### ISSUE TITLE
Network topology display nodes at fixed location

### ISSUE THREAD

**Issue by sachin-samel** [almende/vis#1028]
Hi,

Can we have the control over the starting positions of the nodes?

For e.g. can we set x, y co-ordinates of each node to display it at fixed location?

Thanks

**Comment by AlexDM0** [comment]
Hi,

You can actually set x and y coordinates for each node. 
http://visjs.org/docs/network/nodes.html

If you dont want them to move afterwards, turn off physics or add the fixed option to the nodes.

Please read the documentation a for more information.

Regards

**Comment by sachin-samel** [comment]
Hi,

Please visit the JS bin sample:
http://jsbin.com/sananolete/edit?html,output

Added x and y properties to nodes, but still it is not at the desired positions.

Regards

**Comment by AlexDM0** [comment]
Hi,

It is important to understand that the x and y positions of the nodes are not in DOM space. The canvas has it's own units which relate to DOM space with scale and translation. Imagine there to be a camera hovering over a piece of paper. You can draw something on the paper and it is fixed in the frame of the paper. But what you see in your browser is the image of the camera above it, and that camera you can move.

In your case, after initalizing, the network fits, thus moving the camera. You can turn that off.

http://jsbin.com/tasudebete/1/edit?html,output

Regards

**Comment by AlexDM0** [comment]
You can take a look as to how we matched the positions of the network nodes to the DOM in the source of the network behind the examples

http://visjs.org/network_examples.html

**Comment by sachin-samel** [comment]
Thanks.
It worked!

**Comment by sachin-samel** [comment]
Is there any way to move the viewport to top left corner of canvas?

Currently it draws the nodes from the center of the canvas.

Regards

**Comment by AlexDM0** [comment]
In the jsbin I showed you how to do this with the moveTo method. The offset could also help you depending on what you want. 

Take a look at the moveTo method documentation for more information. 

Regards
