### ISSUE TITLE
Suggestion: Showcase clusters within cluster on your Network Examples

### ISSUE THREAD

**Issue by dragonzone** [almende/vis#1085]
Cluster(s) within cluster is a powerful feature that Vis.js has. You should showcase that in the Network Examples to attract more users just in case they do not realize it.

**Comment by AlexDM0** [comment]
Hi Dragon,

We're open to pull requests for new examples as well. If you have a great showcase on how we can demonstrate this we'd be happy to give it a place in the examples.

There are some examples that do this (the cluster by zoom for instance). How would you suggest we showcase this particular feature?

Regards,

Alex

**Comment by AlexDM0** [comment]
Any ideas?

**Comment by dragonzone** [comment]
I think you can add another example to the following example at: http://visjs.org/examples/network/other/clustering.html. Where you have another button for "Clusters within cluster", that once clicked you can simulate the multiple action, by using setTimeout(), which clusters c1 and c2. Then, another setTimeout(), which cluster c1 and c2 to become c2. Somewhat like some of the example I posted on jsbin & jsfiddle for the bug report, such as this one https://github.com/almende/vis/issues/1281.

**Comment by dragonzone** [comment]
BTW, I saw some examples in your showcase, which looks pretty nice. Unfortunately, the stuff I am using w/ vis.js network is a closed system, otherwise, I would love to share it with you guys. It will probably blow you away. But I try to simulate my work on my own person git, which I mentioned to you before. https://github.com/dragonzone/JsSamplerApp. I just don't have any place to host them. :)

**Comment by AlexDM0** [comment]
We'll see what we can do for the example! Tnx for the idea. 

We can host the code on visjs if you'd like to join the showcase :). I look forward to seeing what you're working on!

Regards

**Comment by dragonzone** [comment]
The sample I write uses a series of libraries both back-end (Java & mainly Spring Framework) and front-end (vis.js, lodash, backbone, handlebars, bootstrap, screenfull, primeui). With the back-end, it'll need some dynamic data, which I don't have but I have a couple of static JSON file to show the how the structure should be. Not sure how to do it yet.

BTW, I just realize that other people ask the same/similar questions as I do and I'm pretty sure I am late in the game with vis.js. I think it may be good if you create a wiki or FAQs for your project. That way you do not have to re-answer the questions/answers again, wasting so much of your time. And also, that way, as your user based grow, they have a quick place to go and you can focus on more "interesing" questions.

**Comment by dragonzone** [comment]
Your vis.js network is a rewrite from of this IBM's i2 Analyst Notebook (http://www-03.ibm.com/software/products/en/analysts-notebook). However, they are a desktop application but they do not have a web app version. The do have an applet version, however, it has horrible support with minimal features as the desktop, therefore, we chose your. But if you have a chance to download & see their demo/trial version, you will be able to see some of the additional features that vis.js is missing. They have a few other layout which vis.js does not currently have, such as the peacock layout.

**Comment by AlexDM0** [comment]
Hi Dragon,

We try to put all the things we learn in the issues in the documentation but there's no fighting people who don't really read the docs.. I'm not sure how a wiki would help. What would we put in there that is not in the documentation? There have been examples born from jsbins in issues but we can't maintain all the jsbins to keep up to date with releases.

We'd be extremely happy with ways to allow users to get the hang of vis quicker with less issues but we're not sure what would work. A FAQ is currently pretty much in the examples. A wiki required additional maintenance etc. The git issues are found by google when people search so in a way they're good. Often people don't search and ask the same question over and over though.

If we could get a community maintained wiki that would be amazing :)

> Your vis.js network is a rewrite from of this IBM's i2 Analyst Notebook

You make it sound like we copied stuff :) I'd prefer the term "has stuff in common with" than a rewrite ;)

Since we build these modules so the rest of our company can use them, we try to only build big features if they're needed. We have never had requests for more layouts so far. Feel free to implement one and pull though ;)

Cheers

**Comment by dragonzone** [comment]
It's just competing ideas. But we find your network better. ;) As me to mentioning the various layouts such as the peacock, I was hoping you guys would do it since I think it deals more with mathematics, which I consider to be pretty stinks at, even though I had a minor in it and haven't touched in a long time. :D I am more of an integrator.

I think adding a few other layout will sometimes help analyst view from different angle/perspective, which more or less help them whatever they are doing.
