### ISSUE TITLE
Request to change oncontext of Network

### ISSUE THREAD

**Issue by stanleyxu2005** [almende/vis#1113]
If I right click on a node or an edge without having selected, I have to use position (`event.pointer.DOM`) to calculate the element under mouse cursor. It is a bit inconvenience. Do you think it is worthy to tell user the information directly?

I suppose to have 
```
{
  activeElement: {
    type: 'NODE' /* or 'EDGE' */, 
    id: the_id
  }
}
```
Currently I wrap the oncontext event with my own...
```
network.on('oncontext', function(args) {
  var selection = network.getNodeAt(args.pointer.DOM);
  if (selection !== undefined) {
     handleOnContext(args.extend({activeElement: {type: 'NODE', id: selection}}));
  } else {
     selection = network.getEdgeAt(args.pointer.DOM);
     if (selection !== undefined) {
       handleOnContext(args.extend({activeElement: {type: 'EDGE', id: selection}}));
     }
  }
});
```

**Comment by stanleyxu2005** [comment]
Any opinion? On the plan list or rejected? I think it makes sense. But you don;t agree, please close the issue.

**Comment by AlexDM0** [comment]
Hi,

We have never used the type field in any of the events so it will not be likely that we will change this for the right click handler.

This is not really a priority for us, I think it's dependent on the use case what information you want. I like the consistency of the event data as it is now. 

Since all methods you need are already available we may consider changing this event for the next breaking release.

Regards

**Comment by stanleyxu2005** [comment]
As it does not meet common interests, I close it.
