### ISSUE TITLE
BPMN editor with vis.js

### ISSUE THREAD

**Issue by cmuelder** [almende/vis#1124]
Hi,

This is a questions post!!!

I am developing a bpmn web designer for our company and started using canvas itself. But seeing your project, i thought about refactoring it. I have seen the examples and need to make sure, that everything i need is already posible or could to contributed. I use the functionality from the network part. 

What i was missing is way to define a layout scheme for bpm processes. Is this already available? 

Is it possible to draw connections between nodes (in realtime)? Regarding the interaction, this doesn't seem to be necessasry for network. 

Is it possible to extend nodes with tooling (e.g. to draw connections between nodes)

Thanks in advance for answering!

Best regards,
Christian

**Comment by AlexDM0** [comment]
Hi,

It is possible to drag edges between nodes. Take a look at the manipulation example. 

That being said, this is not the usecase the network is made for. The network has been designed for data visualisation first. 

For this specific usecase I think you would be better off using SVG instead of canvas. 

Since we have not built network with bpmn in mind, there is no support for a layout scheme. There is however support for dot language. Since I'm not familiar with the bpmn process definition other than a quick wiki lookup, I'm not sure what sort of things are required. Edges with multiple corners are not easily shoehorned into network (except when using invisible nodes as corner points). 

Could you supply a more clear requirements list so I can judge I what is easily implemented and what is already there?

Regards,

Alex

**Comment by cmuelder** [comment]
Hi Alex,

Thanks for the quick response.

Instead of writing, i thought it would be eeasier to upload some screen from the eclipse BPMN desinger to preview some requirements like tooling, drag & drop, resize, ediges with handles...! And everything should be highly interactive as shown in the two tooling sceens.

Best regards,
Christian

![drag_resize](https://cloud.githubusercontent.com/assets/13118933/8906806/d7fac5f8-3471-11e5-9dc7-015b41e549b2.png)
Nodes need to be selectable, draggable and some resizeable. You need to drau edges between nodes.

![edges](https://cloud.githubusercontent.com/assets/13118933/8906807/d7fb5b62-3471-11e5-8a15-4f5cb717ec6e.png)
Edges should be arranged vertical and horizontal!

![tooling1](https://cloud.githubusercontent.com/assets/13118933/8906809/d8039afc-3471-11e5-95cb-73768e24c6bb.png)
Interactive tooling for selected and hovered nodes.

![process](https://cloud.githubusercontent.com/assets/13118933/8906808/d8020408-3471-11e5-9746-cc740fede476.png)
Shows a different kind of tooling for notes.

**Comment by cmuelder** [comment]
Sorry, did not want to close it!

**Comment by AlexDM0** [comment]
Hi,

This is not what vis is suited for. I think you'll need to look for a different tool.

Regads

**Comment by cmuelder** [comment]
Hi Alex,

Thanks for your fast support! 

I wish you all the luck and success with your nice project.

Best regards,
Christian

**Comment by AlexDM0** [comment]
Thanks, good luck finding a suitable library!
