### ISSUE TITLE
SVG loading problem in Firefox

### ISSUE THREAD

**Issue by guptakeshav** [almende/vis#1132]
http://visjs.org/examples/network/nodeStyles/HTMLInNodes.html
The above example shows the usage of SVG images in Nodes. But when I try to run this example in Firefox, the images sometimes doesn't loads. On Chrome, it works fine.
When I checked the console, it showed me an error "NS_ERROR_NOT_AVAILABLE", when the library tries to call "drawImage()".
On searching about this, I found the following link:
http://stackoverflow.com/questions/18580844/firefox-drawimagevideo-fails-with-ns-error-not-available-component-is-not-av
It states that this is a bug in Firefox, which is already mentioned in Bugzilla. And a user has also given a workaround for it to work in Firefox.
So, can you please implement that workaround or something else, so that it will always work in Firefox.

Thanks,
Keshav Gupta

**Comment by AlexDM0** [comment]
Hi,

That workaround does not work for vis. We use scheduled redraws for animation and physics. Even if the drawing works (try spamming network.redraw()) the render loop keeps crashing.

Another problem is that the network has moving nodes. If you keep repeating the draw call without updating the position, the position the node is drawn can be very wrong.

Finally, there is a clear warning that it does not work on all browsers. Your issue is an example of this. I'm sorry but there is nothing we can do for this.

Regards,

Alex
