### ISSUE TITLE
[Network Feature Request] can shadows have colors?

### ISSUE THREAD

**Issue by Tooa** [almende/vis#1138]
Hi,

have a look at [this example](http://jsbin.com/qeyikumile/edit?html,output). I would expect to get a green edge highlighting. Not sure, if this behavior is explained by the documentation here:

`When color, highlight or hover are defined, inherit is set to false! ` ([Reference](http://visjs.org/docs/network/edges.html))

Best Uli

**Comment by AlexDM0** [comment]
Hi Uli,

Yes, that is exactly what is ment by that part of the docs. The inherit overrules all color information.

Regards

**Comment by Tooa** [comment]
> The inherit overrules all color information

This explanation is far better than the current one in the docs. I suggest to change it. I can do a pull request for it, if you like to. 

<b>OT</b>: Do you know how to achieve a similar glow effect like in the following picture for visjs?
![glow](https://cloud.githubusercontent.com/assets/5375334/8983482/e80dc70a-36ca-11e5-8c52-9c0451146a17.png)

**Comment by AlexDM0** [comment]
Hi Uli,

I think you'll need to use the shadow property but it does not use colors at the moment. Just black. Maybe in future releases?

We're open to pull requests for improvements anywhere :)

Regards

**Comment by AlexDM0** [comment]
https://github.com/almende/vis/blob/master/lib/network/modules/components/edges/util/EdgeBase.js#L506

and 

https://github.com/almende/vis/blob/master/lib/network/modules/components/nodes/util/NodeBase.js#L27 

If you're feeling up to it :)

**Comment by Tooa** [comment]
I'm a little bit confused regarding the color topic. Assume you have several node groups (`{"id":"1689","label":"XXX","group":8, ...`). By using the `inherit` property the edges get different colors for each group assigned. This is nice. But, how to enable edge highlighting and also preserving the edge colors at the same time? If you remove the `inherit` property and add the `highlight` property, all edges will get the same color - which is bad. 

The only way to get different colors for the groups, is to individual assign for each edge a color according to their group membership. It would be nice to still use the automatic color assignment. Am I missing something?

I would love to have glowing edges, but I'm not very into this web development stuff. It's more like a burden for me :D I will see, what I can do.

**Comment by AlexDM0** [comment]
when using inherit, the edges get the color of the node's border. This includes the highlight and hover border colors for the highlight and hover cases. 

If you manually define the highlight, it will use the default colors for all fields you didnt manually specify. If you look at the configurator it may be clearer. You override a single value. To answer your question, yes if you want to have fully customized colors, you'll have to customize all of them. There has been a request for groups for edges just like nodes but this will not be added soon due to the fact that its very busy here at the moment and we have no need personally for this feature.

Regards,

Alex

**Comment by Tooa** [comment]
> There has been a request for groups for edges just like nodes but this will not be added soon due to the fact that its very busy here at the moment and we have no need personally for this feature.

I see. In my case, I need to use the edge coloring for groups, because I use pictures as nodes and therefore I have no node color. I think I will manual assign colors to edges according to their membership as workaround. I also thought of using a custom shape for the nodes like in [this example](https://camo.githubusercontent.com/3d46358d0bc4d44328627127fde7cfbe2e89b620/687474703a2f2f73796e74686f6d61742e64652f746d702f787a6e39792e706e67). Then I could color the shape and have the image inside the shape. Do you have a pointer to achieve such a shape? I only know the circular image example.  

![coloring](https://cloud.githubusercontent.com/assets/5375334/8984184/479a0968-36d0-11e5-80ad-46bdaab9f8ee.png)

**Comment by AlexDM0** [comment]
You could still give nodes with the image shape a border color. They wont get a border, but the edges will take it.

Regards

**Comment by Tooa** [comment]
> You could still give nodes with the image shape a border color. They wont get a border, but the edges will take it.

Ah, I was not aware of this. But I still need to assign the color for each node according to its membership myself. I will see, if it's still worth to implement the assignment for just having a edge highlighting. 

While we are talking about it: Are there any plans for [re-sizing images in circular shapes](http://jsbin.com/todudohezo/1/edit?html,output)? A fitting shape around the images in the image example above would be better than just having this big images.

**Comment by AlexDM0** [comment]
I'm not sure what you mean by resizing images in circular shapes. I am now resizing the shape so it's smallest side (width or height) matches the circle. If I don't do that, you'll get a rectangle in a circle. You can use the useImageSize in the shapeProperties http://visjs.org/docs/network/nodes.html to have the size of the node determined by the size of the image instead of the size you supply.

What is the result you'd expect?

You can also just use groups to classify the colors instead of doing this per node (you'll still need to supply a group per node though).

Regards

**Comment by Tooa** [comment]
Sry, for the late response I had quite a lot of exams. My "re-sizing" question has been resolved by this feature 11318647fec16c27ecdf1f88bd8f3c011f8277e8. Thank you very much! Compare the result [1] to the same example using circular shapes [2]. Next I will try to get the label inside the shape. 

[1] http://jsbin.com/cequbupici/1/edit?html,output
[2] http://jsbin.com/todudohezo/1/edit?html,output

**Comment by AlexDM0** [comment]
Hi,

Will be added in the next release.

Regards

**Comment by AlexDM0** [comment]
Ths has been released in 4.12
