### ISSUE TITLE
Network: Laggy on Android WebView

### ISSUE THREAD

**Issue by Jonty800** [almende/vis#1173]
Hi, I'm writing a simple network chart for use inside an android WebView. 

Do you have any tips on reducing lag? It is not very responsive and seems to be low FPS. My options are such:

https://gist.github.com/Jonty800/3579bb0c70058df6bded 

![image](https://cloud.githubusercontent.com/assets/1188837/9146558/a5226400-3d55-11e5-8f85-fa0687aeef85.png)

Also, as seen in the above picture, I sometimes get a highlighted border when clicking too much. This also happens on Chrome (PC). How can I disable this effect?

Cheers!
Jon

**Comment by josdejong** [comment]
http://stackoverflow.com/questions/18601824/disable-orange-highlight-on-a-div-in-webview

**Comment by josdejong** [comment]
About the performance: mobile devices are typically slower than PCs/laptops, so it's important to keep the number of nodes limited.

One thing that can improve performance a bit: disable smooth edges (see example: http://visjs.org/examples/network/edgeStyles/smooth.html)

**Comment by AlexDM0** [comment]
Hi,

I think the lag is due to the implementation of the drawing in that browser. The circular images are quite heavy for mobile. If the graph is as small as you show us here, the computation is negligible. All lag is due to drawing. You can try if the normal image type is smoother. You'd have to make your images into these circles manually.

Regards
