### ISSUE TITLE
IE8 compatibility

### ISSUE THREAD

**Issue by Gargaroz** [almende/vis#1232]
I know vis.js is just compatible with IE9+ only, but I'm wondering if:

* anyone knows a workaround to get it working with IE8+, as I initially thought to include an `Object.create` polyfill, but then I realized I might need other polyfills when new errors will pop out, and even if I just need that single polyfill it might just be a way to shallow of a solution for vis.js;

* anyone is aware of the reasons why the workaround I'm looking for it's basically impossible to implement or/and too risky to use;

Thank you in advance

**Comment by AlexDM0** [comment]
Hi,

I really just would not bother. For all features we assume IE9+. There can
be so many small things going wrong I wouldn't know where you'd want to
start. It would take a LOT of time to rewrite the parts, it would perform
terrible as the IE8 JS engine is just plain crap and nobody would really
win here.

If you're going for the network or graph3d module, the canvas would not
work. If you're going for the graph2d, SVG is not likely to work. Timeline
is pure DOM so that might be the only one. Still, I wouldnt bother.

Regards

**Comment by Gargaroz** [comment]
Thank you for your answer.

**Comment by Gargaroz** [comment]
Even if this issue is closed, I wish I can hear from other users struggling to use vis.js in IE8 like me.

**Comment by AlexDM0** [comment]
I'll open it for a while but this is not really a forum.

**Comment by josdejong** [comment]
You will at least have to load es5-shim, es5-sham, and [https://github.com/jwmcpeak/EventShim/blob/master/eventShim.js](eventShim.js). Then there are still some issues left, it may be solvable, just follow the errors that you get in the developer console of IE8 and try to fix them.

**Comment by Gargaroz** [comment]
@josdejong thank you for your advice; I just want to add the libraries I'm already including in my project to handle compatibility issues (I'm developing an AngularJs, Bootstrap web-app):
```html
<script type='text/javascript' src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.7.1/modernizr.min.js"></script>
<script type='text/javascript' src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<script type='text/javascript' src="//cdnjs.cloudflare.com/ajax/libs/respond.js/1.4.2/respond.js"></script>```
