### ISSUE TITLE
Node position issue when using network on popup window

### ISSUE THREAD

**Issue by bdvops** [almende/vis#1254]
Please see this simple example (you need to disable blocking of mixed content)

http://jsbin.com/wodewiguye/1

There are two networks on the page.  The first is a div on the actual page and the other is within a model popup.  The one on the page loads properly but the popup network does not.  The nodes do not position themselves in the center of the canvas and actually when running within JSBin, the nodes do not show at all.  But that seems to be a JSBin issue.  How can I make the nodes/network behave the same in the popup as if it was on the page itself?

**Comment by AlexDM0** [comment]
Hi,

This seems to be due to bootstrap, though why I have no idea. @josdejong, do you have any ideas?

Regards

**Comment by josdejong** [comment]
It's because the container div is not visible at the moment the Network is drawn.

I tried calling `network.redraw()` *after* the modal has become visible, that should do the trick but apparently does not work for some reason.

**Comment by bdvops** [comment]
I'm not a JS guy so I have no idea how to do it but is there a way to get a callback on when the modal container div is visible then call draw()?

**Comment by AlexDM0** [comment]
Hi,

I fixed a serious bug which caused the network not to draw in hidden divs.

You will still need to call the fit() method because the network may be displayed off screen when you show the div.

Looking at what you use for the plugin, I'd suggest a simple timeout (time now based on your loading animation)
```
setTimeout(function() {network.fit()},250)
```

Thanks for reporting! We'll try to do a bugfix release very soon.

**Comment by AlexDM0** [comment]
This has been fixed in 4.8.1
