### ISSUE TITLE
Edges displayed between transparent parts of the nodes. Hierarchical layout

### ISSUE THREAD

**Issue by seemakamble** [almende/vis#1270]
Hi,

When using font-icons for nodes in hierarchical network layout, the edges below the nodes are also visible.

Please see the attached screen grab.

Is there any way to hide these edges or start the edges from the node border?
![edges below icons](https://cloud.githubusercontent.com/assets/14121871/9679352/8cd3f9ec-530b-11e5-9533-107c8f024f3e.jpg)

Here is the plunker link : http://plnkr.co/edit/vFmu12QX7odURrBY4FCJ?p=preview

Thanks,
Seema

**Comment by AlexDM0** [comment]
Hi,

Easiest way would be to use custom images with a center that is not transparent. 

It is very computationally intensive and sometimes not possible to detect the exact location of the edge. We have assumed that nodes cover it up and this is not likely to change due to performance. 

Regards,

Alex
