### ISSUE TITLE
Network Images keeps applying physicis

### ISSUE THREAD

**Issue by ppierce01** [almende/vis#1280]
I am new to this library and also new to Java in general.  I am trying to create a network diagram with images and have all most got it working with this code:

      // create a network
      var container = document.getElementById('mynetwork');
      var data = {
        nodes: nodes,
        edges: edges
      };
      var options = {

        nodes: {
          borderWidth:1,
          size:55,
	      color: {
            border: '#222222',
            background: 'grey'
          },
          font:{color:'black'}
        },
	
		
        edges: {
			
			arrows: {
				  to:     {enabled: false, scaleFactor:1},
				  middle: {enabled: false, scaleFactor:1},
				  from:   {enabled: false, scaleFactor:1}
					},
			color: {
				color:'#848484',
				highlight:'#848484',
				hover: '#848484',
					},
			font: {
				  color: '#343434',
				  size: 14, // px
				  face: 'arial',
				  background: 'none',
				  strokeWidth: 5, // px
				  strokeColor: '#ffffff',
				  align:'horizontal'
				},
			smooth: {
						  enabled: false, //setting to true enables curved lines
						  //type: "dynamic",
						  //roundness: 0.5
						},
			physics: false
				}
		
      };
		
		network = new vis.Network(container, data, options);
		
    }

The diagram loads properly with the nodes and edges.  The problem is when I start to drag the noses to arrange them the way I want them I can drag several of them but then all of a sudden the physics kicks in and moves everything again.  I have seen, earlier posts,  about disabling the physics using the Network.options() and have attempted to add that code, but I can't seem to get the syntax right.  Can you point me to an example or documentation where this is done?

**Comment by dragonzone** [comment]
Physics is set on the network object, not on nodes or edges, here is how to do it:

```
network.setOptions({
	physics: {
		enabled: true|false
	}
})
```
Here is the documentation: http://visjs.org/docs/network/physics.html

**Comment by AlexDM0** [comment]
Hi,

You have disabled the physics in the edges. This is possible and means that they will not be modeled as springs. You still have the physics of the nodes enabled, which means you'll see a combination of the central gravity and the gravitational repulsion.

Regards,

Alex

**Comment by AlexDM0** [comment]
On a sidenote, this is not Java ;)

**Comment by ppierce01** [comment]
Thanks DragonZone.  I had tried that but the diagram would not render.  It is working now after I moved the code provided out of the var ortions section and placed it after the network =new statement.  The documentation was a little confusing and caused me to assume the network set options( ) went in the same area as the nodes and edges options.

**Comment by AlexDM0** [comment]
Hi,

Could you specify which part of the documentation was not clear? We're always open for improvements. 

Regards

**Comment by ppierce01** [comment]
Sure but keep in mind I am a green horn and to someone more experienced the documentation may make perfect sense.

In my situation I started with an the example CircularImages.html.  In that example the code looked like this

               var options = {

nodes: {
code here
},
Edges: {
code here
}
};

Network = new vis.network(container, data, options);

When I got to the point where I was trying to stop the physics I saw in the documentation the physics options were all shown within the var options section as described above.  With the network.SetOptions(options); outside or under the var options section.  So I placed the physics: {enbled:false} within my code so it now looked like this:

var options = {

nodes: {
code here
},
Edges: {
code here
},

                                physics: {enbled:false}

};

Network = new vis.network(container, data, options);
                                network.SetOptions(options);

This did not work and the diagram would not render.

In response to my post, DragaonZone provided this code example


network.setOptions({

    physics: {

        enabled: true|false

    }

})

Which I placed within the var options section and again it would not work.  I then moved code example out of the var options= section and placed it as shown below,

network = new vis.Network(container, data, options);
                                network.setOptions
                                (

                                                {

                                                                physics: {enabled:false}
                                                }
                                );

And everything is now working, the diagram is rendered and I can drag the nodes with no physics.

I hope this is helpful for you and is clear enough.  I have attached my entire project for you to look at if that helps any.

I appreciate your willingness to work with me and really like your solution.

Thanks Perry

**Comment by longcdo** [comment]
I think the documentation is excellent and very surprise by the 100s of configurations available, which I tried to apply to our own app. I just think you are missing some of the JavaScript fundamentals and therefore, are kind of lost. Before learning JS, I had a Java background. I thought JS would be very similar to Java, but in fact, there's a lot of differences. Though I am still continuing to learn JS and the many OS JS libraries out there, such as vis.js. I would best advise that you read up more on JS.

Now back to your comment. There are multiple ways to set options. One is to set the options BEFORE you pass "new vis.Network(container, data, options);", to create the network. Notice the "options" parameter at the end, which you have set other stuff there. The other options is my way, network.setOptions(), which AFTER the network has been drawn, you can change the various options to it, such as disabling the physics. I use the latter method when user wants to manually change options or setting themselves instead of using the default.

**Comment by dragonzone** [comment]
I think the documentation is excellent and very surprise by the 100s of configurations available, which I tried to apply to our own app. I just think you are missing some of the JavaScript fundamentals and therefore, are kind of lost. Before learning JS, I had a Java background. I thought JS would be very similar to Java, but in fact, there's a lot of differences. Though I am still continuing to learn JS and the many OS JS libraries out there, such as vis.js. I would best advise that you read up more on JS.

Now back to your comment. There are multiple ways to set options. One is to set the options BEFORE you pass "new vis.Network(container, data, options);", to create the network. Notice the "options" parameter at the end, which you have set other stuff there. The other options is my way, network.setOptions(), which AFTER the network has been drawn, you can change the various options to it, such as disabling the physics. I use the latter method when user wants to manually change options or setting themselves instead of using the default.

**Comment by ppierce01** [comment]
Thanks,

You are correct I definitely need to do some more reading on JS.

Sorry to be a pest but  if I understand what you are saying the  network.setOptions run after the network has been loaded and rendered on the screen.  So I would assume the setting above in the var options ={} section would all be in play until the network stabilized.  Once stabilization has completed, then the physics would be disabled.

However that is not what I am seeing, I am adjusting the springLength parameter in the var options section, which is above the network.setOptions(),  but those setting are not being applied if I disable physics in the network.setOptions section which is after network = new.

Thanks Perry

**Comment by AlexDM0** [comment]
Hi Perry,

Vis has Events. Events are triggers you can listen to in order to execute code at that point. 

I will assume that you want the following: You start a network, want the physics to stabilize it, then disable the physics on stabilization so you can drag the nodes around manually.

In order to do this you load the network with your options for nodes and edges. 

You also listen to the stabilizationIterationsDone event like so:

```
network.on("stabilizationIterationsDone", function() {
  network.setOptions({physics:false});
}
```

There is a difference between stabilized and no physics. If the network has stabilized the physics stop, correct, but once you move something the network will not be stable any more and the physics do their best to make up for it. What you want is to completely disable the physics when the initial stabilization phase has finished.

This initial phase is made up of a few parts:
- startStabilization 
- stabilizationProgress (until iterations are done or network is stable)
- stabilizationIterationsDone

There are by default 1000 iterations for the stabilization. If the network is stable the stabilizationIterationsDone AND the stabilized event will fire. It can happen that after 1000 iterations your network is not officially stable. In this case, the nodes will continue moving until they are stable. Only then the stabilized event is fired.

Hopefully that clears it up a little.

As for the spring length, By default you're using the barnesHut solver. You will need to modify this:

```
{physics:{barnesHut:{springLength: number}}}
```

Could you use jsbin for code examples in the future?

Also take a look at our examples for more information:
http://visjs.org/examples/network/physics/physicsConfiguration.html
http://visjs.org/examples/network/events/physicsEvents.html

Regards,

Alex

**Comment by ppierce01** [comment]
Alex thank you very much for your patience, explanations and examples.  My network is performing just as I needed it to.

I started this process last Friday and have a fully functioning network diagram in only 3 and half days.  Prior to finding the VIS library I had  built a network diagram using the D3 library.   it took me all most a month to figure it out and it was not meeting all of the client’s needs, using D3 it was impossible to save the diagram with the images.  When my Manager suggested I look into another API I was not looking forward to trying to learn another product.  I must say your product has a lot of good examples and documentation which made this process much easier.



Thanks Again Perry

**Comment by AlexDM0** [comment]
Hi Perry,

Glad to hear everything is working well!

Enjoy using vis!
