### ISSUE TITLE
Network Manipulation:Edit Node icon not visible properly after addNode is false

### ISSUE THREAD

**Issue by vramali1** [almende/vis#1311]
Hello, 
I am using manipulation to create graph. I have disabled addNode : false and EditNode: true. when I did that I see that the Edit Node icon is not displayed properly with alignment issues. I was able to reproduce the issue in 2 different environments. Could you please tell me how it can be fixed.
Thanks

**Comment by AlexDM0** [comment]
Hi,

This issue is two things: 
1 CSS misalignment, which I've fixed on the develop branch.
2 The edit node button not showing because you set it to true while it can only have a function:
http://visjs.org/docs/network/manipulation.html

So 1 will be fixed in the next release, 2 is up to you :)

For an example on what to put in the function, take a look at this:
http://visjs.org/examples/network/other/manipulation.html

Regards

**Comment by AlexDM0** [comment]
Released in v4.9.0
