### ISSUE TITLE
Network: Default edge minLength

### ISSUE THREAD

**Issue by dragonzone** [almende/vis#1322]
In the network options, you can set:

```
edges: {
	length: linkAnalysisVar.edgeLength
},
```
which set the length for all the edges on the network. However, once you set that all the edges will have the same length. The issue arises when I have 100s or 1000s of nodes, they will be so close together creating a circle. If I do not set that edges' length, each edge will their own length, which is what I want. However, I have a feature where I allow the user to stretch the edges longer RELATIVE to than their default value, so they can easily analysis the network. So how can I do this? For example, I have these edges length once drawn:
```
e1 - len: 200
e2 - len: 275
e3 - len: 325
To easily analyze the network, I will increase each edges length by 200, which will become:
e1 - len: 400
e2 - len: 475
e3 - len: 525

```

**Comment by AlexDM0** [comment]
Hi,

These lengths are an indication, they are the lengths of the springs at rest. Since there is repulsion, the  edge becomes longer. I would suggest you'd increase the edge length and the spring constant together. I do not think the feature you're proposing will really do what you want it to do. Keep in mind that the physics eventually determine the length of the edge.

Regards
