### ISSUE TITLE
Services(virtual sub-edges) in vis.js

### ISSUE THREAD

**Issue by salacoste** [almende/vis#1350]
Hi,
I want to highlight the edges through which the connection.
As example:

Logic edge: from c to a
but in real edges the logis through c->b->e->a, and i want highlight the real edges when i search the logic edge.

Is it possible via standart instruments of vis.js?
What could you recommend for implement this task?

Thanks for future,
Ivan

**Comment by josdejong** [comment]
This is perfectly possible to do with vis.js, but you will have to write the logic for highlighting this chain of edges yourself. You can give the edges that you want to highlight a different styling.

**Comment by salacoste** [comment]
Thanks u, 
I have logic: get the list of connections which need to highlight [1-2;2-4;4-6;6-3] for example.

I have 2 questions:
- How i could implement sql result from my DB to vis.js?
- Could i freeze nodes from moving and that every render the nodes stay the same position as before. (every render nodes are jumping at default)

**Comment by josdejong** [comment]
You can make nodes fixed by giving them a `x` and/or `y` property.

Getting SQL results from some database into your browser and display it with vis.js is a bit out of scope. The data from your database must be exposed via a REST API using some server. You can load the data into your browser by doing an AJAX call. You can search on google how all of this works, this is not related to vis.js.

**Comment by salacoste** [comment]
Thank you josdejong, i already trying use x/y properties.
I want make edit view, there is nodes is draggable and when press button all node positions save to library.
How i could get current node positions from canvas?

**Comment by josdejong** [comment]
See docs on methods `Network.getPositions(nodeIds)` and `Network.storePositions()`.

http://visjs.org/docs/network/#methods
