### ISSUE TITLE
Vis JS: Node positioining after window resize is not workjing

### ISSUE THREAD

**Issue by vramali1** [almende/vis#1369]
Hello, I have created a Vis JS network with X and Y coordinates and autoResize:true option. I store the x and y cooordinate in the following way
x = Mouse X Coordinate/Window Width
y = Mouse Y Coordinate/Window Height

After I resize the window, The nodes lose their X and Y positions and is not exactly positioned whereas the nodes are resizing. Could you please tell me how can i position the node correctly on window resize.

Thanks.

**Comment by josdejong** [comment]
I'm not sure what you try to achieve. Network has it's own coordinate system. You can use methods like `getPositions(nodeIds)` or `storePositions()` to retrieve these positions in order to restore them later on ([see docs](http://visjs.org/docs/network/#methods)). Using a function like `fit()`, the nodes in the Network are scaled such that they neatly fit the window.

**Comment by Tooa** [comment]
> Using a function like fit(), the nodes in the Network are scaled such that they neatly fit the window.

Is the node scale/size really changed or is it more like a zoom out as mentioned in the docs [1]?

[1] http://visjs.org/docs/network/index.html?keywords=fit

**Comment by josdejong** [comment]
It's indeed zooming/moving the viewport such that the contents fit.

**Comment by vramali1** [comment]
Got it, Thanks.
