### ISSUE TITLE
HowTo: fixed group of nodes

### ISSUE THREAD

**Issue by zero-delay** [almende/vis#1380]
Hello,

which direction should I follow to make nodes like those in the picture?

What if I declare an hidden node inside the black shape, with two hidden edges toward the little red nodes? Is there a way to keep these edges at a fixed length and not partecipating in the physics?

Enrico
![stars](https://cloud.githubusercontent.com/assets/14863672/10567390/6b40ce34-7603-11e5-9a06-c970d729fec0.png)

**Comment by josdejong** [comment]
hm that doesn't sound easy to do. It would require an edge with a fixed length between the red and black nodes. Maybe it works by specifying the right length for these edges and giving them (almost) infinite stiffness. It's not possible right now to give edges a stiffness individually, so that would require hacking into the code of Network.

**Comment by AlexDM0** [comment]
This is not possible with vis. Feel free to change the source to suit your needs though.
