### ISSUE TITLE
show hide a node by id

### ISSUE THREAD

**Issue by oceatoon** [almende/vis#140]
Hi
Thanks for your great work 
I'm making a tag filter on a graph, 
I can't find in the docs how to show hide a node in a graph with it's ID ?
is there a sample with something like this ?

**Comment by wolfig** [comment]
Just because I ran into the same problem and Alex's comment helped me some hits that might be useful:

1) Alex's code line 
`nodes.update(...)`
refers to DataSets, not to network.nodes

2) You can update the attribute "hidden" in the node-dataset, so they become invisible. Here a code snippet of updating a bunch of nodes:
```
		var updateArray = [];
                 for (nodeCounter = 0; nodeCounter < nodeCount; nodeCounter++) {
			updateArray.push({id: idsOfNodesForUpdate[nodeCounter], hidden: true});
		}
                nodeDataSet.update(updateArray);
```

**Comment by mvivekc** [comment]
FYI: The above code does not take care of all the edges assigned to it the hidden node. This needs to be taken care of with another forLoop on the edges array. Still, did not know about hidden field. Thanks.
