### ISSUE TITLE
Error using PhantomJS

### ISSUE THREAD

**Issue by ramnathv** [almende/vis#1525]
I am trying to captures screenshots of a network visualization using PhantomJS. I tried the following based on the article on screen-capturing that can be found [here]

```bash
phantomjs ./rasterize.js "http://visjs.org/examples/network/basicUsage.html" basicUsage.png
```

I am getting an error and the resulting image does not have the network.

```
TypeError: 'undefined' is not a function (evaluating 'this.on.bind(this)')

  http://visjs.org/dist/vis.js:27262 in Network
  http://visjs.org/examples/network/basicUsage.html:50
```

Can anyone provide me with ideas on how I can use PhantomJS for screenshotting vis.js network plots?

**Comment by josdejong** [comment]
I think this is a duplicate of #1170.

**Comment by dragonzone** [comment]
There are lots of issues using Phamtom.js. There are a few ways using vis.js to get screenshot. One way is like this sample I built here: https://jsfiddle.net/f5up4o2g/

The other way to solve this problem is reading this other one here I stated awhile back: https://github.com/almende/vis/issues/1535

Hope this helps!
