### ISSUE TITLE
Barchart fill-opacity

### ISSUE THREAD

**Issue by Sillanmaki** [almende/vis#1551]
Barchart fill-opacity won't change anything.

.custom-style1{
  fill: #03A9F4;
  fill-opacity: 1;
  stroke-width: 0px;
}

**Comment by ludost** [comment]
Hi Sillanmaki,

This is caused by the relative high css specificity (level 2, e.g. ".vis-timeline .vis-bar") of the css classes in vis.css. This can be solved by making the custom-style also level 2 or by using !important.

Example of the first solution:
.vis-timeline .custom-style1 {
    fill: #03A9F4;
    fill-opacity: 1;
    stroke-width: 0px;
}

Since release 4 of visjs, all css classes are prefixed with "vis-", which should allow us to make the css classes less specific, as the names are more-or-less unique now. I'll check if this is doable in the near future.
