### ISSUE TITLE
network and data by ajax

### ISSUE THREAD

**Issue by Xerrass** [almende/vis#1611]
Hello community probabaly you can quickly help me but im strugling to build a Network wich gets updated every 10 seconds with data froman AJAX request is there anything i that i missed?

there is nothing in the examples as far as i know.

Jonathan

**Comment by AlexDM0** [comment]
Well I won't go in to the Ajax part since that has nothing to do with vis, but there are many examples showing the use of the dataset for dynamic data. There is documentation on it as well as other methods on how to work with data. 

Id suggest you look for those. If they are so well hidden from view, I'd be happy to hear ideas on how to improve their visibility.

**Comment by Xerrass** [comment]
Hey thx for the Fast response  personaly im in my beginning carrier of javascript and ajax so im a bit strugling with everything ;-) 
what for me realy coud help is a well explained things as of the setData function is ofcourse explaind but im strugling with the use of it so a real good commented pice of code.

but it coud be that im strugling because of my small JS knolage!

**Comment by AlexDM0** [comment]
Hi,

well we're not a JavaScript help desk but since I'm in the train, let's give it a shot. 

Basic setup: 
Use the vis.DataSet for your nodes and edges. See examples in dynamic data. 

Create network. 

When Ajax data comes in, make sure it is valid JavaScript and vis format (array of JSON) and use the dataset update to add the new data.

Do not use setData because it will completely reset your network, requiring it to settle over and over. 

Now a few things to test:
Do the Ajax call without the network and console.log the result to get an idea if it works and if you can use the data. 

Create a network without Ajax and use the JavaScript method setTimeout to fake data coming in at a later time. See if your data is successfully propagated to the network. 

Have fun

**Comment by Xerrass** [comment]
ok gotcha its working for real thank you for your help has givven me a headsup :-) :+1: 
as i have fast changing datasets ruphly every 3 seconds is it posibal to always draw a dataset the same way ? so everytime lets say im poping in 5 nodes each connected to each is it posibal that each node is everytime on the same position ?

i already set the random stirng but its still not static?

**Comment by AlexDM0** [comment]
you mean the randomSeed number? I have no idea what you mean. If you define
a random seed the layout will be the same. Static and in the same postition
are two very different things..

**Comment by Xerrass** [comment]
ok will explain it:

take a city in mind now take TOMTOM a GPS Navi so the TOMTOM will always display things the same way because the streets are not mooving.

so if im efreshing even with the randomseed set to 1 it looks kinda different!

but everytime when i have the same data (the same nodes same edges ) shoudnt it look exactly the same ?

**Comment by Xerrass** [comment]
im sorry its looking the same!

**Comment by AlexDM0** [comment]
... problem solved
