### ISSUE TITLE
items on timeline get deselected

### ISSUE THREAD

**Issue by YiuriV** [almende/vis#1614]
Hi,
I have a mapviewer which uses the timeline to view historical maps. I've been able to create seperate click and doubleclick events so I can select 2 different maps on the timeline in order to compare them. However, when I want to change the opacity, the timeline item gets deselected as soon as I click on the slider.

I'll upload the homepage with the code. If someone could tell me where I'm wrong that would be great.

Thanx

edit: the item gets deselected when I have my developertools open
[index.TXT](https://github.com/almende/vis/files/108427/index.TXT)

**Comment by josdejong** [comment]
I don't see a screenshot or link to a site, but this sounds like the slider on the map does not stop propagation of the click event, so the Timeline also gets this click event and handles it accordingly. 

In order to stop event propagation, you probably have to create a Hammer.js (you can use `vis.Hammer`) event listener for click and stop that, as hammer.js does not respect event propagation.

**Comment by yotamberk** [comment]
@YiuriV Is this issue still relevant? I can't get your example working

**Comment by yotamberk** [comment]
closed for inactivity
