### ISSUE TITLE
How to get node object with 4.14.0

### ISSUE THREAD

**Issue by stanleyxu2005** [almende/vis#1669]
I have sticked to 4.7.0 too long. Today I tried to upgrade to 4.14.0, I found many errors in my code. One of them is that I cannot get the node size using the code now:
```
    network.findNode(0)[0].options.size;
```

I read the document, I found most methods will now return node id instead of node objects. A very close method can be `network.getBoundingBox(nodeId)`. But `right - left` does not equal the radius that I've set in options. How to get this value? 

Is there any migration guide?

**Comment by AlexDM0** [comment]
The fact that that worked in the first place was a bug. The code returned an internal node object instead of the node id. The method now does what the documentation says it does.

With the ID you can get the options you need. If you need options of the clusters, you manually inputted them so they will have to be cached.

Regards

**Comment by stanleyxu2005** [comment]
Got it. Finally I noticed my code does not require to obtain node's radius from the current instance.
