### ISSUE TITLE
Select,Deselect events not triggered when switching between node and attached edge

### ISSUE THREAD

**Issue by dimosr** [almende/vis#1771]
In the following network: 
(nodeA) - [edge1] -> (nodeB)

When:
1) Selecting nodeB
2) Then, selecting edge1
"_deselectNode_" event is triggered for nodeB
But, "**_selectEdge_**" event is **not triggered** for edge1

Also, when:
1) Selecting edge1
2) Then, selecting nodeB
"_selectNode_" event is triggered for nodeB
But, "**_deselectEdge_**" event is **not triggered** for edge1

**Comment by Tooa** [comment]
I think this is expected behavior. Take a look at this example [here](http://jsbin.com/qojunijiyu/1/edit?html,console,output). Once you click on one of the nodes, the `selectNode` and `selectEdge` events are fired. When you then click on the edge it is still selected. Thus, no new `selectEdge` event is fired. 

The [documentation](http://visjs.org/docs/network/) states: 
> Fired when an edge has been selected by the user.

There is no second `selectEdge` event because the edge is already selected. This is also true for your second case. 

You can get your desired behaviour by suppling the following option value: `  var options = { interaction: {selectConnectedEdges: false}};`. This will disable the selection for adjacent edges when clicking on a node.
