### ISSUE TITLE
Feature Request: iOS scrolling feature

### ISSUE THREAD

**Issue by kuehn-sba** [almende/vis#1971]
is it planned to support the -webkit-overflow-scrolling: touch; css feature? which would improve timeline scrolling on iOS devices, because it uses hardware acceleration on that devices?

Scrolling is very slow inside browser of iPad, when there are more then 200 items in a window...

**Comment by mojoaxel** [comment]
Nice idea!
Sadly it's not that simple: The timeline is not just simply a large container that is scrolled vertically. in fact the "scrolling" is done fully manually by handling touch events. Because the timeline is in fact only as wide as the surrounding box the `webkit-overflow-scrolling` can not be used here.

The "scrolling" has to be done manually because the content changes very dynamically. For example the number of groups and the height can be different at certain positions. Also zooming could be a problem with native scrolling active.

I'm sure a timeline-component with better mobile support and even "momentum"-scrolling could be built, but the vis implementation seems to have a different focus.

**Comment by mojoaxel** [comment]
@kuehn-sba I think you can close this issue.

**Comment by awatson1978** [comment]
So, instead of implementing ` -webkit-overflow-scrolling: touch`, does anyone have ideas on how to implement momentum scrolling on mobile devices (specifically iOS)?  The library is already implementing touch events, and it's already got momentum scrolling.  I'd be willing to devote some cycles to this if anybody could give some thoughts on where to start.
