### ISSUE TITLE
[BUG?] background-image in item.style not working?

### ISSUE THREAD

**Issue by MisterDev** [almende/vis#2095]
Building a Timeline in my `Ionic1` app, I'm trying to dynamically set a `background-image` to my items using the `style` property.
This is my item object: 
![screen shot 2016-09-15 at 14 06 55](https://cloud.githubusercontent.com/assets/11232797/18549358/4557a5f2-7b4e-11e6-901b-fbc8c98f4467.png)

But when it is rendered the image is not displayed because `background-image` is set to `url('http')` 

![screen shot 2016-09-15 at 14 07 34](https://cloud.githubusercontent.com/assets/11232797/18549385/749a6ef8-7b4e-11e6-8c51-c156033c92e7.png)

**NOTE** None of these works
```
style: "background-image: url(' "+ p.imageURL +" ')"
style: 'background-image: url(" '+ p.imageURL +' ")'
style: "background-image: url(\" "+ p.imageURL +" \")'
style: "background-image: url('https://pbs.twimg.com/profile_images/378800000822867536/3f5a00acf72df93528b6bb7cd0a4fd0c.jpeg')"
```
                    

What is happening? Am I doing something wrong?

**Comment by brichbe** [comment]
When you specify that image URL in javascript those two forward slashes after "https" are being treated as a comment.

One workaround could be encoding that URL, but instead I'd recommend you specify your item background image using CSS, by using the `className` property instead of the `style` property.

Define the item with something like:
`className: 'bgimage'`

And in your CSS add something like:
`.vis-range.vis-item.bgimage {
background-image: url("https://www.google.com/images/nav_logo242_hr.png");
}`

**Comment by MisterDev** [comment]
Thanks for your reply.

I'm confused, the style property should be a string and afaik javascript doesn't treat `//` inside a string as a comment: 
![screen shot 2016-09-15 at 17 11 51](https://cloud.githubusercontent.com/assets/11232797/18555366/ead3b282-7b67-11e6-99a1-e8a351631d81.png)

so this  should be treated as a string
```
style: "background-image: url('https://pbs.twimg.com/profile_images/378800000822867536/3f5a00acf72df93528b6bb7cd0a4fd0c.jpeg')"
```

Or am I just misunderstanding what you mean?

I can't use a CSS class since every item should have a different `background-image` . 
I've solved using templates, but I'm still interested in figuring out what is happening here :)

**Comment by brichbe** [comment]
Yes a var String with forward slashes isn't a problem, but I just meant it seems that forward slashes within the style property String value are strangely being treated as a comment, so it's still worth investigating if this is an unexpected side effect with something VisJs is doing.

Regardless, since you've found your solution using templates it's probably best to close this ticket for now, but post more info later if you find another workaround.

**Comment by MisterDev** [comment]
Oh, I thought you meant to say that this is how it should work.

I opened this issue to figure out what's going on, not only to find a workaround. If this is not the expected behavior I think this issue should be kept open.

**Comment by mojoaxel** [comment]
@MisterDev Is this still an issue? If not can you please close this. Thanks!

**Comment by MisterDev** [comment]
Hi @mojoaxel, I haven't found why this happens and the repo has not been updated since I opened this, so I guess this strange behaviour is still here.

If you mean my issue, that's solved :)
