### ISSUE TITLE
Click event reports an error

### ISSUE THREAD

**Issue by tescott** [almende/vis#2102]
I created an event that fires when the user clicks on the graph2d object.  

Example:

```
   function onGraphChange ()
   {
      delayRenderUpdate = RENDER_STEP_SIZE*4;
   }
   graph2d.on('click',onGraphChange);
```

When it fires in the browser, I see the following error traceback:

> DataAxis.screenToValue    @   vis.js:26773
> Graph2d.getEventProperties    @   vis.js:25293
> (anonymous function)  @   vis.js:25090
> etc.

Digging into the code, this corresponds to:

```
  DataAxis.prototype.screenToValue = function (x) {
    return this.scale.screenToValue(x); // problem is on this line
  };
```

I just started using vis.js today, so I'm not sure what is intended here.

UPDATE: 
Just discovered this happens regardless of whether I have an event defined or not.  I deleted the event, reloaded (CTRL+F5) the view, and clicked on the graph2d.  Same problem.

**Comment by mojoaxel** [comment]
@tescott Can you please provide a simple example (e.g. on [jsbin](jsbin.com)) that shows when the problem occurs. Thx!

**Comment by tescott** [comment]
Sure thing!  Here's an example: [http://jsbin.com/qayajuzeza/1/edit?html,output](url)

I'm using Chrome.  I hit F12 to bring up the Dev Tools.  Click anywhere on the graph and you'll see the error appear in the Dev Tools console.

**Comment by tescott** [comment]
I'm wondering if this is due to no data being present.  If I have a Graph2d that has some data points, I don't get the error when I click on the graph.

**Comment by mojoaxel** [comment]
I can confirm this! http://jsbin.com/nizehoj/1/edit?html,output

**Comment by Tooa** [comment]
The problem is that `this.scale` is undefined. The value is initialized [here](https://github.com/almende/vis/blob/9703462783923ceb52107f0f3fe070de7cb0fe8f/lib/timeline/component/DataAxis.js#L56) and receives a value [here](https://github.com/almende/vis/blob/9703462783923ceb52107f0f3fe070de7cb0fe8f/lib/timeline/component/DataAxis.js#L366). 

> I'm wondering if this is due to no data being present. If I have a Graph2d that has some data points, I don't get the error when I click on the graph.

This means that the `_redrawLabels` is only called when some data is given. 

> Just discovered this happens regardless of whether I have an event defined or not. I deleted the event, reloaded (CTRL+F5) the view, and clicked on the graph2d. Same problem.

This is because `Graph2D` has an internal `click` event [here](https://github.com/almende/vis/blob/9703462783923ceb52107f0f3fe070de7cb0fe8f/lib/timeline/Graph2d.js#L104).
