### ISSUE TITLE
Make nodes link to url

### ISSUE THREAD

**Issue by TJRL** [almende/vis#2156]
I'm trying to make each node in my network link to a different url. I thought of either using an onclick event like the example here: http://visjs.org/examples/network/events/interactionEvents.html , or change the html of the node like the example here: http://visjs.org/examples/network/nodeStyles/HTMLInNodes.html . But both examples seem to complicated for what I want, nor do I completely understand how it works (javascript novice). I thought the most simple way to do this would be to put a css styled a tag in the shape of the node inside the node. However, I'm not sure if this will work.

**Comment by yotamberk** [comment]
Hey @TJRL,
There is no easy way to add a link in html canvas... 
http://stackoverflow.com/questions/6215841/create-links-in-html-canvas

I believe the best way is using an onclick event  as you suggested.

**Comment by dragonzone** [comment]
Vis.js network has a built-in event called, 'selectNode', where when node(s) are selected, it will pass in the all the nodes & edges (to & from the selected nodes), etc. that was clicked on. (Rather than the onClick event that will be fired if a node is selected or not). You then can get the selected node's ID & get it's properties back, such as URL & then redirect them to it.

Here is an example of how to do it: https://jsfiddle.net/qpd63j7r/

But if you want advance manipulation of the vis.js, you should start ramping up your JavaScript skills b/c you will need it. Hope this helps!

**Comment by dragonzone** [comment]
You can go here to get the full list of events: http://visjs.org/docs/network/#Events

**Comment by TJRL** [comment]
That helps a lot! Thanks dragonzone!

**Comment by bor8** [comment]
Use "click" instead of "selectNode", otherwise nothing happens, when a node is already selected.

Does Unicode now have a real symbol for an external link symbol like in Wikipedia? This one sucks: http://www.fileformat.info/info/unicode/char/1f517/index.htm (\uD83D\uDD17)

**Comment by ootoovak** [comment]
@bor8 I was finding the same thing but then but it was because I had
```
options = { interaction: { selectable: false } }
```
at first. If you change `selectable` to true then @dragonzone's solution works by listening to the `'selectNode'` event. I found listening to the `'click'` event worked in terms of capturing the event but it didn't have any nodes listed in the event params.
