### ISSUE TITLE
Get edge's label from editEdge event

### ISSUE THREAD

**Issue by sawatsky** [almende/vis#2233]
We should be able to get the `label` information for edges in the `editEdge` event.

Currently, we can get `label` information for nodes from `editNode`, so it makes sense to be able to get the label from `editEdge` as well.

This will require adding another event - or adjusting the current events -  for editing edges, so that users aren't required to arbitrarily move an edge's link to trigger the `editEdge` event. Users should be able to edit an edge's label without any other adjustments.

For current workarounds: #2068

**Comment by mojoaxel** [comment]
@eymiha are you sure this is fixed with #2329 ?

**Comment by eymiha** [comment]
In `examples/network/other/manipulationEditEdgeNoDrag.html` you can see that now, when editing a labeled edge, the current value is being pulled from the passed data. Unless I really mucked something up it should be working because the label data is loaded in the `ManipulationSystem#performEditEdge` function.

**Comment by mojoaxel** [comment]
@eymiha Yes looks good.
@sawatsky Feel free to reopen if this is still an issue.
