### ISSUE TITLE
get Zoom Level 

### ISSUE THREAD

**Issue by pliablepixels** [almende/vis#2278]
Hi there, I noticed some useful functions, [zoomIn and zoomOut added](https://github.com/almende/vis/issues/1955) in 4.17 - thanks they are useful.

Is it possible to get the current zoom level? I need to store it in a DB so I can go back to that zoom level when the app restarts (the data may change, but the zoom level needs to be retained in my app). Thanks

**Comment by yotamberk** [comment]
You can get the start and end time and לstore them

בתאריך 7 בנוב׳ 2016 10:29 אחה״צ,‏ "Pliable Pixels" <notifications@github.com>
כתב:

Hi there, I noticed some useful functions, zoomIn and zoomOut added
<https://github.com/almende/vis/issues/1955> in 4.17 - thanks they are
useful.

Is it possible to get the current zoom level? I need to store it in a DB so
I can go back to that zoom level when the app restarts (the data may
change, but the zoom level needs to be retained in my app). Thanks

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/almende/vis/issues/2278>, or mute the thread

**Comment by yotamberk** [comment]
You can save the start and end times. Wont that have the same effect?

**Comment by pliablepixels** [comment]
I think that would only work if the data set range is the same.
Here is what I mean:

I've set my graph options with a specific zoomMin (say granularity of 1 month) and a zoomMax (say granularity of 1 minute)

Now, if a person always wants to view his timeline at the granularity of 10 minutes, he will zoom in till he sees 10 minutes gaps. Now, even if he changes the date from/to he wants to always view at 10 minutes zoom level.

**Comment by yotamberk** [comment]
So you can save the end and start difference and you get the soon level

**Comment by pliablepixels** [comment]
Sorry if I'm sounding daft (likely because I am) but here is what I am doing:

```
timeline.on('rangechanged', function(s) {
         console.log ("Range Changed:"+JSON.stringify(s));
 });
```

Here is the graph:
<img width="697" alt="screen shot 2016-11-07 at 8 10 40 pm" src="https://cloud.githubusercontent.com/assets/4116654/20082792/8610e796-a526-11e6-811d-65f145d94fae.png">

And here is the callback console.log

<img width="764" alt="screen shot 2016-11-07 at 8 10 54 pm" src="https://cloud.githubusercontent.com/assets/4116654/20082798/92320d98-a526-11e6-8e14-b674293c85c2.png">

The start and end don't seem to correspond at all to the graph?

**Comment by pliablepixels** [comment]
Okay, so it looks like the object passed to this callback is something else, not the visible window.
Changing it to this gives the correct displayed range:
```
 timeline.on('rangechanged', function(s)
 {
                                ///console.log ("Range Changed:"+JSON.stringify(s))
                                var w = timeline.getWindow();
                                console.log ("start:"+w.start+" end:"+w.end);
});
```
This produces:
<img width="604" alt="screen shot 2016-11-07 at 8 18 10 pm" src="https://cloud.githubusercontent.com/assets/4116654/20082917/5502617e-a527-11e6-911c-2b5bbc3355d6.png">

**Comment by yotamberk** [comment]
I'm sorry but i really dont understand why you need the zoom. If you have the start and end date, you can save them and when you refresh, set the timeline to these times. Or, calculate the difference and set the start to whatever you want and the end date to the start time + the difference calculated before. No need for calling zoomIn

**Comment by pliablepixels** [comment]
argh. Indeed - you are absolutely correct. Classic case of [XY](http://mywiki.wooledge.org/XyProblem) problem solving.

**Comment by avrahamcool** [comment]
you can get the current zoom level (scale and step) from the timeline instance.
`timeline.timeAxis.step.scale`
`timeline.timeAxis.step.step`

**Comment by ZaidRehman** [comment]
Hey,
I need this zoom level in my use case because start and end time will not work for me.

I have a slider which shows the zoom level of the timeline chart.
updated slider updates the zoom of timeline (by zoomIn and zoomOut functions)
Now I want to update the slider when user changes the zoom by scrolling.

Is there any way by which I can track the zoom levels changed by user?
