### ISSUE TITLE
SVG mouseover does not work?

### ISSUE THREAD

**Issue by TJRL** [almende/vis#2322]
I've tried to implement SVG nodes with mouseover effects, but they don't work whatever method I used (I tried most methods discussed here: http://www.petercollingridge.co.uk/data-visualisation/mouseover-effects-svgs). Is this a bug? Is there a way I can make it work by changing something in the source code?

The fiddle shows an svg with a mouseover effect, one embedded in the network, and one in the page body:

https://jsfiddle.net/Thymus82/t2cq8rna/

**Comment by DoubleTK** [comment]
Hi @TJRL ,
I'm not sure if it's a bug or not, but there is a simple workaround that might work for you. I haven't looked at the source code, but I'm guessing the 'color' attribute of the node is not setting the 'fill' attribute of the svg image and that's why it's not working.

For the workaround, are you able to create a second 'highlighted' svg of the 114 image? If you can do that, you can simply swap out the image url and call 'update' on the dataset.

JSFiddle example: https://jsfiddle.net/t2cq8rna/8/

Notice, after you create the network, add two 'on' events, one for 'hoverNode' and one for 'blurNode'. When those events fire, check the node Id, grab the node from the dataset, update the image url, and then call update on the dataset, passing the node back as an argument, like so:

```
	var network = new vis.Network(container, data, options);
  network.on('hoverNode', function(node){
  	if(node.node === 2){
      let node = nodes.get(2);
    	node.image = 'http://s.cdpn.io/3/kiwi.svg';
      nodes.update(node);
    }
  });
  
  network.on('blurNode', function(node){
  	if(node.node === 2){
    	let node = nodes.get(2);
    	node.image = 'http://mov114.com/media/114.svg';
      nodes.update(node);
    }
  });
```

Let me know if that will work. It may be a good idea to eventually add the ability to fill the image using the hover feature of the node, but I'm not sure that would work in each case.

DoubleTK

**Comment by TJRL** [comment]
Thanks @DoubleTK! I was already on this track, but hadn't figured out how exactly to correctly use hoverNode and blurNode in the code. Super!
