### ISSUE TITLE
doubleClick Events it not fired.

### ISSUE THREAD

**Issue by yubitib** [almende/vis#2421]
when "clickToUse" is true once i clicked item i could use click event again i click the same item i could not use click event it not fired.

**Comment by Tooa** [comment]
It works for me with [this](http://jsbin.com/xadoyuhugo/edit?html,console,output) minimal example. I need to click on the timeline once since the option `clickToUse` is activated. Then the timeline is marked with a blue border. Then I click on `item 2` and the the `click` event is fired. A second click on the same element i.e. `item 2` issues another `click` event.

**Comment by yubitib** [comment]
I've confined the option like [this](http://jsbin.com/yuduceziza/edit?html,console,output), not it's not working please check also scroll is not working on the background

**Comment by yotamberk** [comment]
@yubitib Scrolling has been solved in the `develop` branch. In terms of the double click, I'll check it out.

**Comment by yubitib** [comment]
OK Thanks, i need to fix the scroll in your master branch,
may you please help to it?

**Comment by Tooa** [comment]
You can [cherry pick ](https://git-scm.com/docs/git-cherry-pick)the [commit](https://github.com/almende/vis/commit/5f7a721bf9728dd1ac8390b6835c00bb779df251) from the develop branch.

**Comment by yubitib** [comment]
but i used bower for install libraries in my production

**Comment by Tooa** [comment]
For the time being, you can build the develop branch yourself and include your own build in your production env. Otherwise, you have to wait for the next visjs release. However, this shouldn't take too long.

**Comment by yotamberk** [comment]
Fixed in #2473

**Comment by mojoaxel** [comment]
@yotamberk fixed this with #2473
