### ISSUE TITLE
Almende Timeline: Highlighting weekends with different colors

### ISSUE THREAD

**Issue by tejashree2012** [almende/vis#2564]
I want to highlight weekends and non business hours in different background color on timeline.
Can I do this?
For eg: Saturday and Sundays  and non business hours will be shown in grey color and rest of the days in white. Even after zoom in, grey color should be displayed on that particular day.

Kindly let me whether we can achieve this in timeline?

**Comment by lewisjb** [comment]
You'll want to look at http://visjs.org/docs/timeline/#Styles
The example there even has the greyed weekends. I'll leave it as an exersize for the reader on how to do it for non-business hours

**Comment by tejashree2012** [comment]
I tried to implement greyed weekends. However when timeline is zoomed in to hourly basis, grey color of weekends disappear. Can we achieve this. Even after Zoom in or zoom out, grey color should be displayed on that particular day.

**Comment by yotamberk** [comment]
@tejashree2012 Can you supply a jsbin? It will be easiest to look at with an example

**Comment by mojoaxel** [comment]
I remember fixing the CSS tags month ago. This should be doable overwriting the correct class-tag for weekends, but I have to check again for details.

**Comment by yotamberk** [comment]
@mojoaxel can you check this again please?

**Comment by mojoaxel** [comment]
@tejashree2012 Please have a look at the [gridStyling example](http://visjs.org/examples/timeline/styling/gridStyling.html). There the weekend (Saturday and Sunday) are marked dark-gray.
At the moment this marks disappear if you zoom in, so that the hours of the day are displayed. Also the css-class-tags disappear if you scroll out so much than 2 days get grouped together.

You can set a min and max to prevent the user from zooming out of this range.

**Comment by Anja-R** [comment]
Hi

Is there a way to get the weekend colored even if you show the hours of the day?

I have this css
```	
        .vis-time-axis .vis-grid.vis-saturday,
	.vis-time-axis .vis-grid.vis-sunday {
		background: #F0F0F0;	
	  }
	  
	.vis-time-axis .vis-grid.vis-today {
		background: #FFFFCC;	
	  }
```
The "today" is working when hours is shown, but not the weekend, but I don't really see any difference in the css

![billede](https://user-images.githubusercontent.com/36192901/38295548-9fa204ea-37ee-11e8-8a54-5c82db412aa6.png)

**Comment by brichbe** [comment]
@Anja-R  Your CSS is correct. The problem is what mojoaxel alluded to earlier -- the CSS class-tags change when you're zoomed in to an hourly view. When zoomed out to a day-to-day view, the vis-saturday and vis-sunday class-tags are present so your CSS will work to change the background of the weekends; however, those tags are no longer present when zoomed further in. Unfortunately, there's no clear, existing workaround for this.
