### ISSUE TITLE
How to centre major labels in timeline?

### ISSUE THREAD

**Issue by bvisick** [almende/vis#2663]
I want to centre the text for the major labels in a timeline and leave the minor labels left-aligned. I've tried:
```
.vis-time-axis .vis-text {
      text-align: center;
}
```
which centres the minor labels and leaves the major labels left-aligned, the opposite of what I want. Is there a way of doing this? Thanks.

**Comment by yotamberk** [comment]
Centered compared to what? They are programmed to be visible as much as possible so this is not possible with only css.

**Comment by mojoaxel** [comment]
It is not possible to change the alignment of the major-labels at the moment, because they don't have a defined `width`. 
For the minor-labels a center-alignment is no problem, because thay have a width [TimeAxis.js#L262](https://github.com/almende/vis/blob/master/lib/timeline/component/TimeAxis.js#L262).

**Comment by yotamberk** [comment]
The only workaround I could think of is to add a `margin-left' to the label-major but It won't promise it to be always in the center. If you want this as a feature request, please open a new issue with the feature explained.
