### ISSUE TITLE
[Timeline] Bug ordering nested groups

### ISSUE THREAD

**Issue by gerardp** [almende/vis#2676]
Hi,
Nested groups are not sorted when the parent has 'showNested: false'.

**Comment by mojoaxel** [comment]
@gerardp Can you please provide a simple [jsbin](http://jsbin.com/?html,output), to demonstrate the bug.

**Comment by gerardp** [comment]
(I am not sure that the bug comes from the property "show Nested: false".)
http://jsbin.com/relegoheze/edit?html,output

The order should be:
clean house
cook
shop

But in the example the output is:
clean house
shop
cook

**Comment by gerardp** [comment]
@mojoaxel Any idea on this bug and how to fix it?

**Comment by brichbe** [comment]
This does appear to be a bug where the `groupOrder` is not applied to the nested groups (or a feature request for creating a new `nestedGroupOrder` timeline configuration option...).

@gerardp until this is fixed, I believe you'd have to work around this with the understanding that the groups are ordered in the DataSet by their 'id' value, so that's the order the _nested_ groups are getting displayed.  For example, change the "shop" `id` from `122` to `142` in both places and you'll get the desired order.

**Comment by yotamberk** [comment]
@gerardp Thanks for reporting. In the meantime, @brichbe 's suggestion is a great workaround

**Comment by mojoaxel** [comment]
Is this fixes with #2810 ?

**Comment by yotamberk** [comment]
solved in 4.20.0
