### ISSUE TITLE
Missing way to interact with tooltips in Timeline module

### ISSUE THREAD

**Issue by netbrothers-tr** [almende/vis#2682]
What I want to achieve is to enable the user to interact with the (built-in) tooltip, e.g. to click on a link in the tooltip's html. Maybe I just don't see how this works. Thanks for your suggestions and replies everyone!

**Comment by yotamberk** [comment]
Hi @netbrothers-tr , the timeline has a builtin tooltip that only appears on hover. You can't interact with it because it will disappear if you try to move your mouse on it. 

The best bet is to use an external tooltip that will appear onclick of the item. 
 OR
this could be a feature request to implement a tooltip that will stay static when hovering on it. 

For the meantime, I would go for the first suggestion.

Does this help @netbrothers-tr ?

**Comment by netbrothers-tr** [comment]
Hi @yotamberk , thank you for the clarification! It helped. I will, for now, try to include an external library but I think it makes a lot of sense to built this functionality directly into vis. 😃

**Comment by brichbe** [comment]
I disagree with this becoming a feature request to be built into vis.

As @yotamberk explained, you're not talking about a tooltip, you're talking about a _popup_ that allows the user to click on a link, which are different things.  Popups are easily implemented by handling the timeline click|doubleClick|contextmenu event you want, and then using a 3rd party lib to display the popup you need, so this is not something that should be a concern of a lib like vis that's focused on data graphing/visualization.  

Plus, the popup's behavior is application-specific, so it could be cumbersome for vis to implement something that handles everyone's needs (e.g. when should the popup close? after some time delay, after a link is clicked, or after a close button is clicked?)  Better to implement this yourself, in a way that suits your application, like many other users of vis have already done.

**Comment by netbrothers-tr** [comment]
@brichbe you convinced me.
