### ISSUE TITLE
Feature request: Graph3D Tooltip Styling

### ISSUE THREAD

**Issue by p-a** [almende/vis#2769]
Currently the style and layout of tooltips are hard coded, and only the inner HTML can be customised.
It would be nice if there was support for some means of styling tooltips, including its line and point.

**Comment by Tooa** [comment]
Thanks for your feature request. It's unlikely that someone in our team will pick this up in near future since no one really works with the `graph3D` module in our team. However, we are open for pull requests. In case you are interested, check out the `develop` branch and send us a pull request. That would be really nice.

**Comment by p-a** [comment]
Created a PR for this issue. Added info to docs and provided a basic example on how to use the new feature.
