### ISSUE TITLE
Cannot unsubscribe from DataSet

### ISSUE THREAD

**Issue by alunperkins** [almende/vis#2811]
Illustration:
https://jsfiddle.net/9dfzmpbh/10/

I subscribe to events with DataSet.on(...).
If the syntax used for the callback is either "(args) => {commands}" or "function (args) { commands; } " then that subscription cannot be unsubscribed from.
If the callback syntax is just a function name, then that works, and can be unsubscribed from, but this has other problems for me regarding variable scope in my typescript project.

I compare this to the way subscriptions work for Graph2d, and find that Graph2d works as expected, and intregrates well with my typescript project. This behaviour is specific to DataSet.

**Comment by ZacBrownBand** [comment]
I may be off here, but it looks to me like this is an issue of references. Hope this helps.

You are doing:
```js
dataset.on('add', function(e) { console.log(e);});
dataset.off('add', function(e) {console.log(e)});
```
This will not work because the functions are not the same thing.
```js
var a =  function(e) {console.log(e)};
var b =  function(e) {console.log(e)};
(a == b) // false
```

This does not work because when off is called it looks for a callback handler that is the same as what you passed in.

This can be fixed pretty easily by using the same function reference for both calls.

```js
var add = function(e) {
  console.log(e);
}

dataset.on('add' add);
dataset.off('add', add);
```


Also note, that if you are using bind, the bind must be done to the common reference.

Good
```js
var add = function(e) {
  console.log(e);
}.bind(this)

dataset.on('add' add);
dataset.off('add', add);
```

Bad
```js
var add = function(e) {
  console.log(e);
}
dataset.on('add' add.bind(this))
dataset.off('add', add.bind(this));
```

**Comment by alunperkins** [comment]
Thank you. 
I was mistaken - I thought your first example worked for other classes (e.g. Graph2d), but I checked and found that it does not (however Graph2d has the helpful .off('click') syntax). So DataSet works as expected, but simply lacks a helper syntax.
I did not know about 'bind'! It does indeed solve my problem. Thanks very much!

**Comment by ZacBrownBand** [comment]
Great, glad to help. I have had that issue in the past!
