### ISSUE TITLE
vis-group height is not fixed when two items are placed next to each other

### ISSUE THREAD

**Issue by MAHESHGONDA** [almende/vis#2816]
hi ,
 i am not getting why height of groups is not uniform ? did i missed anything ?
example which i am trying is below  , please let me how can i make height of groups uniform 

http://jsfiddle.net/Ltsf0Lb7/85/

**Comment by brichbe** [comment]
I think that's the standard behavior when the timeline height is static and is larger than the group/item contents being displayed -- in that case (like your example) one of the groups is drawn "taller" than it should be so that it fills the empty space.

If you remove the timeline height setting of 90% from your example, you see the timeline height becomes dynamic so that all groups are the same height (until/unless items come into the view).  Otherwise you can try changing the group CSS to specify minimum group heights so they're more consistent when the timeline height is static.

**Comment by brichbe** [comment]
Also, re: min-height, see the suggestion in #2711

**Comment by MAHESHGONDA** [comment]
i added 
.vis-inner {
min-height: 200px;
}
also i removed height setting of 90%, still i have same issue , still items are not aligned one after another 
But when i added below css then all items are aligned one after another 

      .vis-item.vis-range{
        top:46px !important;
      }

modified jsfiddle 
http://jsfiddle.net/Ltsf0Lb7/96/

**Comment by brichbe** [comment]
@MAHESHGONDA  It's unclear if you still have a question/issue?  If not, please close this ticket.
