### ISSUE TITLE
[Graph2d] "Cannot read property 'x' of undefined" when changing items via "graph2d.setItems"

### ISSUE THREAD

**Issue by cridus** [almende/vis#2818]
I have a page in which the user needs to be able to switch to different data via a `<select>`. When initializing the graph with the first set of data there's no error, but once you switch to another set via "graph2d.setItems" this exception is thrown:

    Uncaught TypeError: Cannot read property 'x' of undefined  
      at vis.js:31221  
      at Object.e.insertSort (vis.js:1348)  
      at n.setItems (vis.js:31220)  
      at n._updateAllGroupData (vis.js:29810)  
      at n._onUpdate (vis.js:29627)  
      at n._onRemove (vis.js:29633)  
      at n.setItems (vis.js:29566)  
      at n.setItems (vis.js:29124)  
      at HTMLSelectElement.<anonymous> (VM157:112) <- "graph2d.setItems" when the <select>'s value changes

Here's a JSFiddle that reproduces the issue: https://jsfiddle.net/ntaxc1f5/2/

Previously I was using version 4.15.1 of vis.js and this worked no problem. I updated to 4.18.1 because I had [this issue](https://github.com/almende/vis/issues/450) and I hoped it would be fixed in the latest version, at least for my situation.

**Comment by Tooa** [comment]
I can confirm this issue. The problem is that [here](https://github.com/almende/vis/blob/bc2bc581aaa16905f2ee15b26d3915648c34cc54/lib/timeline/component/LineGraph.js#L523) the passed variable `groupsContent` is empty. It looks like this check [here](https://github.com/almende/vis/blob/bc2bc581aaa16905f2ee15b26d3915648c34cc54/lib/timeline/component/LineGraph.js#L481)  prevents that there is any data written to the array. I haven't figured out the semantic of the check yet.

**Comment by lazychaser** [comment]
Same issue, works fine in v17.0, but there are other issues in this version

**Comment by blin4444** [comment]
This issue seems to happen when calling setItems, with items of the same group as items already in the graph. This functionality last worked in version 4.17.0.

Here is a simple example to demonstrate the problem:

```
<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/vis/4.19.1/vis.min.css" />

        <!-- Switch to 4.17.0 and the graph shows a horizontal line, as expected -->
        <script src="https://cdnjs.cloudflare.com/ajax/libs/vis/4.19.1/vis.min.js"></script>
        
        <script>
            function initVis() {
                var container = document.getElementById('graph')

                items = [
                    {x: 0, y: 1, group: 1},
                    {x: 1, y: 2, group: 1},
                    {x: 2, y: 3, group: 1},
                ]
                
                graph2d = new vis.Graph2d(container, items);

                // The following call fails.
                graph2d.setItems([
                    {x: 0, y: 4, group: 1},
                    {x: 1, y: 4, group: 1},
                    {x: 2, y: 4, group: 1}
                ])
            }

            document.addEventListener("DOMContentLoaded", initVis);
        </script>
    </head>
    <body>
        <div id="graph">
        </div>
    </body>
</html>

```
http://jsbin.com/komopagifo/1/edit?html,output

On 4.19.1, an error occurs on the setItems call.
Switch to 4.17.0 and the graph shows a horizontal line, as expected.
Reverting LineGraph.prototype._updateAllGroupData to the version in 4.17.0 resolves the issue.

@yotamberk @mojoaxel @ludost  Related to earlier issue #2594.

**Comment by AngeloYoun** [comment]
The offending commit seems to be 876e0ab83e3d378aefa3005a49d0641e3f60f6ca,
specifically
```
 if (!groupIds && ids) {
       for (var groupId in this.groups) {
         if (this.groups.hasOwnProperty(groupId)) {
           var group = this.groups[groupId];
           var existing_items = group.getItems();
 
           groupsContent[groupId] = existing_items.filter(function (item) {
             return (item[fieldId] !== idMap[item[fieldId]]);
           });
           var newLength = groupCounts[groupId];
           groupCounts[groupId] -= groupsContent[groupId].length;
           if (groupsContent[groupId].length < newLength) {
             groupsContent[groupId][newLength - 1] = {};
           }
         }
       }
     }
```

**Comment by avrahamcool** [comment]
I'm using 4.21.0 and the issue is still here.
(i'm clearing the items DataSet, and setting new data without changing the groups)

was it published? or is it still awaiting release?
