### ISSUE TITLE
Tooltip doesn't hides with scrolling

### ISSUE THREAD

**Issue by nickmeewis** [almende/vis#2820]
With the vis Timeline add a title to multiple items.

`{
                id: 1,
                content: 'item 1',
                group: 'test1',
                start: '2017-02-28T00:00:00+01:00',
                end: '2017-03-01T00:00:00+01:00',
                title: 'test 1'
            },
            {
                id: 2,
                content: 'item 2',
                group: 'test1',
                start: '2017-03-01T00:00:00+01:00',
                end: '2017-03-05T04:30:00+01:00',
                title: 'test 2'
            },`

Set options
`horizontalScroll: true,
            zoomKey: 'ctrlKey',
            verticalScroll: true`

When you hover over an item the tooltip appears, than scroll without moving your mouse until you reach an other item. A new tooltip appears and the other one doesn't hide.

It looks like the scroll event doesn't check the mouse over state.
But not sure how that part works.

**Comment by bradh** [comment]
Is this browser independent? Can you set up a jsbin that shows the problem?

**Comment by nickmeewis** [comment]
I created a small jsbin.

http://jsbin.com/radipoketo/1

Hold your mouse on the first item ("item1") and use you scroll wheel to hover over the second item ("item2"), then scroll until you leave the second item. If you move your mouse the tooltip won't hide.

"*notice don't move your mouse until you left the last item"

**Comment by lewisjb** [comment]
Good spotting!

This has been partly fixed in the develop branch due to #2662.
I believe the only aspect that was fixed was the tool-tip never disappearing. But not the tool-tip not switching when you scroll (ie when your scrolling it will say "item 1" over item 2, or still having the tooltip when you aren't over anything), this is due to no mouse event being triggered from scrolling.

In release 4.19 it should only allow 1 tool-tip to be open at once, so when you have that tool-tip that doesn't disappear, if you hover over another item, it will go away.
