### ISSUE TITLE
Secondary Events for an Item

### ISSUE THREAD

**Issue by Kaliph** [almende/vis#2824]
![featute_secondary](https://cloud.githubusercontent.com/assets/19877914/23567690/cad74ca8-0057-11e7-9e65-c7c5f6c27b75.png)

Hey there I would love to see the timeline improve with the possibility to show secondary Events. 
The idea came to my mind when I saw your progress bar approach.
I made a screenshot of what I would like to be able to do with the vis timeline in future.

A method to hide and display the secondaries would be also a nice addition.

I would appreciate if this will make it to a feature request. Thanks for the great job. The Timeline is already great!

**Comment by brichbe** [comment]
You should try implementing this with existing functionality, since it seems quite possible to do with the current features of items, groups and subgroups, and by using custom styling such as zero margins so these "related" items appear as one.  Otherwise you may be waiting weeks/months/years for this to be implemented because this could be complicated to implement and few, if any, current users of Vis will find this new feature relevant for their app.

**Comment by Kaliph** [comment]
You are right. I would do, if my knowledge would be big enough. I am a beginner to JavaScript. Some help with where to Look at would be appreciated. Thankyou

**Comment by brichbe** [comment]
You learn by studying, and you get better by doing.  There is a lot of [documentation ](http://visjs.org/docs/timeline/) for you to read and [examples ](http://visjs.org/timeline_examples.html) for you to study.  Spend more time learning those things and learning more Javascript/CSS/etc. until you're more comfortable.  Then try creating an example on jsbin/jsfiddle.  Ask for help if you've gotten stuck with something, but only after you've tried some things yourself.  Please close this ticket and use http://stackoverflow.com/ for general questions in the future.

**Comment by Kaliph** [comment]
I will follow this idea under [http://stackoverflow.com/questions/42597276/vis-js-progress-bar-does-not-show-correct-value](url)
After I have figured out how the progress bar shows the sent value maybe with a animation if the value increases. not only showing a percentage value.
