### ISSUE TITLE
Can't render this network.  Renders as moving vertical line.

### ISSUE THREAD

**Issue by mullenba** [almende/vis#2845]
I'm attaching a tab indented JSON file with a list of nodes and edges.  All of the other networks I've created this way have worked fine, but this one renders as a zoomed out single vertical line.  When you try to zoom in to see the individual nodes, it actually starts moving up out of the screen!

[debug.txt](https://github.com/almende/vis/files/827446/debug.txt)

**Comment by Bastetoi** [comment]
Maybe it's not coming from the json :3
just sayin'

**Comment by mkomitee** [comment]
I have a similar sounding issue. I end up with what _looks_ like a single horizontal line but that could be due to my layout direction. I've attached a reproducer (renamed from html to txt because github doesn't support attaching files with an html extension).

If you zoom in a lot (which is hard, because it tries to scroll off the container) it looks like there's more detail.

[reproducer.txt](https://github.com/almende/vis/files/828829/reproducer.txt)

My actual application involves a graph of this _shape_, but I've removed all of the extraneous options which don't appear related to the issue at hand.

**Comment by mkomitee** [comment]
I don't know _why_, but it appears that if I negate my levels, from:

                 {"id": "a", "level":  6, "label": "a",},
                 {"id": "b", "level":  5, "label": "b",},
                 {"id": "c", "level":  4, "label": "c",},
                 {"id": "d", "level":  3, "label": "d",},
                 {"id": "e", "level":  3, "label": "e",},
                 {"id": "f", "level":  3, "label": "f",},
                 {"id": "g", "level":  2, "label": "g",},
                 {"id": "h", "level":  1, "label": "h",},
                 {"id": "i", "level":  0, "label": "i",},

to 

                 {"id": "a", "level":  -6, "label": "a",},
                 {"id": "b", "level":  -5, "label": "b",},
                 {"id": "c", "level":  -4, "label": "c",},
                 {"id": "d", "level":  -3, "label": "d",},
                 {"id": "e", "level":  -3, "label": "e",},
                 {"id": "f", "level":  -3, "label": "f",},
                 {"id": "g", "level":  -2, "label": "g",},
                 {"id": "h", "level":  -1, "label": "h",},
                 {"id": "i", "level":   0, "label": "i",},

And change my direction to DU, I get the graph I expect.

I'm tempted to do this, but the documentation doesn't have anything in it about the legal values for levels:

    When using the hierarchical layout, the level determines where the node is going to be positioned.

**Comment by mkomitee** [comment]
I have a functioning work around: I find my maximum level, and then subtract that from the levels I use to render, so in this case level 6 becomes 0 and level 0 becomes -6. Every graph I've tried to render with that change appears correct. 

Simply multiplying the level by -1 and then changing to DU won't work for me in production because I have some levels which are positive and some are negative. 

I suspect this is a bug.

**Comment by mullenba** [comment]
I played around with this some more and found that using negative levels didn't work in my case.  Instead, I came up with a way to reduce the number of edges connecting all of the nodes and that seemed to be renderable.  Maybe the bug has something to do with the number of edges between the nodes?

**Comment by mkomitee** [comment]
... and I now have data where my workaround no longer helps.

**Comment by mkomitee** [comment]
It looks like this data-set is causing issues for the physics engine. By increasing the options `physics.maxVelocity`, the graph can be made to converge much faster.

**Comment by wimrijnders** [comment]
@mullenba I tried the network data with `vis.js 4.19.1`, it renders fine. Perhaps there are specific options you used which create the issue.

**Comment by wimrijnders** [comment]
Duplicate #1735 .
