### ISSUE TITLE
Timeline IE issue: invalid start "NaN"

### ISSUE THREAD

**Issue by susemiessner** [almende/vis#2858]
I have an issue with IE (11) and displaying the timeline. My timeline is of type range and has a start and end date. They look like this
`type: range,
start: 2017-3-13,
end: 2017-3-18`
I get the following error:

> Invalid end 'NaN' in vis.js(19495,7)
any idea what's going on?

**Comment by susemiessner** [comment]
the problem is that in IE you need to pass the date as a 
`new Date(2017, 3, 13)`

**Comment by bradh** [comment]
You can also pass an ISOString format.

**Comment by jfuehner** [comment]
I'm having a similar issue when trying to wire into the timechange or timechange event handlers. I receive a Invalid start "NaN" error which appears to be being caused by adding a custom timebar...

Below is a sample of my code...
```

timeline.setOptions({
    height: '100%',
    editable: false,
    moveable: true,
    zoomable: true,
    configure: true,
    showCurrentTime: false,
    start: vis.moment.utc().format('YYYY-MM-DDT00:00:00.000Z',
    moment: function(date) {
      return vis.moment(date).utc();
     }
});

timeline.addCustomTime(vis.moment.utc().valueOf(), 'my-time-bar');
timeline.on('timechanged', function(props) {
     console.log('timechanged...');
});
```

If I comment out the timeline.on('timechanged') line I do not receive the error.
