### ISSUE TITLE
Question: [Network] Too many nodes -> circle node position

### ISSUE THREAD

**Issue by dmolnar99** [almende/vis#2868]
Hey,

I'm working on a network with svg images. I use the basic random layout, which works fine and displays all the nodes randomly. If I increase the number of the nodes, the nodes won't be positioned randomly in the container, but in a circle. Why is that?

Thanks.

Best regards,
David

![ok](https://cloud.githubusercontent.com/assets/16260193/24045426/5b2396aa-0b1f-11e7-96fd-ef7d8e821a4c.PNG)

![notok](https://cloud.githubusercontent.com/assets/16260193/24045432/6705ad00-0b1f-11e7-9e29-74a587ea7498.PNG)

**Comment by Tooa** [comment]
To which `visjs` version are you referring to? Can you show the example via [jsbin.com](jsbin.com)?

**Comment by wimrijnders** [comment]
I can actually explain this (to my own surprise).

In all likelihood, you have the following options set in your `options` structure:

```
layout: {
  improvedLayout: true
},

physics: {
  enabled: false
},
```

With `improvedLayout: true`, an initial layout algorithm kicks in (namely `Kamada Kawai`). This will only actually run if some conditions are met:

- Less than half of the nodes have the xy-coordinates pre-configured
- The network consists of clusters of nodes, each of which has <= 150 nodes

A 'cluster' is hereby a collection of nodes, which as a whole is connected to other clusters by at most a single edge. The network as a whole can be one single cluster.

If these conditions are met, the algorithm kicks in and positioning occurs. If not, the algorithm is skipped; because `physics` is disabled, there is no fallback for further positioning. In that case, you get the circle arrangement.

The telltale sign that `Kamada Kawai` can not run is the following output in the console:

> This network could not be positioned by this version of the improved layout algorithm. Please disable improvedLayout for better performance

**Comment by wimrijnders** [comment]
To get around this, set `physics.enabled:true`. I also recommend doing initial stabilization, because otherwise the network will be quite restless on-screen while iterating the coordinates.

And, while you're at it, you might as well disable `improvedLayout`, because that algorithm is not going to run anyway. Disabling it gives you a tiny performance improvement.

So, on the whole, the settings in `options` will look something like this:

```
layout: {
  randomSeed: 191006,    // Optional; insert your value here
  improvedLayout: false
},

physics: {
  enabled: true,
  stabilization: {
    iterations: 500      // Change this to whatever is convenient for you
  }
},

```

Hope this helps.

**Comment by wimrijnders** [comment]
@dmolnar99 Did this answer your question?

**Comment by dmolnar99** [comment]
@wimrijnders I use now fewer nodes, so I did not check your solution yet.

**Comment by wimrijnders** [comment]
@dmolnar99 Is the issue still relevant then? If not, please close it.

**Comment by wimrijnders** [comment]
Thanks!
