### ISSUE TITLE
No custom time bar found with id 'xxxxxxxx'

### ISSUE THREAD

**Issue by ilaipi** [almende/vis#2899]
Hello, I use vis with react and I need to add customTime in the render method.
So I will call `getCustomTime` with the same id everytime I update my state.

obviously I met the error: `A custom time with id "58d4e9f1b0797277cbfb0d78" already exists`

so I thought I need to use `getCustomTime` method to see if one id is already exists.

and then I met this error.

why not return undefined instead of throw a error?

or any idea about my case?

thanks!

**Comment by ilaipi** [comment]
now my render method is:
```javascript
render() {
    const { timeline } = this.state;
    if (timeline) {
      timeline.setItems(this.props.items);
      if (this.props.customTimes) {
        this.props.customTimes.forEach((customTime) => {
          // if (timeline.getCustomTime(customTime.id)) return;
          try {
            timeline.addCustomTime(customTime.time, customTime.id);
          } catch (err) {
            console.log(`======customTime id ${customTime.id} add to timeline======`);
          }
        });
      }
    }
    return (
      <div ref={(timelineContainer) => { this.timelineContainer = timelineContainer }} />
    )
  }
```

**Comment by yotamberk** [comment]
@ilaipi can you please supply a jsbin?

**Comment by ilaipi** [comment]
@yotamberk hello, [here](https://jsbin.com/wodose/edit?js,output) is the jsbin.

you can uncomment these two lines to get the error
```javascript
// var customTime = timeline.getCustomTime(id);
// timeline.removeCustomTime(id);
```

**Comment by bradh** [comment]
@ilaipi What did you expect to happen in that jsbin? The first time through, the id clearly doesn't exist because it hasn't been created yet.

**Comment by ilaipi** [comment]
@bradh yes, if a id hasn't been created, I hope to get a undefined not a error.

**Comment by jgorene** [comment]
Hello everyone ;)
On this question, I was wondering how to use the ".get Custom Time (id)" method ?
In any case, I don't see its usefulness as it currently stands.
Personally, I do not use it, although I often use the "customTime" in apps...

**Comment by ilaipi** [comment]
@jgorene hello, as I had said at the first comment, when I try to addCustomTime, it is a little  difficult to know whether I had added it. so I need to `getCustomTime` first to check if it is undefined.

the items can simply add by `setItems`.

**Comment by jgorene** [comment]
@ilaipi, Yes I think I understood your approach to using this "getCustomTIme" method ;)
I was just trying to broaden this thread to the actual use of this method.
Just a suggestion...
For me, it would be more interesting to use this method to find an array of existants "customTIme" objects in a timeline (e.g) and not, to find a "customTime" from itsalready known  id.
timeline.getCustomTIme() would do > [{customTime}, {customTime}, ...]
Otherwise, when creating a new CustomTime, I use its date (string) as ID for limit potential duplicate like an id "undefined" (e.g)
Hoping that It's quite clear...

**Comment by ilaipi** [comment]
@jgorene thanks. actually I don't understand `timeline.getCustomTIme() would do > [{customTime}, {customTime}, ...]`, `timeline.getCustomTime()` must have a id param. 

I would like to get an array by `getCustomTimes()` or by `getCustomTime()` without a special id.

I have an object called `Action`, each instance `action` should render a custom time, and that custom time must have the same id with the action.

**Comment by jgorene** [comment]
@ilaipi Ok but at this step, it becomes quite complicated for me to explain :S
First, because I speak wrongly English (as you have seen;) and vis.js is so awesome (almost magic) that the possibilities of use are really multiple and varied ... and very attractive to use !

Otherwise to be clearer but whithout it meets your question, sorry...
I use customTime as a landmark combined with "moveTo" to target a date on a certain period (e.g) ... in fact, I can have several customTimes present on a timeline.
Finally, it might be interesting to be able to catch all ones existing with a method like getCustomTImes () indeed in this case...
But I will try to prepare a JSBin to show it in these days soon ;)

**Comment by jgorene** [comment]
Hello,
Here an [example](https://output.jsbin.com/befada) for a prototype still in testing and outside its context ... code is still dirty but that was building with many care despite everything and works rather fine... for now (any suggestions welcome ;)
So, in any case, that illustrates my remarks on this thread
"Focus on weed" uses customTime with moveTo ...
This practical is convenient for us, although may not be the "intended use" ;)
