### ISSUE TITLE
Enable a rollingMode for custom time.

### ISSUE THREAD

**Issue by alexsandro-xpt** [almende/vis#2929]
I sugget a new feature for Timeline something like `.setRollingModeTo(sometime)` to fix mouse wheel zoom over specific time.

Today it work only for current time by `rollingMode: true` at options Configuration. The method `.toggleRollingMode()` move is fixed for currentTime only and I guess becouse it is set here https://github.com/almende/vis/blob/master/lib/timeline/Range.js#L135 changing `new Date()` for a specific time may be will work fine.

Some tip about that?

**Comment by yotamberk** [comment]
I'm sorry but I don't understand this feature request. You want to focus on a time offset from the current time? If so, this has been added here #2950

**Comment by alexsandro-xpt** [comment]
I want to focus on a custom time, not a current time(`new Date()`).

**Comment by Smileydude** [comment]
it wouldn't be rolling since the custom time doesn't move. Really you want to set the mouse position on a zoom to equal a certain time?

**Comment by alexsandro-xpt** [comment]
@Smileydude  Not only exactly set mouse position, I want fix mouse position at custom time when mouse wheel event occur.

**Comment by cipri-tom** [comment]
This would be a very nice feature ! Basically, the timeline is always centered on a custom time `t0` and zooming keeps this centered, regardless of where the mouse is actually positioned.

I would add the option to also "pan" the custom time i.e. the vertical bar stays in the middle of the timeline and as the timeline pans left/right the time of `t0` changes. In other words, instead of moving the bar `t0`, move the timeline and update `t0`

**Comment by yotamberk** [comment]
This can be done now using `rollingMode.offset` option
