### ISSUE TITLE
navigation doesn-t appear on Firefox

### ISSUE THREAD

**Issue by scenaristeur** [almende/vis#2946]
Hi, 
I use vis for a project based on [Polymer](https://github.com/Polymer/polymer) .
Demo here : http://smag-cece4.firebaseapp.com/?search=David

i added the navigation option with 
```
    var options = {
      interaction: {
        navigationButtons: true
      }};
```
the navigation buttons appear on Chrome (55.0) but not on Firefox (52.0 ).
I've tried on Fedora 25 and on Windows 10, probleme is on both.
Here is the full code of my Polymer element : https://github.com/scenaristeur/0smag/blob/master/public/smag-vis.html

Do you think this could to the [polyfills system](https://www.polymer-project.org/1.0/docs/browsers) ?
Do you have any suggestion ? 
thx

**Comment by wimrijnders** [comment]
I can verify that `navigationButtons: true` works as intended on Firefox (linux). I really think this is due to an external factor.

Digging deeper:

- I can verify that the same Firefox does not support `<link rel='import'>` tags, but Chrome does.
- The behaviour on your 'demo' site is what I would expect if the **vis.js CSS file is not loaded**.
- `polyfill` appears to be using [webcomponentsjs](https://github.com/webcomponents/webcomponentsjs) underwater. This adds handling for the `<link rel='import'>` tags for browsers that do not support it.
- See this open issue : [#400](https://github.com/webcomponents/webcomponentsjs/issues/400) on `webcomponents.js`

This is as far as I will go with this. If you wish for more support, please isolate the problem in a `jsfiddle` demo or similar. The demo site is _very_ confusing to navigate through.

My conclusion for now is that it is not a `vis.js` problem and I will flag it as such.

**Comment by wimrijnders** [comment]
> Do you have any suggestion ?

Perhaps one: see if you can add a link the the `vis.js` css-file in your top document, outside of all the link-imports. I have a strong suspicion that that will solve the issue.
