### ISSUE TITLE
show all vis-group on load, not only in visible area

### ISSUE THREAD

**Issue by scorbesir** [almende/vis#2956]
Hello,

Can someone explain me how i can disable the performace setting. I dont want groups or items to be empty. i want to show all the groups and items at all times. 

![screenshot_365](https://cloud.githubusercontent.com/assets/27006213/24796244/830000fa-1b8c-11e7-88e9-4de54a6bb9d3.png)

Greetings,

**Comment by bradh** [comment]
This is a bit vague. I'm sure you understand what you want, but we can't see your screen, so you need to describe it to us. From the stuff you've pasted, I'm not sure what part of the code you are referring to (probably network, but maybe timeline or something else).

Can you try to produce a jsbin that shows what is happening, and describe what you want to happen instead?

**Comment by yotamberk** [comment]
Hi @scorbesir ,
You can't disable the performance setting through the options. We can direct you to the line where this happens and you can disable it in the code. This is not advised though since it has substantial performance effects. If you're planning to change this, it might be better if you add it as an option that can be set, like: `keepItemsNotInFrame: true`, or something of that sort. 
The lines you are looking for are here: 
https://github.com/almende/vis/blob/master/lib/timeline/component/Group.js#L243
if you change it to `true`, it will always show the items.

**Comment by scorbesir** [comment]
Hi Yotamberk,

Thanks, it works. When i set that group to true, it works also not, so i have set true to all isVisible in RangeItem, Item, BoxItem, PointItem and ,BackgroundItem and all rows are visible when page are loaded.

This can be closed, its solved now.
