### ISSUE TITLE
Timeaxis with only Mondays in timeline

### ISSUE THREAD

**Issue by dlc4gl** [almende/vis#2998]
Hi,

I would like to show only Mondays from Jan 1, 2018 to Dec 31, 2018 on my timeline.  Please review my example at https://jsbin.com/zihisuq/2/edit?html,output.  Currently only January and October have Mondays.  The vertical scrollbar shows, but for some unknown reasons the horizontal scrollbar does not show.  I have searched the vis.js timeline documentation, vis.js timeline examples, Stackoverflow & github issues and found no solution.  

Question 1:  Is it possible to show only Mondays on the timeline?
Question 2:  Is it possible to show the horizontal scrollbar?

Thank you for your help.

**Comment by brichbe** [comment]
1)  It should be possible to display only Mondays, but it does seem like there's a problem where the `timeAxis.step` value is not consistently honored.  I see in your example all the Mondays are shown in January, but then after January 29th, the next day shown is Feb 1st which is clearly wrong, but after that the 7 day step is honored through that month, and that pattern continues through the year.  I don't have time right now to track this down in the source, but feel free to start looking.

2)  I don't believe the `horizontalScroll` option is meant to display a scrollbar; rather it's meant to change the mouse wheel behavior to move the timeline left/right rather than zooming in/out.  See http://visjs.org/examples/timeline/other/horizontalScroll.html

**Comment by yotamberk** [comment]
@dlc4gl about question 2: there is no horizontal scrollbar. It has been requested in a feature request but not implemented yet.

**Comment by jgorene** [comment]
@dlc4gl , About Question 1
A solution using moment.js (but not mandatory, it is also possible with js pure), quite useful and finally fairly easy to implement that works anyway.
Here is an [example](https://output.jsbin.com/siyixe/18) taken from your JSBin...
If this can match what you would like to do ;)
