### ISSUE TITLE
Smooth dynamic causes "Node no predefined level or all" Exception

### ISSUE THREAD

**Issue by Steff1337** [almende/vis#3036]
Hello,

i am using visjs for a small Vaadin addon project. I created an addon using the visjs network to display control flow graphs. This addon works so far, except for one exception i get everytime i use hierarchical layout in combination with smooth edges.

If is set:
```
 "smooth": {
                "enabled": true,
                "type": "dynamic",
                "forceDirection": false,
                "roundness": 0.5
            }
```
inside the options only everything works fine (with or without using hierarchical layout).

But if is put this code also to a specific edge, i get the following exception:

> To use the hierarchical layout, nodes require either no predefined levels or levels have to be defined for all nodes.

This by the way only occurs if i use the DYNAMIC type. All other types seem to work.

This was tested inside the addon project as well as in a small standalone HTML/JS testproject.

I am not sure if this is intended, a bug or just wrong usage. I would be really happy if you could help me.

Thanks in advanced. :)

Regards,

Steff

**Comment by wimrijnders** [comment]
I can verify that the exception is intentional; either all nodes need a level defined or none of them. This is done by checking for the presence of field `level` in the nodes. However, there is no immediate relation with option `smooth.type : 'dynamic'`.

I tried out a network according to your description, but I don't see anything special. Would you mind setting up a `jsfiddle` or similar to show the problem?

**Comment by Steff1337** [comment]
Hello,

sorry for the delay but i went on a short vacation lat weekend^^.

So here is the [example on jsfiddl](https://jsfiddle.net/apnmmc5q/1/).

I have tested it again and it seems that using the dynmic type per edge is the problem. If i use it only ins the edges global options (line 56) and do not use smooth per edge (lines 405, 467 and 529), the network works. But if i use smooth per edge with type dynamic per edge, the network wont show up with the above exception. Any other smooth types seem not to have this issue.

Regards,

Steff

**Comment by wimrijnders** [comment]
@Steff1337 Thanks for taking the trouble of creating an example. The problem is a bit clearer now.

There are at least two things interacting with each other here:

1. The value for option `edges.smooth.type` for the main options gets overridden by `horizontal` or `vertical`if the initial value is `dynamic`.
2. However, this overriding does not happen if `edges.smooth.type` gets set per node. So, the type remains `dynamic` regardless.
3. An internal feature of `dynamic` is that an extra node is added to the tree, to guide the form of the `dynamic` node (i.e. it's a Bezier curve).
4. This node is then added to the node list. The tree layout algorithm then attemps to use this extra node in the tree layout, which fails.

So, the resolution is something like this:

- It's obvious from the code for setting up options, that `type: dynamic` is not allowed for tree nodes. If options are set for nodes explicitly, `dynamic` should be forbidden.
- An internal check must be added (notably in `LayoutEngine.setupHierarchicalLayout()`) to avoid having nodes in Bezier curves being added in the tree layout.

These conclusions are taken in the spirit of the current code. I'm open to alternative suggestions.

(I'm a bit miffed by this, though. I'm pretty sure I've seen tree layouts works with `dynamic`. Need to recheck this).

**Comment by Steff1337** [comment]
@wimrijnders Thanks for your quick and detailed response :)

Now i understand the problem. What also seems to work somehow is to set a default level in the global node options if a level per node is used. Then the network shows up but looks a little bit odd.

I think i will rather use your suggestion and only allow dynamic inside the global edge options.

**Comment by wimrijnders** [comment]
> only allow dynamic inside the global edge options

Or, when looked at from the other direction: do _not_ set `type:dynamic` in the options of the nodes themselves.

Yes, that is definitely the easiest way to go. It's still a bug, though, that needs fixing. Thanks for reporting it.
