### ISSUE TITLE
graph size changes and gets blur when window resize or the container dom size changed

### ISSUE THREAD

**Issue by DanielWLam** [almende/vis#3120]
Sorry to border, however, is it a "bug"? When i change resize the window or change the net-work's parent node's size, net-work change it's size too, but the nodes and edges could get too much big or too much small.  It looks like the pic I show: 

![image](https://cloud.githubusercontent.com/assets/8369212/26668004/5f4bd89a-46da-11e7-9bee-113df67d8228.png)

**Comment by wimrijnders** [comment]
Hi there. Not sure what I should be looking at. Ignoring the censoring, it looks fine to me.

Is your worry that the nodes will be too large for the screen (when increasing size)? And that the nodes will become microscopic (when decreasing size)? In that case perhaps you can add an automatic scaling of the network if sizes change. Take a look at method `Network.fit()` in the [documentation](http://visjs.org/docs/network/#methods).

Otherwise, please make a `jsfiddle` or suchlike to illustrate the issue.
