### ISSUE TITLE
Network - image scaling seems to be broken in IE11 and Chrome 

### ISSUE THREAD

**Issue by dockstreet** [almende/vis#3149]
Hi,

With version 4.20.0 it seems like for IE11 I have to now make all of the images the same size or I have issues, I did not with 4.19.0

Chrome does not seem to have this problem, but another. The images now seem to 

My fix for IE is simply to resize them all with mogrify/convert  -resize 300x300! from ImageMagick portable command line to the same size.

I do not have a fix for Chrome , other than to zoom in. 

I'm not sure if I can reproduce this as i'm not coding the JavaScript directly but instead using it from wrapper in R https://github.com/datastorm-open/visNetwork. 

I could maybe do a screenshot? but would have to redact it substantially.

**Comment by wimrijnders** [comment]
>  I have to now make all of the images the same size or I have issues

What issues specifically?

> The images now seem to

Now seem to what?

Would you mind being more specific in describing what is not working in your opinion? I can't give a directed answer if I don't know what the actual problem is.

-----

There are two things I ask you to try here:

**1. Disable interpolation.**
This is a feature that was enhanced in `v4.20.0`. It is possible that this has side-effects in untested browsers (sorry, no access to IE11; I abandoned windows long ago).

I must assume that you have the capability to set options. Please set the following and see if the images are handled better:

```javascript
nodes: {
  shapeProperties: {
    interpolation: false
  }
}
```

**2. Disabling resizing images to same size**
By default, all images used in nodes are resized on-screen to the same dimensions. By the act of resizing, this may have an effect on the quality of the images.

Please disable this automatic resizing and see if the images display better.

```javascript
nodes: {
  shapeProperties: {
    useImageSize: true
  }
}
```

**Comment by dockstreet** [comment]
Hi - I'm feel free to close this, the Interpolation = false - helped ! 
UseImageSize = true; I would need to rescale the images even smaller, I may end up going that way - but for now your great suggestion helped none the less. 
:-)

I have to now make all of the images the same size or I have issues
What issues specifically? 
Specifically - not all of the images would be displayed, and be blank only the edges connecting where an image should be. So I made them all the same sized with an ImageMagick convert batch, and this seemed to correct the issue. For some being blank but not others. Use image size would have worked, but the images I was supplied were all of different resolutions so it ended up looking like a collage - interesting but not where I wanted to go. 

(In Chrome - not IE ) The images now seem to
Now seem to what? The images in Chrome seem to have artifacts, disabling the interpolation removed abhorrent pixes being displayed randomly around the image edges. 

Thanks again for the help!!!!

**Comment by wimrijnders** [comment]
Hey, thanks for taking the time to fill in the blanks!

>  feel free to close this, the Interpolation = false - helped !

I'm happy to learn that you have solved your problem. However, I'm a bit worried that the option does not appear to work on IE. I'm the one who made that change (#3010), and I have to confess that I did not test on IE. I intend to make am issue to test this.

> not all of the images would be displayed, and be blank only the edges connecting where an image should be.

This might be an indication of another problem, namely that not all images are available when the network is initialized - they may still be in the process of downloading (this can actually happen IRL).

To check if this if happening, please perform this simple test: Load your network, count to ten and click or drag any node. Are now some (or all) of the images now suddenly displayed?

> The images in Chrome seem to have artifacts, disabling the interpolation removed abhorrent pixels being displayed randomly around the image edges. IE11 was surprisingly fine with this.

The artifacts are exactly the problem that #3010 solves. What you are saying, is that IE11 does a better job by default at interpolation than Chrome (and Firefox also). Perhaps there should be a check somewhere on which browser is running, so that interpolation is disabled by default for IE11. Will think about this.

> Thanks again for the help!!!! :-)

My sincere pleasure; thank *you* for pointing a possible problem out, and for being willing to add extra info.

**Comment by wimrijnders** [comment]
I'll close the issue now; feel free to add the results of the test mentioned in previous test, if you perform it.
