### ISSUE TITLE
Can't include hidden nodes to cluster in joinCondition

### ISSUE THREAD

**Issue by dheerajbapat** [almende/vis#3164]
As joinCondition loops over this.body.nodeIndices I am not able to include hidden nodes while forming a cluster.
I think looping over this.body.nodes will solve this.

Scenario: If I have filter on color of nodes (say red nodes are hidden) & I cluster by shape of node.
Then I change filter to show red nodes. Those node will appear out of cluster.
Because those were not included in cluster as it was hidden while forming cluster.

Workaround: process clustering again while changing filters & process filters again while opening cluster.

**Comment by wimrijnders** [comment]
> As joinCondition loops over this.body.nodeIndices I am not able to include hidden nodes while forming a cluster.

This is, in fact, the intended purpose of `network.body.nodeIndices`. Only the id's of the *visible* nodes are in this list. The full list of nodes, as you correctly point out, is in `this.body.nodes`.

I don't fully understand your scenario, but I think the intention is to use clustered nodes to create new clusters, is this correct?

In that case, I feel that your workaround is the correct way to do this. If your think otherwise, please let me know.

**Comment by dheerajbapat** [comment]
Thanks for the response.
My scenario is here: http://jsfiddle.net/agfqf6mt/1/ 
Step 1: Click 'Toggle Red Nodes'
Step 2: Click 'Toggle Cluster Square'
Step 3: Click 'Toggle Red Nodes'

In this case joinCondition does not consider hidden nodes.
How to consider hidden nodes as well while clustering?

My guess was looping over this.body.nodes (in vis cluster function) will solve this.

Or is there any better way to achieve this?

**Comment by wimrijnders** [comment]
@dheerajbapat Thanks for the great demo! Looking into it now.

**Comment by wimrijnders** [comment]
There's more going on here than I presumed. I'll keep a list here and expand it as needed.

* `network.GetconnectedEdges()` also returns the cluster edges for a given clustered node. Due to the update of the `hidden` field, the edges DataSet get contaminated by these. Cluster edges must be skipped.
* clustered nodes are hidden already; their hidden state should not be toggled in `toggleRedFilterEle()`
* for a given edge, field `hidden` shouldn't be toggled if the *other* node is clustered or hidden.

*Not done yet*
----
This escalated badly; I'm seriously thinking to add hide/unhide functionality to `Network`. I don't think the casual user wants to be confronted by this.

**Comment by dheerajbapat** [comment]
Thanks for understanding and taking it on priority :smile:

**Comment by wimrijnders** [comment]
**Interim note:** I feel like I'm making a mess of fixing this.

The states `hidden` and `clustered` are actually two different things; the problem here is that the `hidden` state is sort of used to identify both these states in the current code.

I've been trying to consolidate the code to a state in which it works as expected. I've just come to the realization that it would be much better to just accept that `hidden` and `clustered` are two different things and that they should be identified and handled separately.

OK, so it's back to the drawing board for me.

**Comment by wimrijnders** [comment]
OK, I've figured it out. Here's a [demo](http://jsbin.com/zetonut/edit?js,output), please check if it works as expected.

I'll put further information in the PR, which should be accessible from this issue.

**Comment by dheerajbapat** [comment]
Thanks! 

I could not check your demo, because it is giving below exception in console.
Refused to execute script from 'https://raw.githubusercontent.com/wimrijnders/github_bugs/master/vis/issue3164/vis.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.

Then I saved your vis.js and it is working great!
Thanks for fixing.

**Comment by dheerajbapat** [comment]
Still have the problem with latest vis 4.21.0
http://jsfiddle.net/agfqf6mt/3/
