### ISSUE TITLE
onAdd does not fire when adding new item to timeline manually

### ISSUE THREAD

**Issue by helgrima** [almende/vis#3180]
When adding new items manually to timeline "onAdd" -event does not fire. This can be easily tested with example 
[http://visjs.org/examples/timeline/editing/editingItemsCallbacks.html](http://visjs.org/examples/timeline/editing/editingItemsCallbacks.html)

Open developer tools of your browser and type in following
`
timeline.itemsData.add({start: new Date(), type: "point"});
`

My assumption is that "onAdd" event of timeline should be fired, but only event from dataset is fired. 
My use case here is that I must validate new data points, which I create manually with code, against the server to check if are they valid. And if not I can easily reject them with callback.

**Comment by yotamberk** [comment]
@helgrima I don;t see a problem. The `onAdd` event is fired. You can see it in the example

**Comment by helgrima** [comment]
It is true that "add" event on item collection is firing, but I meant that "onAdd" event on timeline object is not firing, ie. prettyPrompt is not showing up. Tested with latest Google Chrome and Internet Explorer 11.

**Comment by brichbe** [comment]
@helgrima I get the `onAdd` callback prompt when double-clicking an empty area of the timeline, so I don't see an issue either.  Tested with the latest Chrome/FF/IE.

**Comment by helgrima** [comment]
@brichbe Yes, double clicking on timeline creates popup and fires the `onAdd` but when adding item to timeline with javascript `onAdd` does not fire. Let's take this example: [http://visjs.org/examples/timeline/editing/editingItemsCallbacks.html](http://visjs.org/examples/timeline/editing/editingItemsCallbacks.html)
When I double click on timeline following piece of code is executed:

`
onAdd: function (item, callback) {
      prettyPrompt('Add item', 'Enter text content for new item:', item.content, function (value) {
        if (value) {
          item.content = value;
          callback(item); // send back adjusted new item
        }
        else {
          callback(null); // cancel item creation
        }
      });
    },
`

But when I do insert new time with following code:
`timeline.itemsData.add({start: new Date(), type: "point"});`
`onAdd` of timeline does not fire and I am wondering should it fire or not? And I know that `add ` event of DataSet is firing, but that event is not that useful as you cannot cancel that event.

**Comment by brichbe** [comment]
Short answer:  no it should not be fired.

You are misunderstanding the difference between those two events, that one applies to the [Timeline API](http://visjs.org/docs/timeline/) and the other applies to the [DataSet API](http://visjs.org/docs/data/dataset.html).

The timeline's `onAdd` event is fired as a result of a  _human-driven_ action upon the UI, thus it allows you to cancel the action if your app considers the user's input invalid (such as the referenced example cancels the action if the user attempts to enter a blank content value).

This is different from the DataSet firing its own `add` event when a new item is inserted into the set.  This is a _program-driven_ action, which occurs when your app programmatically adds new items into your timeline's DataSet, or it occurs anytime the `onAdd` callback is not cancelled.  It makes sense there's no way to "cancel" this `add` event because this input is not coming directly from the user.  If for example, your program gets data from a server and you need to validate it, simply do so _before_ adding to the DataSet rather than expecting a callback.

Adding data items to your timeline using the browser developer tools certainly isn't recommended so it's not very helpful, but what that's doing is adding a new item directly to the DataSet -- it's not interacting with the Timeline UI, so that's why you see the `add` event fired but not the `onAdd`.

**Comment by helgrima** [comment]
Thank you for detailed explanation. Now I understand that `onAdd` event is not supposed to fire when adding items to timeline programmatically.

However, is there some nice way to fire this `onAdd` event when adding items to timeline programmatically? As it would be really nice to have validation logic for new item in `onAdd` listener, whether item is introduced into timeline by user input or by programmatically.

**Comment by bradh** [comment]
You could just call whatever validation logic you have manually.
