### ISSUE TITLE
How to disable overlapping items intervals - timeline

### ISSUE THREAD

**Issue by SkyTaurus** [almende/vis#3190]
How to disable overlapping items intervals?
I need to ensure that the intervals do not intersect when moving elements.
I set option stack: false, but they run against each other.

**Comment by madebydavid** [comment]
To do this when moving elements, I think you can add the `onMoving`  attribute to the [timeline options](http://visjs.org/docs/timeline/#optionTable) - this is a function which will only allow the item to be moved if you call `callback(item)`.  Inside that function you would need to implement the test to see if the item is overlapping with any others.

There's a [file in the tests folder](https://github.com/almende/vis/blob/9703462783923ceb52107f0f3fe070de7cb0fe8f/test/timeline_groups.html) which shows the `onMoving` function in action, but checking against a min date rather than an overlapping check.

**Comment by yotamberk** [comment]
Don't you need simply `stack: true`?

**Comment by SkyTaurus** [comment]
I use the timeline to schedule the playback of media files. Obviously, several can not play simultaneously.
I need them to be arranged in one row.

**Comment by madebydavid** [comment]
I think you just need something like this:

```javascript
    onMoving: function (item, callback) {

      var overlapping = items.get({
        filter: function(testItem) {
          if (testItem.id == item.id) {
            return false;
          }
          return ((item.start <= testItem.end) && (item.end >= testItem.start));
        }
      });

      if (overlapping.length == 0) {
        callback(item);
      }

    },
```

The internal functions for stacking can't really be used for this - they rely on knowing the item's `top` position.

**Comment by SkyTaurus** [comment]
It's great, partly working. Now it is necessary that the selected element can stand between the elements , since there the interval allows.
http://prntscr.com/fm5402

**Comment by bradh** [comment]
So you want to drag to the space between the elements, but to not allow overlap? Just use the `onMove` callback to reject instead of `onMoving`.

**Comment by SkyTaurus** [comment]
Yes, but I need to understand that the element can fit there. After all, there is an internal function that will check it and if there is np space between the elements then it makes a stack. I want to understand how to call it in a method.

**Comment by bradh** [comment]
You can calculate it yourself, or just use the callback check. I don't think there is any API you can use to know in advance - just reject it in the callback if it overlaps.
