### ISSUE TITLE
window.open and DataSet

### ISSUE THREAD

**Issue by pradeepacc** [almende/vis#3191]
I have a html which has DataSet defined and I am trying display the same graph in page 2 with window.open. I have added a 'non-working' sample to jsfiddle just to get an idea of what is been tried.
https://jsfiddle.net/zcgvqh29/

In the original code, I added debug pointers into the vis.js and I can see the nodes and edges coming in but it is of object type and not DataSet. Because of this, it fails in the setData() function in the library.
Library code as below:
if (nodes instanceof DataSet || nodes instanceof DataView) {
     this.body.nodes = nodes;
} else if (Array.isArray(nodes)) {
    this.body.data.nodes = new DataSet();
    this.body.data.nodes.add(nodes);
} else if (!nodes) {
    this.body.data.nodes = new DataSet();
} else {
    throw new TypeError('Array or DataSet expected');
}

In page 1, when this code in the library is executed the "nodes instanceof DataSet" is true. But when this is executed from page 2 using window.opener.data, the 'nodes instanceof DataSet' is false, 'nodes instanceof DataView' is false, 'Array.isArray(nodes)' is false and it goes to else condition and throws TypeError and do not render network.

Any reason why the nodes is not a DataSet when referred through window.opener, even though I can see the data with values inside while debugging, it is not any one of these types DataSet/DataView/Array and how to resolve this?

**Comment by wimrijnders** [comment]
This is basically not a question about `vis.js` but about html and javascript. I'm therefore marking it as **invalid**. But since I have put effort into it, I'll give an answer.

The datasets are initialized using the `vis.js` in the first page. In the new page you are *reloading `vis.js`*, hence a different code base. This screws up the usage of the non-trival objects defined in the first page.

The easy way out is to transfer *simple* objects between pages, i.e.:

```
    var nodes = [                  // drop new.DataSet()
...
    ];

    var edges = [                  // drop new.DataSet()
...
    ];
```

This removes the dependency on the `vis.js` in the first page.

And do something with `</script>` tags in the second page. I am truly wondering how you got it to work (sorry, but I'm a bit annoyed).

**Comment by pradeepacc** [comment]
Thank you. Sorry for not being clear on the statement. There are 2 ways I tried. 
I have shown the second option I tried where I was stuck with and you have clarified on your response. 
First option I tried was from the parent screen, I tried something like this
var newnetwork = new vis.Network(newpage.document.getElementById('newscreen'), data, options)
This worked in Chrome and FireFox but not in IE.
