### ISSUE TITLE
Timeline - Overlapping items when setting margin in options to -15.

### ISSUE THREAD

**Issue by DavidHessling** [almende/vis#3209]
Hi guys,

we want range items to align to each other if one ends and another one starts with the same point in time. If their time range overlaps, we want them to stack. To do this, we set the horizontal margin to -15.

In this thread ( https://github.com/almende/vis/issues/1652 ) it was said that this is the solution.

Unfortunately, sometimes it appears that the range items overlap instead of stack.

Here's a bin to show this behaviour:

https://jsbin.com/doligadeqi/edit?html,js,output

Do you have any idea, how we could solve this issue?

Thanks a lot,

David

**Comment by brichbe** [comment]
Setting a negative margin seems like a fragile hack.  I don't have time to create an example right now, but one option would be using subgroups, which would allow you to explicitly control stacking of your items.

The basic idea is that all non-overlapping items belong to a single "default" subgroup, and with the timeline stacking disabled, all these items would appear aligned at the same height.  Listen for events anytime an item is moved (or added/changed depending how your app works), and when these events occur compare item start/end times to determine whether this item overlaps with any of the other existing items.  If it does overlap, give this item a unique subgroup Id so it'll appear stacked away from the others; otherwise set it's subgroup Id to be your "default" one.

**Comment by yotamberk** [comment]
I wouldn't set a negative value unless it was a -0.5. not more than that. What @brichbe suggests is the way to go
