### ISSUE TITLE
visualization vis-center vis-item 

### ISSUE THREAD

**Issue by krishnakore** [almende/vis#3233]
HI,
I am facing the all vis-item placing at 0*0 position. I have seen that from the visualization div, the height showing 0(zero). I have set the height 170 in **options**, 
I am using this framework in 2 places in my Application. One is coming fine. The other one is having issue. And the Issue is wondering me that some times appearing properly in chrome. But not in IE all time.

![vis](https://user-images.githubusercontent.com/6780829/27821129-801f2960-60a1-11e7-9f82-fce031992417.png)

![vis2](https://user-images.githubusercontent.com/6780829/27821187-bdfa2ae6-60a1-11e7-83d8-ab3a4d197c0b.png)

 Thank you.
Ram

**Comment by wimrijnders** [comment]
I really have trouble understanding what the issue is.

* With what `vis.js` module is this happening? E.g. `network`, `timeline`, `graph2d` or `graph3d`.
* What is 'the issue' exactly? That the view is empty? Please clarify.

It would be a big help if you can set up a demo on `jsfiddle` or suchlike illustrating the problem.
I get the strong impression that this is an HTML question, because I don't see a single line of code directly related to `vis.js`. If so, this issue will be flagged as `Invalid`.

**Comment by krishnakore** [comment]
Thank you so much for reply.
I have solve this issue..

**Comment by wimrijnders** [comment]
OK, great. Have a good day!
