### ISSUE TITLE
Error in Network options (Angular 4)

### ISSUE THREAD

**Issue by JaroslavPrt** [almende/vis#3314]
I am trying create 'network', and getting error (first image), but in docs said that it is optional prop: http://visjs.org/docs/network/edges.html

![image](https://user-images.githubusercontent.com/11339544/28745908-fb704412-748a-11e7-9127-54f9987535bb.png)

after add prop have next error in browser console
```
ERROR TypeError: Cannot create property 'enabled' on boolean 'true'
    at Object.e.mergeOptions (vis.js:1353)
    at Function.value (vis.js:36856)
    at t.value (vis.js:35888)
    at o.setOptions (vis.js:33348)
    at new o (vis.js:33315)
    at AppComponent.webpackJsonp.../../../../../src/app/app.component.ts.AppComponent.makeTree (app.component.ts:61)
    at SafeSubscriber._next (app.component.ts:21)
    at SafeSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.__tryOrUnsub (Subscriber.js:238)
    at SafeSubscriber.webpackJsonp.../../../../rxjs/Subscriber.js.SafeSubscriber.next (Subscriber.js:185)
    at Subscriber.webpackJsonp.../../../../rxjs/Subscriber.js.Subscriber._next (Subscriber.js:125)
defaultErrorLogger @ core.es5.js:1020
VM129 htmlfile?c=_jp.aktje5b:8 Uncaught DOMException: Blocked a frame with origin "http://localhost:4200" from accessing a cross-origin frame.
    at http://localhost:4200/sockjs-node/893/bn1xx0t1/htmlfile?c=_jp.aktje5b:8:19
(anonymous) @ VM129 htmlfile?c=_jp.aktje5b:8
```

```
 const data = {
      nodes: new vis.DataSet(this._generateNodesData(treeData.nodes)),
      edges: new vis.DataSet(this._generateEdgesData(treeData.edges))
    };

    const options = {
      edges: {
        smooth: {
          enabled: true,
          type: 'cubicBezier',
          roundness: 0.4,
        }
      },
      nodes: {
        color: '#ff0000',
        fixed: false,
        font: '12px arial red',
        scaling: {
          label: true
        },
        shadow: true
      },
      layout: {
        hierarchical: {
          direction: 'UD'
        }
      },
      physics: false,
      interaction: {
        dragNodes: false,
        dragView: true,
        hover: true
      }
    };

    const container = document.getElementById('vis-tree');
    this.network = new vis.Network(container, data, options);

```

 
Help to fix pls! thx

**Comment by wimrijnders** [comment]
> ERROR TypeError: Cannot create property 'enabled' on boolean 'true'

This looks like a giveaway on what is happening. There are only a couple of options with explicit value of true in your example, it should be possible to check them all.

I can't tell from here if this is a `Network` bug or something due to the combination with `Angular`. I'll assume for now that it's a `vis.js` thing and treat it as such. I'll report the results here of the analysis.

**Comment by wimrijnders** [comment]
PR #3281 fixes a bug which might have caused this. Which is interesting, because the bug itself has not been released in the first place.

Are you by any chance compiling `vis` from source, and then specifically from the `develop` branch? That's the only explanation I have. In that case, please pull `develop` again. But really I would advise just using the stable version - either the latest release or the `main` branch.

If the above assumption is not correct, please inform me. It might then be another problem.

**Comment by JaroslavPrt** [comment]
thx for answer, 
i'm using version 4.20.1, https://www.npmjs.com/package/vis

**Comment by wimrijnders** [comment]
OK, so it was a bug in `util.mergeOptions()` in `v4.20.1`. The good new is that it's fixed for the next release.

The workaround is as follows:

```js
    const options = {
      nodes: {
        scaling: {
          //label: true
          label: {
            enabled: true
          }
        }
      }
    };

```


HTH

**Comment by wimrijnders** [comment]
Fixed by #3280.

**Comment by wimrijnders** [comment]
Please close the issue if you're happy with this response.

**Comment by JaroslavPrt** [comment]
thanks for the help
