### ISSUE TITLE
edge display with smooth  and overlapping issues

### ISSUE THREAD

**Issue by kandangit** [almende/vis#3349]
Hello

There is a network graph that uses hirarchical layout and has one root node and edges connecting from there representing answers.

My comment is to request improvements in the way edges are displayed and get some recommendation on my comments below if possible please, (hope it doesn´t come accross as many things in once issue, just want guidance on issues around displaying edges between nodes in a hierarchical graph).
(Have seen a related issue about edges overlapped)

In my graph, users can manually add/delete nodes/edges (between any nodes).

To avoid overalapping edges I have to manually add smooth to the eges (curvedCW/curvedCCW) using an algorithm. But this can get complicated since between two nodes, there can be edges in both directions.

This also creates a problem, where edge labels (which are given by users) can also overlap.
 
See example

**https://jsbin.com/kolicet/edit?html,js,console,output**

Is feasible this can be changed or is a recommendation for better handling of this?

Similar to font.vadjust, can exist a font.hadjust? It would allow me to give the user the option to set this attribute and move edge labels better 

Final question is, based on the example, If I change edge with id 305 (Label: FLIGHT) so from/to are reversed (to look the same change from CCW to opposite CW) then the whole graph is displayed differently (only change is one edge was changed direction from/to). why happens ?

(Sometimes nodes are displayed in a default layout, but would be better they are by default moved in case they overlap with other edges (as in example, second_attempt))

Many thanks for the help

**Comment by wimrijnders** [comment]
> To avoid overalapping edges I have to manually add smooth to the eges (curvedCW/curvedCCW) using an algorithm.

Currently, this is the best way to do it - I reached the same conclusion in #1957. There is no plan right now to deal with overlapping edges, mostly because I don't really have a good idea on how to handle it. Suggestions are welcome.

> This also creates a problem, where edge labels (which are given by users) can also overlap ...
Is feasible this can be changed or is a recommendation for better handling of this?

Currently, it is not feasible to change, see my remark above. To avoid the overlap of the edge labels (notably 'FLIGHT' and 'TRAIN' in you example), I can think of two approaches:

1. Increase the roundness of the curves:
```js
     "smooth": {
       "type": "curvedCW",
       "forceDirection": "none",
       "roundness": 0.5   // This is max roundness
     },
```
2. Use a font alignment different from `horizontal`:
```js
    "smooth": {
       "type": "curvedCW",
       "forceDirection": "none",
       "roundness": 0.5
     },
     font: {
       align: 'bottom'
     }
```

Here is what both approaches look like, used for FLIGHT and TRAIN respectively:

![canvas](https://user-images.githubusercontent.com/769037/29310782-71cee4c0-81af-11e7-9a2b-472bef99d35d.png)

> Similar to font.vadjust, can exist a font.hadjust?

Option `font.vadjust` is not meant for big displacements, only for small font corrections. See #3215. But I understand your intention. I suppose a displacement for the entire label (not just the font) should be feasible. Will think about this.

> If I change edge ... so from/to are reversed ... then the whole graph is displayed differently ... why happens ?

It's because of the way the edge direction is handled when setting up the display. The to-direction has priority.
It's quite hard to divine a repeatable layout from just the edge directions. If you need a more static layout, it's better to explicitly set the levels per node, e.g.:

```js
 var nodes = [
    {"id":249,"label":"START", level:0},
    {"id":250,"label":"IDENTIFICATION_ID", level:0},
    {"id":251,"label":"IDENTIFICATION_PASSPORT", level:1},
    {"id":252,"label":"PRODUCT", level:2},
    {"id":255,"label":"FIRST_APPOINTMENT", level:3},
    {"id":265,"label":"SECOND ATTEMPT", level:1}				
  ];
```

HTH. Sorry I can't give you a definitive wrap-up of the issue right now.

**Comment by kandangit** [comment]
Thanks for the answer. ,understand.
I always set label direction to default (horizontal). I think looks better and since the API deals with different graphs created differently, cannot work out the best alignment in each case.

If is feasible then keep this open just for the hadjust change.  

In some cases may look as good option to have some labels displaced through x axis from the center of the edge. In example, "FLIGHT" to the left, and "TRAIN" to the right.


cheers

**Comment by wimrijnders** [comment]
That would be visually in order; however, I have no overview in how to implement that in a consistent and generic manner (handling exceptional cases is a different matter of course). I am totally open to suggestions and solutions here.

**Comment by wimrijnders** [comment]
Does this answer your question? If so, please close the issue.

**Comment by kandangit** [comment]
yes. Issues were answered, was not sure if the hadjust parameter (to provide an horizontal displacement of the label in relation to its edge) was something being considered. ?

Can close as seems from the comment the way to implement this is not straight forward compared to vadjust
