### ISSUE TITLE
Clustering `clusterOutliers` / `joinCondition` seems to be broken.

### ISSUE THREAD

**Issue by sawatts** [almende/vis#3367]
Trying to do some intelligent clustering using `clusterOutliers` with `joinCondition` - not getting the expected results.  The presence of `joinCondition` seems to prevent clustering for anything other than `undefined` value:

Depending on the value assigned to `joinCondition` the following behaviours are observed:
- Not present or set to `undefined` and clustering occurs (possibly wrongly...).
- Set to `null` and no clustering occurs.
- Set to a `true` function and no clustering occurs; would expect this to be the same as no join function?
- Set to a `false` function and no clustering occurs; this is as expected though possibly by chance,
- Set to an intelligent function and no clustering occurs.

This is demonstrated in the [jsbin](http://jsbin.com/nenenat/18/edit?html,output) by changing the value of `join_` between `undefined`, `null`, `joinAll_`, `joinNone_`, and `joinLevel_`.

In addition, when clustering does occur (for `undefined`), of the three leaf nodes in the example, only two are clustered with their parent. The last node (5) is also a leaf but is not joined with its parent cluster.

**Comment by wimrijnders** [comment]
## Analysis

### General working: 
Method `clusterOutliers()` does a pre-filtering on nodes with one edge. This allows for the combinations: (1, 3), (2,4) and (2,5). For eligible nodes, `joinCondition()` is run. Whatever comes through is put in a list of possible clusters. 

The found cluster possibilities are added sequentially in the given order; on every cluster addition, these checks are done:
- if a given node is already part of a cluster.
- if it's a valid cluster. For this case: if there are >= 2 nodes in a cluster

### joinConditions in example

1. **`undefined`:** On addition of the clusters, the first two combinations are added but (2,5) is rejected because 2 is already part of cluster (2,4). This smells tot me like noncompliance to the documented behavior, hence a bug.

2. **`null`:** `Uncaught TypeError error options.joinCondition is not a function`. Further clustering handling is skipped. I'd say that this is expected behaviour, since `null` is not specified in the doc's (hence `undefined` 🤣 ....never mind).

3. **`joinAll_`:**  Only one node is added to a cluster, e.g. for 2 and 5 only 2 is added. Cluster is rejected because there's only one node in it. Bug by omission.

4. **`joinNone_`:** Works as expected, but only because **3.** is skipped due to return value.

5. **`joinAll_`:** Eventually fails because of **3.** (2,4) is the only combination that is eligible, but fails because the cluster is stored as (2).

### Conclusion

I can't resist saying "a clusterf* if I ever saw one". Work is definitely required here. Thanks for reporting!

**Comment by wimrijnders** [comment]
Thanks for the demo BTW, it translates quite well into a unit test.
