### ISSUE TITLE
network - glyph - node font.multi fontAwesome icon blank

### ISSUE THREAD

**Issue by dockstreet** [almende/vis#3408]
Hi,

I tried to specify a node from the multifont example with a FontAwesome glyph, but the icon I was trying to use showed up blank? 

```js
{ id: 3, font: { multi: 'html', face: 'FontAwesome' }, label: ' \uf286 <b>This</b> is an\n<i>html</i> <b><i>multi-</i>font</b> <code>label</code>', x: 40, y: 40 },
```

Is it expected or a bug? 

Or perhaps there is another way to combine an image with text in an node without SVG? kind regards!!!

**Comment by mbroad** [comment]
When you resize or interact with the graph in some way, does the icon begin to appear?

**Comment by dockstreet** [comment]
![image](https://user-images.githubusercontent.com/1080803/30061734-91d7adf2-9216-11e7-8493-bc6833d61eb9.png)

**Comment by wimrijnders** [comment]
Frankly, I'm amazed that you got that far. You might be the first to try it.
I don't think this is implemented, but I'll have a look.

**Comment by sawatts** [comment]
Coincidentally I have just been trying to do this myself - setting the italic and bold italic faces to fontawesome so that I can add icons in two different colours to the label along with regular text.

Didn't work for me either.

**Comment by wimrijnders** [comment]
Er. Okay. Uhm. I got it.

![download](https://user-images.githubusercontent.com/769037/30069117-13ccbffc-9260-11e7-864a-705127b5fc5c.png)

Eventually. all I did was upgrade `FontAwesome` from `v4.3.0` to `v4.5.0`:

```html
  <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">
```
.... because I accidentally noticed that some icons *were* working.

Go ahead, facepalm. It is that kind of moment.

**Comment by sawatts** [comment]
Not seeing FontAwesome glyphs in multi labels for FA v4.7.0.  They are fine as node icons and in regular HTML constructs.

I had the nodes (option default) `font.ital.face` to `FontAwesome`, `font.ital.mod` to empty string, `font.multi` to `true.  The node-specific label then contains `<i>\uf0c2/i> some other text` for a cloud glyph (amongst others).

Can't say I've used multi-font labels before though - so something may be wrong.  However the "blank boxes" were the correct colour at least.

**Comment by wimrijnders** [comment]
FA 4.7 working for me:

![download 1](https://user-images.githubusercontent.com/769037/30070218-0fe0695e-9263-11e7-8510-41f7db247ec2.png)

But I'm not doing anything as fancy as changing multi-fonts. Will get back to it later.

**Comment by sawatts** [comment]
This may be back to loading the options after the network has been formed (cf. #3350).  A couple of the nodes are refreshed from the server and their label icons then appear (correct colour, way too big).

I'll try to refactor to download the options before the network is first created.

**Comment by sawatts** [comment]
Nope.  Only creating the network after I've pulled the options from the server doesn't change behaviour (but at least the edges are colours after the destination!).

When the graph is first drawn, all glyphs in the labels are drawn as missing characters (cf []) but have the correct colour.  On the first update from the server, the Icon based nodes now show the glyphs in the label - but these are the same size as the Icon itself (changing the font.ital size to 4 hasn't changed the label glyph size).  Other nodes (all shape nodes) are unchanged.

FontAwesome icons are also used in the general display (buttons etc).

I probably have an overly complex set up here to try to pin down the issue.

**Comment by dockstreet** [comment]
Would it be challenging to also include an image such as a plot or graph into the node as well? not sure if the canvas supports <IMG> to include an image besides the glyphs?

**Comment by wimrijnders** [comment]
@dockstreet yes, it would be challenging. Icons work here because they get treated as characters and they just go along with the flow.

Images are supported, but only by themselves, e.g. see example `imagesWithBorders`.

A trick to combine text and images is to use **HTML overlays**, meaning that you have a floating div on top of a node. See e.g. [this demo](http://plnkr.co/edit/dznE73?p=preview) from #3300. This is a form of cheating in the sense that these are not true nodes within the network; but if it works for you, hey, who cares.

**Comment by sawatts** [comment]
Okay I narrowed down the issue(s) I was having, and managed to get good FontAwesome characters in labels (with exceptions).

- Setting 'FontAwesome' as the face for a sub-font (ital, boldital, bold) doesn't work - the glyphs appear as unknown '[]'.
- Setting 'FontAwesome' as the main 'font.face' and using the sub-fonts to assign colour (and empty mod) allows coloured glyphs in the labels of shapes; but regular characters are in serif rather than sanserif/arial.

But...

- In both cases (and as described above) FontAwesome glyphs in the labels of icon nodes (where the icon is from FontAwesome) appear with the same size as the node icon.

It _is_ cool that this (nearly) works out of the box.

**Comment by wimrijnders** [comment]
@sawatts That's great sleuth-work! Can I entice you to make a demo for this, on `jsfiddle` or suchlike?

**Comment by sawatts** [comment]
Okay first example with various nodes and labels in [jsbin](http://jsbin.com/guyikaqoge) of course works fine.  This shows examples with the node's main font set to FA, and some with just italic and bold fonts set to FA.

The only error I see is when I update one of the nodes and the glyphs in the label are lost - uncomment the 'nodes.update()' at the end to effect this.

One difference between this and my real-case is that the real case uses groups to set all but the colors and label content, while the example does it all within individual nodes.  I will try produce a copy which moves properties to groups instead...

**Comment by sawatts** [comment]
New [jbin](http://jsbin.com/vicelidune) example of the same graph with font and icon properties moved to groups, and just colours overridden in the individual node.

This now shows "multi-font" not working in labels when the fonts are set through the groups rather than in the node (bad) - for both shape and icon nodes.

Still don't see any examples of the icon-sized glyphs though.  What else is different...

**Comment by sawatts** [comment]
Big characters are here! [jbin](http://jsbin.com/duzoleqoqe).

The last difference was that I set the font properties for all 'nodes', the groups just set the icon to use, and the individual nodes set the colors and labels.  With this arrangement we see the icon-sized characters in the labels of icon nodes.

This reverts all nodes to a single font (not multi-font).  Switching to multi-font for all nodes we see the following [jsbin](http://jsbin.com/yaredatoxa).  None of the label-glyphs display, *except* in the labels of icon nodes, where they are icon-sized.

One different still is that in the "real" case both glyphs appear large in the icon labels, whereas here just the first one is.  Possible caching issue - but it doesn't change in the example if I change the glyph used in the title.

**Comment by wimrijnders** [comment]
@sawatts Excellent work! I hereby promise to honor it with a serious investigation of the code (aka 'WTF is happening').

I wish I had some token currency to reward you with. All I have is this beer icon 🍺 which I hope to share with you 🍻 .

**Comment by wimrijnders** [comment]
Looking at the code. Heavy going, but I was expecting that.

I'll be updating this list as I go - think of it as observations during debugging. Putting them here because I want them in a central location. The added benefit for you is that you can see something is happening.

----

### Notes
- (Multi)font options present on node as well as label. Node-specific options not set in Node instance on call to ctor! They *are* set in Label instance.

**Comment by wimrijnders** [comment]
Hi guys, this is to inform you that I've managed to fix the bug in the first example. It was a combination of bad transferral of options and, well, a really indecent, banal bug. If you must know, here is the fixed version:

```js
    if (fontOptions[mod][option] !== undefined) {  // Grumbl leaving out test on undefined equals false for ""
...
    };
````

The amount of time to find that was preposterous. I don't mean to whine (and bragging is out of the question), but this was a really, really hard thing to fix. IMHO of course. But there's a lesson here.

With any luck this also takes care of the issues in the rest of the example. Will check at a later time.

**Comment by wimrijnders** [comment]
FYI second example works perfectly now.

**Comment by wimrijnders** [comment]
Guys, thanks for this issue. It uncovered quite a bit of manure in the label-handling code. This is slightly offset by the amount of work it turned out to be, but I'll survive.

**Comment by dockstreet** [comment]
@wimrijnders - thanks so much for the hard work !!!!

**Comment by wimrijnders** [comment]
After examination, I conclude that the two missing icons are, in fact, correctly displayed.
Well, not really 'correct', but it's according to the set options.

The icons are:
```js
    {
      id: 3, 
      label: '\uf286 glyph shape',
      group: 'glyphs'
    },
    {
      id: 4, 
      label: '\uf286 glyph icon',
      group: 'glyphs',
      shape : 'icon',
      icon : { color: 'green' }
    },
```
Note that the icons in the label text do not have tags.

The relevant options are:
```js
  var options = 
  {
...      
    nodes :
    {
      font :
      {
        multi : true,
        ital : { face : 'FontAwesome',mod : '' },
        bold : { face : 'FontAwesome',mod : '' }
      }
    }
  };
```
Note that `FontAwesome` is used for the tags only. Non-tagged text will therefore use the default font, which is `arial`, which does not contain icons.

----
Which means I'm done here. I'm looking at one more thing derived from this issue, which is dynamically changing the groups. After that, I can submit the PR.

**Comment by sawatts** [comment]
@wimrijnders Many thanks for working this out -- an end-user requirement puts this back in out pot.
