### ISSUE TITLE
storePosition() works differently as expected

### ISSUE THREAD

**Issue by gnoric** [almende/vis#347]
Hi,
I want to create a hierarchical layout about communications. On the first load, the graph comes up quite tangled. here is a small example:
http://demo.ybcrisk.wpengine.com/
I would wish for user 6 and 8 to be next to eachother, and user 9 and 5. I can do this by dragging them next to each other, but on the next load, they are tangled up again.
I thought I can use storePosition with the stabilize callback, but turns out storePosition() doesnt actually store the positions just resets them to the initial tangled up load.

Now my questions: Is it possible what I want? Can you give us an example of how to use the storePosition() correctly? How would I go about, achieving that it allways loads the way it was drag&dropped last?

Thanks in advance, for taking your time.

**Comment by paschsaar** [comment]
Hi, 
are these Informations about hierarchical layout still valid? The documentation does not tell something about it. And can I use getSeed for hierarchical layout to?

**Comment by AlexDM0** [comment]
Hi,

The hierarchical layout does not use a random process to initialize so
there is nothing to seed. The hierarchical system has been greatly reworked
since this issue. The order is determined by the x and y positions
depending on what direction you use (in UD for instance, the x postion
handles the sorting in the x direction). I suggest you take a look at all
the examples on our website regarding the hierarchical layout.

Regards
