### ISSUE TITLE
Release 4.21.0 timeline renders significantly slower than 4.20.1

### ISSUE THREAD

**Issue by dlparker** [almende/vis#3563]
I have a pretty simple timeline, with half a dozen range items and half a dozen box items, each of which are simple. When I run it with 4.20.1 the I can just see the pause between the expansion of the vertical space for the timeline and the final rendered content. I'd guess it is about a tenth of a second or maybe less. 

If I change nothing except the version of vis, moving to the new 4.21.0 version, the delay is close to a full second. I have tried it on chrome and firefox (on linux), got the same behavior.

Note that you can see a delay, thought not as extreme, on the drag and drop example. Not enough there to take that long, I'd think.

**Comment by yotamberk** [comment]
We've applied the hiding the initial timeline until the timeline is fully loaded the first time.
It might seem slower because in < v4.21.0  the timeline would build in pieces. 
I have a PR waiting with a loading screen option to show this better. 
The idea is that if we show the timeline getting built in pieces, it will show some items in incorrect positions, and then flicker to go to the correct position. In the current version, we don't intermediate stages of the building.

I am currently working in improving the performance of both the initial render and the redrawing. I should be able to improve this substantially in the next release.

Closing this issue due to my explanation. If you think this issue is still not addressed with my answer, and needs further work, feel free to reopen and explain more.
