### ISSUE TITLE
Timeline Major Labels Background

### ISSUE THREAD

**Issue by PhilRicher** [almende/vis#3609]
Hi,

Let me start by saying that this project is pretty awesome.  It is so easy to use and the documentation is good.
I'm using the timeline project and styling weekends as in here **http://visjs.org/docs/timeline/#Styles:**

/* gray background in weekends, white text color */
  .vis-time-axis .vis-grid.vis-saturday,
  .vis-time-axis .vis-grid.vis-sunday {
    background: gray;
  }

But for I reason I can't figure out, sometimes, the gray shading is going up to the top.  So the monthname is also gray.  Is this a bug or do you know how to keep the gray only for the cells and the date number but not for the monthname?

Thank you.

**Comment by brichbe** [comment]
Not sure I'd call it a bug since it's a matter of desired style, but yeah, the cause does seem to be something peculiar about how the background grids are sized, where some of the divs are drawn the full timeline height but others aren't.

Since the month names are drawn on the foreground, you should try customizing the "vis-text vis-major" style by setting its background color to match the background color of your non-weekend grids.  If you get that working, please post your solution for others to use.

**Comment by PhilRicher** [comment]
Thank you for pointing me in the right direction.

I have tried a couple of css tweaks.  I finally got my month names background colored as I wanted with this rule:

  #visualization > div > div.vis-panel.vis-top > div > div.vis-text.vis-major.vis-day1 {
            background-color: white;
        }

This way, January, April, July and October are shown on a white background for every years.

Thanks.


Phil Richer

**Comment by PhilRicher** [comment]
Good enough.
