### ISSUE TITLE
Items in the duplicate timeline (with 1px width)

### ISSUE THREAD

**Issue by didiazo14** [almende/vis#3619]
<a href="http://es.tinypic.com?ref=mrx085" target="_blank"><img src="http://i64.tinypic.com/mrx085.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

Good Morning.

As you can see in the screenshot, I have the following problem.

I am developing a platform for a company in the agronomy sector, which shows sectors of irrigated fields. Until now I have no problem, the problem is that the irrigation sectors are repeated but with a width of 1px.

I hope you can help me with my problem.

**Comment by yotamberk** [comment]
What would you expect the behavior to be? Can you explain the problem?

**Comment by katjasmin** [comment]
You should check the start and end dates for these particular irrigation sectors. There might be an syntax error or maybe an error in the data itself. The same thing happened to me once, when a group of items had start dates that were bigger than their actual end dates due to a typing error. In this case visJs draws the item, but the width always remains 1 px. 

Another scenario might be, that the difference between the start and end date is so small (on that scale I would guess less than an hour) that you have to zoom in to see the actual item size.

**Comment by yotamberk** [comment]
@katjasmin is right.
It doesn't seem like a vis problem
