### ISSUE TITLE
Timeline is scrolling to the top on setItems

### ISSUE THREAD

**Issue by mkmieciak** [almende/vis#3628]
Hi! I have issue with timeline redrawing on items update. I'm getting new items from API, then i'm running setItems function, on data load whole timeline is scrolling to the top. How can i update items without this behaviour?

**Comment by brichbe** [comment]
Most of the [examples](http://visjs.org/timeline_examples.html) make use of the [DataSet](http://visjs.org/docs/data/dataset.html), which provides [methods](http://visjs.org/docs/data/dataset.html#Methods) for you to add/update/remove one or more items within that DataSet.  You should try adapting your code to use that instead of calling Timeline.setItems() whenever a subset of your data changes.  

I'm not certain if that will fix your scroll-to-top issue, because that behavior may be dependent on how many items you're updating each time, how many groups you have, how much height your timeline has relative to the items being displayed, whether you're using stacking, etc., but you should try using the DataSet first to see if that helps.

**Comment by mkmieciak** [comment]
Ok, thanks! I will let you know is it work :)

**Comment by mkmieciak** [comment]
That was the issue. Thanks for help! :)
