### ISSUE TITLE
nodes fontfill suggestions

### ISSUE THREAD

**Issue by dponch** [almende/vis#365]
Hi all,

I have a couple of suggestions for the new propertie of the nodes fontfill. Hope them help :)
1) The top of the letters are out of the coloured area
![outfontfill](https://cloud.githubusercontent.com/assets/2233165/4524902/30661e40-4d4b-11e4-934c-b98bbbf96e08.png)
2) It would be nice that the edges finish on the label instead of finising on the nodes, to not loose the arrow
![edgenofontfill](https://cloud.githubusercontent.com/assets/2233165/4524912/5d47113a-4d4b-11e4-86d9-550843fc350a.png)
![edgefontfill](https://cloud.githubusercontent.com/assets/2233165/4524915/60a51d36-4d4b-11e4-91a0-05910a2c9518.png)

Thanks,
Guillermo

**Comment by AlexDM0** [comment]
Hi,

I have pushed an improvement to the develop branch. The issue is that there is no specific function that can give us the exact height of the text, nor where it will start. This is browser dependent.. and I'd rather not make exception cases on all browsers and versions.

It should be only a pixel or two difference now, which is the best can can cleanly do at the moment.

Regards,

Alex
