### ISSUE TITLE
Timeline:  Hiding items filtered with get from Dataset not possible  (=>Not of type item) 

### ISSUE THREAD

**Issue by Siedlerchr** [almende/vis#3677]
First of all thanks for the great library! It's awesome.

I want to dynamically hide and show items which match a certain criteria. The problem is that I get a TypeError: x.hide is not a function.  When debugging the content of the Array from get, I see that it is only of type object and not (what I expected) of type item.
Is there any other way to achieve this?

```js
let items = new DataSet();
items.add({
    id: 'Test',
    content: "test",
    start: moment().format()

});


let itemsInRange = items.get({
    filter: item => (
        item.id.startsWith("Test")
    )
});
console.log("Hide Items", itemsinRange);
itemsinRange.forEach(x => x.hide()); 

```

**Comment by brichbe** [comment]
Looks like you're on the right track in the way you're using a `DataSet` to contain all your items, and then you're using the `DataSet.get()` method with a `filter` as the way to figure out which of those items to display.

I wonder where you got the idea that hide() was a method you could call on an item because that's not mentioned anywhere in the docs; but anyhow, there are [Timeline methods](http://visjs.org/docs/timeline/#Methods) you can invoke to give the same effect, in particular notice `setItems()`.  Setup your filter to return only those items you want to display (instead of the ones you want to hide), then call `Timeline.setItems()` passing in the array of filtered items.

**Comment by Siedlerchr** [comment]
I used the timeline.setItems() approach with the [sequency library](https://github.com/winterbe/sequency), which allows me to easily chain filters:
```js
import {asSequence} from 'sequency';
import {DataSet, Timeline} from "vis";

let items = new DataSet();

function hideItems()
{
    let  allItemIds = items.getIds();

    let temp = asSequence(allItemIds);
    //custom criteria
   if(condition1)
      temp = temp.filter(it => !it.startsWith("Test"));
   if(condition2)
     temp = temp.filter(it => !it.startsWith("ABC"));

    temp = temp.map(it => items.get(it)).toArray();
    timeline.setItems(temp)

}


```
