### ISSUE TITLE
Background items color

### ISSUE THREAD

**Issue by ssvelta** [almende/vis#3773]
Hi all,

We want to draw support stuff working days and times, weekends, holidays, etc. as background items. The rest (white parts) will indicate, when are people at work.

There are some background items that partially overlap another background item. They have the same css class (definition of background-color), but in the case of overlaping, each item has own color. Where is it controlled/defined? Is it possible to set 1 color for all background items?

![timeline](https://user-images.githubusercontent.com/26813590/35045460-cd532f58-fb8b-11e7-92f5-c21d184c91a9.JPG)

We are on vis.js Timeline version 4.16.1
Thanks for your help.
s.

**Comment by katjasmin** [comment]
If you want to use the same background color on all background items you could use the same style class for all items, when defining them. 
The reason, why colors overlap is due to the transparency of the background color. You can always set the transparency value to 1 for your background items. The disadvantage of this solution is, that you can't see the lines behind the background items anymore.

**Comment by ssvelta** [comment]
great hint, I have found this css class
```
.vis-item.vis-background.weekend {
                background-color: rgba(200, 200, 200, 0.2);
                z-index: -1;
            }
```

I have set background color to
`background-color: rgba(242, 242, 242, 1);`

Now it looks exactly as I wanted
![timeline](https://user-images.githubusercontent.com/26813590/35048136-206be6fa-fb94-11e7-999c-1a69a198e945.JPG)

Thanks for your help.
s.
