### ISSUE TITLE
Possible to plot Timeline and Graph on top of each other?

### ISSUE THREAD

**Issue by DanTulovsky** [almende/vis#385]
Hi.

Is it possible to plot Timeline and Graph on top of each other?  If I specify the same container, then the graph ends up under the timeline. I'd like both to be plotted on top of each other.

Thank you
Dan

**Comment by AlexDM0** [comment]
Hi Spencer, 

You can change the width with the dataAxis.width option. I know you know this because there is the other issue on this but for completeness, I wanted to put it here as well. 

@jarekpelczynski The issue with the width as reported by Spencer (#510) has been solved and is awaiting release. With that, the method I mentioned above should work for you.

Regards,

Alex

**Comment by bhspencer** [comment]
Hi Alex

I didn't mean to express any unhappiness with my above comment. I just wanted to point out one of the challenges of stacking a Graph2d on top of Timeline. You are quite correct, you can set the dataAxis.width option and this is really a minWidth. As you zoom in and out of the Graph2d the width of the data axis may increase to fit the labels. When it does it will nolonger line up with the timeline. A such I believe setting dataAxis.width alone is insufficient if you want to keep the Graph2d and Timeline aligned. I found that setting dataAxis.format.left.decimals helps keep the width more constant but I still find that it is necessary to  "watch" for a change in the width and adjust the position of the Timeline underneath in some circumstances.

Ben

**Comment by AlexDM0** [comment]
Hi Ben,

I agree that this solution is not optimal, however, as it stands now, this is the only way to do what jarek wants. Since this is a workaround, I don't plan on improving the options to suit this. In the future, we want a closer integration of the timeline and the graph2d, which would allow behaviour like this out of the box.

I didn't mean to imply you were negative about any of this, apologies for that.

Regards,

Alex
