### ISSUE TITLE
Feature: Support for dynamic or programmatic call of all option callbacks.

### ISSUE THREAD

**Issue by tatsujb** [almende/vis#3922]
This one I'm not sure if it's already possible or not but I'm led to believe it's not by an absence of mention in the docs  : 

I would like to add other calls to these timeline callbacks : 

```
  options = {
    snap: (date) => {return this.snap(date)},
    onAdd: (item, callback) => {callback(item)},
    onRemove: (item, callback) => {callback(item)},
    onUpdate: (item, callback) => {callback(item)},
    onMoving: (item, callback) => {callback(item)},
    onMove: (item, callback) => {callback(item)},
    onInitialDrawComplete: () => {}
  }
```
For Example :
as it stands `onMoving` in this code will execute every time an 'x pixel' passes by your cursor while click and dragging an item but what if I want to call this exact method and exactly in the way that it is currently called at a random time, say when I click on a special button exterior to the timeline?

What if I want to execute vis-timeline's 'onUpdate' everytime `onAdd` is called?

     this.timeline.onUpdate(item);

does not work.

The simplest and most common use case : 

My app has a vis timeline that is always initialized with item X and item Y. It also hosts a "delete X and Y button" above the vis timeline. 

How would I go about deleting items X and Y upon that button click?

to me I would need to not be denied access to `onRemove` as currently is the case.

**Comment by tatsujb** [comment]
@brichbe why doesn't updating groups work (entirely)?

```
const th = this;
      this.groups.forEach(function(group) {
        th.groups.update({
            id: group.id,
            visible: true,
            showNested: true
        });
      });
```
do effectively change the showNested and visible value but it doesn't unfold.

my options : 
```
options = {
    editable: {
      add: true,
      updateTime: true,
      updateGroup: true,
      remove: true,
      overrideItems: false,
    },
    itemsAlwaysDraggable: {
      item: true,
      range: false,
    },
    multiselect: true,
    multiselectPerGroup: true,
    groupOrder: 'content',
    groupEditable: true,
}
```

**Comment by brichbe** [comment]
Sorry, it's really difficult to help debug issues without a working Jsbin to look at. Can you provide a working example that demonstrates the issue you're having?

Also, in response to what you said above:  

> The applications for my idea are limitless though, I think I'll leave this suggestion up.

VisJs has been awesome and helpful for many people, but you've probably noticed recently that not much development has been happening. Unfortunately it seems the core maintainers haven't had much time to work on this project. I'm not saying that in a negative way, it's just the reality that most people (myself included) are too busy doing other things to devote development time to projects like this too.

So, tickets like this one have been piling up a bit lately. Many of them are relevant and should remain open until someone has the time to develop the correct fix. However, tickets like this one, which are suggestions to change the design (for reasons that are frankly unnecessary because you can, and should, do this using the DataSet), well, a ticket like this just adds to the mountain of all the open tickets. I think it would help this community if we all strive to close old/stale/unnecessary tickets so maintainers that have development time to devote can focus on the important ones that actually need attention.

**Comment by brichbe** [comment]
Interesting ideas @tatsujb Are you still planning to use VisJs in your project? Have you made enough progress that you'd be willing to share what you're building?

**Comment by tatsujb** [comment]
what do you mean? no I'm not building a re-work of timeline js, I've finished my implementation for an airbus project but I'm not at liberty to share the sum of my code (but I have shared bits and pieces here).

However I am toying with the idea of making a rework yes, and if I did it would of course be open source and on github.
