### ISSUE TITLE
How can I change the node image by node id in Network module?

### ISSUE THREAD

**Issue by shuaijunlan** [almende/vis#3932]
I use the latest version of visjs, I create a network topology by `Network module`, and now I want to change the node image by node id, but I can't find any function interfaces in the document.

**Comment by jfosnight** [comment]
I just had the same problem today trying to figure out how to update a label after the network has been drawn.  It turned out to be relatively easy.

Assuming that you are using `new vis.DataSet(data)` to initialize your data, you can use the methods provided by the DataSet library http://visjs.org/docs/data/dataset.html.  What you are looking for is probably the `update()` function.

Example:
```javascript
let nodes = new vis.DataSet([
  {id: "1", label: "Node 1"},
  {id: "2", label: "Node 2"},
]);

// Now we can manipulate the data with the provided DataSet functions
nodes.update({id: "1", label: "New Label");
```

Well that's about all I know.  Hope this helps.
