### ISSUE TITLE
Tooltip delay on hover

### ISSUE THREAD

**Issue by jknapp25** [almende/vis#4077]
When I configure Tippy.js it has a delay option that allows you to set a certain amount of time the user has to have stalled their cursor on a button til the tooltip appears. Can this same thing be implemented in Vis?

The timeline I created has hundreds of different items, so when a users mouse goes over the items to the other side of the screen, it shows a bunch of tooltips that the user doesn't want to see. This looks a bit unprofessional in-front of a large room of people.

**Comment by yotamberk** [comment]
I've now branched out to a new fork of my own including only Timeline.
https://github.com/yotamberk/timeline-plus
https://www.npmjs.com/package/timeline-plus
I maintain it weekly and new versions are up with fixes.
Please resubmit this issue there and I will try to address it in-depth.

**Comment by kadamska** [comment]
Since Vis is using `visibility` to show/hide a tooltip, you can add a css transition with a delay:
```
div.vis-tooltip {
   transition: visibility 0s ease 0.75s;
   -webkit-transition: visibility 0s ease 0.75s;
}
```
I wanted to apply the delay only for showing, and hide the tooltip immediately, so I implemented `itemOverHandler` and `itemOutHandler` where I add/remove a custom css class with the delayed transition.

**Comment by daRoof** [comment]
I created pull request #4238 that should fix this issue.
