### ISSUE TITLE
Color weekends in timeline

### ISSUE THREAD

**Issue by fionasanoif** [almende/vis#412]
First of all thank you for an amazing library. We have been using it without having any issues, but recently we got the requirement to color the weekends in the timeline. We started it by using the option of coloring the background areas, and it works for a specific time, but we need to color the weekend from now to 31.12.9999, this is decreasing the performance of our application. 
Is there a way that the weekends are colored in the same time when the timeline is created?
I would appreciate if you can at least give me some hints?

Thanks in advance

**Comment by fionasanoif** [comment]
Hi Alex,

I just added the weekend background coloring, and it works perfectly. But I just had a question, the weekend coloring appears only once you zoom in deep. Is it possible to show the colored weekends also when the timeline is zoomed out?

Regards,
Fiona

**Comment by AlexDM0** [comment]
Hi Fiona, 

Not really. The background coloring is based on the resolution of the timestaps since the css classes are defined per step. If the step becomes too large (say in integer weeks), the weekend class does not exist.

On the other hand, I'm still confused why you don't just use repeating events with backgrounds. There should be a threshold where you zoom out so far that a weekend band will be less than 1 pixel wide, if you zoom out further you don't need to show it because it cannot be shown. It would really help if you could show a jsbin with what you want to do to see if we can come up with an optimal solution.

Regards,

Alex
