### ISSUE TITLE
Hide groups with no visible items

### ISSUE THREAD

**Issue by joemeszaros** [almende/vis#415]
Hi there,

I am looking for an option in timeline to hide groups with no visible items. If you look at the frist group demo (http://visjs.org/examples/timeline/05_groups.html) and move + zoom the timeline to show only _item 7_, all groups remain visible despite group _Alston_ and _Lee_ has no visible items.  Here is a screenshot :

![groups](https://cloud.githubusercontent.com/assets/1064211/4841829/ef400412-601e-11e4-81e7-a6328c0b5405.png)

It would be wonderful to autohide these groups because in my application I have several groups and they fill the screen however only a single item is visible in most of the cases.

**Comment by blackberry464** [comment]
Hi Jos,
Did you ever get around to implementing the <code>visible</code> property?

**Comment by josdejong** [comment]
@blackberry464 this is still on the to-do list.

**Comment by tsnolan23** [comment]
Any update on this? This feature would be huge for us as well!

**Comment by josdejong** [comment]
still on the to-do list. Feel free to contribute... ;)

**Comment by oinkspoink** [comment]
The idea of this feature is really good. I created a workaround in combination with rangechange or rangechanged event and DataView. The idea was to filter the items based on the range to determine the visible groups.

```javascript

var itemsView = new vis.DataView(items, { filter: 
	function(data) { 
        if (!range || (range.start < data.end && data.start < range.end)) {
   			if ($.inArray(data.group, visibleGroups) == -1) {
        		visibleGroups.push(data.group);
       		}
        	return true;
   		}
   		return false; 
    }
});

var groupsView = new vis.DataView(groups, { filter: 
	function(data) {
        return $.inArray(data.id, visibleGroups) > -1;
    }
});

```

Basic example: http://jsfiddle.net/zwwspLnz/

If you use rangechange, the horizontal navigation gets really sloppy with many groups/items because the event fires every minor step (even noticable in the fiddle with 20 groups). You should make sure to refresh the data just every 20-30 calls or more.

**Comment by yotamberk** [comment]
using  #2315 this issue is solved with filtering groups that are not visible
