### ISSUE TITLE
is this project dead ?

### ISSUE THREAD

**Issue by codenoid** [almende/vis#4184]

**Comment by javdome** [comment]
I think that, currently, nobody is in charge of the project. We will see if in the future new main collaborators will manage it again.
However, if you are interested in the Timeline module, its main contributor has forked the project and isolated this part in order to improve it. You can find it in:
https://github.com/yotamberk/timeline-plus

See you

**Comment by mojoaxel** [comment]
see https://github.com/almende/vis/blob/develop/misc/we_need_help.md
