### ISSUE TITLE
[Timeline] Feature request: stack ranges only when their time intersects

### ISSUE THREAD

**Issue by elricelf** [almende/vis#4185]
Simple example: got 2 ranges, 00:00-01:00 and 01:05-02:00. In a close zoom they don't stack, but when zooming out at some point they will stack one on top of another. Would be great to make it possible to represent ranges stacked only when their timings intersect, regardless of zoom level.
![timeline](https://user-images.githubusercontent.com/41512261/48056697-04c5b580-e1bb-11e8-9f51-f9f385ce2f89.gif)

P.S. Changing margin.item.horizontal is not an option

**Comment by javdome** [comment]
Hi!!
The next option in the Timeline configuration will fix it:
`margin: { item: { horizontal: -1 } }`

Besides, if you are interested in the Timeline module, its main contributor has forked the project and isolated this part in order to improve it. You can find it in:
https://github.com/yotamberk/timeline-plus

See you

**Comment by elricelf** [comment]
Hi javdome! 
Thanks for your reply, it works brilliant! And one more thank for a link, glad to see this awesome module continue to evolve.
