### ISSUE TITLE
Meteor / Atmosphere support?

### ISSUE THREAD

**Issue by dandv** [almende/vis#446]
This would be the best graph library for Meteor, and I've [mentioned its absence to the Meteor community](https://github.com/meteor/meteor/issues/3107#issuecomment-63235211).

Packaging for Meteor is quite simple if the original author wants to add support - http://www.meteorpedia.com/read/Packaging_existing_Libraries

**Comment by mcoenca** [comment]
Any news on this one ? :)

**Comment by AlexDM0** [comment]
We don't plan to pick this up ourselves, but if you want to take a look at it, we're happy to accept pull requests as Jos has stated.

Regards

**Comment by vflyson** [comment]
There're a few unofficial packages on atmosphere (you can search for "vis" and find them easily) but they are outdated by at least 6 months.
The reason why is because Meteor is fully integrated with node packages and you can do `meteor npm install vis --save` and then include the library into the front-end space with `import vis from 'vis';` ("ecmascript" package required for "import" to work).
If you're still using the legacy Meteor package structure, then add
```
Npm.depends({
  "vis": "4.16.1"
});
```
into your package.js file along with 
```
api.use('ecmascript', 'client');
```
and
```
api.export('vis', 'client');
```
If global usage is needed be.

The CSS will be missing after you `import vis from 'vis';` so don't forget to
```
api.addFiles('.npm/package/node_modules/vis/dist/vis.min.css', 'client');
```

Better stay away from package.js and go with package.json and just rely on NPM as much as you can, that's my advice.

**Comment by mojoaxel** [comment]
I think @vflyson has described the situation perfectly! Thanks.
