### ISSUE TITLE
Impossible to delete properties on objects within a DataSet

### ISSUE THREAD

**Issue by gossi** [almende/vis#494]
Hey,

in my dataset, I'm using for a network, I set the group when an event happens and want to delete the group when another event happens. It turns out, this is impossible, because `DataSet.update()` merges instead of overwrites. So basically, it is impossible to remove once set properties of an object within a dataset.

Would love a fix for this.

**Comment by AlexDM0** [comment]
Hi,

@Josdejong, because I think the default behaviour is in general better when not changing the dataset. It is the same for initiating a network without hierarchical layout. It would be strange if you had to add the stabilised listener by default. That said, there is room for improvement there. 

As for the state of this current issue, I was under the impression the network did what it was supposed to do except for the zooming. I'll take another look at this. 

Regards and happy new year!

Alex

**Comment by josdejong** [comment]
@AlexDM0 yes that makes sense. Maybe we can seek a solution where we create some overridable functions having the default behavior (in this case a `.zoomExtend()` when stabilized) which we can replace with our own behavior, instead of introducing new (relatively limited) options.

**Comment by AlexDM0** [comment]
Hi Gossi,

So what actually happens is the following: you can set the group to null but it did not revert back the the "default" settings. The reason is that the group entree only overwrites the colors once when loaded, the reference is not broken. Now this is something that we can look at but for now I have made sure the node DOES revert back to the default colors. An other easy fix is to make two groups: selected and unselected and just switch between those. You seem to be focusing on the "remove group" too much that you missed the obvious switching between two groups instead of between a group and no groups :).

The fix to revert back to default is now pushed to develop. This should solve all problems in this issue.

Regards,

Alex

**Comment by gossi** [comment]
Hey @AlexDM0 

just realized your answer. You are right, instead of switching groups, I was focussing on adding/removing those. I thankfully take your tip and create two groups that I'll be switching.

Thanks a lot
gossi

**Comment by AlexDM0** [comment]
Hi Gossi,

The change I made to 'reset' the group back to normal if it was assigned one before has introduced a secondary problem #561. The right way to do this is (as you mention) to assign it a second group. Just a heads up, I have reverted the commit for this issue.

Regards,

Alex

**Comment by natishere** [comment]
am still unclear re the original issue - how to remove a property from a dataset.
i can easily add a property to a dataset node:
dataset.update({id: '1', age: 23})
but how do I subsequently delete that property?
i tried updating with null and with undefined - didn't work.
thanks.

**Comment by AlexDM0** [comment]
Does dataset.remove not work?

**Comment by natishere** [comment]
i dont want to delete the whole dataset. I dont want to delete a whole node within a dataset.
i do want to delete a single property from a node inside a dataset.
given that specific and simple request how would I delete the 'age' property from node id 1 inside my nodes dataset?

**Comment by josdejong** [comment]
It makes sense to add a new method to the `DataSet` for removing specific properites of an item rather than an item as a whole). Or maybe we could extend the method `remove` to remove some specified fields. Mabye something like:

```js
// remove property age from item 1
dataset.remove(1, ['age']});
```
