### ISSUE TITLE
setwindow doesn't always, well, set ;)

### ISSUE THREAD

**Issue by jmls** [almende/vis#541]
I have a button the applies "max zoom" (meant to be to 1 minute).  this is function call that is uses:

```javascript
$scope.zoomMax = function() {
  		setTimeLine(moment().subtract(30,"seconds"),
  					moment().add(30,"seconds"));
  	}

  	function setTimeLine(startTime,endTime) {
  		$scope.timeline.setWindow({
            start: startTime.format(),
            end:   endTime.format()
        });

        console.log("start",startTime.format(),"window start",$scope.timeline.getWindow().start.valueOf())
        console.log("end",endTime.format(),"window end",$scope.timeline.getWindow().end.valueOf())

        $scope.timeline.redraw()
  	}
```

as you can see from the dev console , there are some problems
```html
#1
timelineController.js:152 start 2015-01-06T19:03:37+00:00 window start 1420569246886
timelineController.js:153 end 2015-01-06T19:04:37+00:00 window end 1420572846886

#2
timelineController.js:152 start 2015-01-06T19:03:51+00:00 window start 1420570620913
timelineController.js:153 end 2015-01-06T19:04:51+00:00 window end 1420571499361
````

so in this case I had to push the button twice ... @ 19:03 window start and end did not match the formatted strings. @ 19:04 they did

this is not consistent. sometimes I have to press the button 3 or 4 times before the error ocurrs

**Comment by AlexDM0** [comment]
Hi,

Could you provide a jsfiddle to show the problem? It would make it alot easier for us to solve.

Regards,

Alex

**Comment by josdejong** [comment]
Thanks, I can repeat this issue by just setting `{zoomMax: 1000 * 60}` and then running 

```js
timeline.setWindow(moment().subtract(30,"seconds"), moment().add(30,"seconds"), {animate:false});
```
(animate false to ensure it's not something related to animation)

@jmis note that in your code there is no need to call `$scope.timeline.redraw()`.

**Comment by josdejong** [comment]
hm, I think I misunderstood the issue. 

Isn't the problem here that `setWindow` starts an animation to move to the new start and end? The *final* start and end are not immediately applied as the Timeline moves to the final start/end via animation.

**Comment by bjcullinan** [comment]
I am having this issue too.  It seems when maxZoom is set the setWindow doesn't move unless the current zoom changes (from less than maxZoom).  But the expected behavior is that even if you are all the way zoomed out, and scrolled from a different time frame, it will scroll you back to the time frame set with setWindow.

**Comment by josdejong** [comment]
@bjcullinan do you have a jsbin demonstrating the issue? I don't get it repeated again...

**Comment by josdejong** [comment]
Ah, got the issue repeated again: http://jsbin.com/gonege/edit?html,output

**Comment by josdejong** [comment]
Found the issue, this was a funny one. Turns out `setWindow` refused to apply a new interval when larger than the configured `zoomMax`. 

In your example, the start and end where created separately based on the current time (`moment().subtract(30,"seconds"), moment().add(30,"seconds")`), sometimes resulting in the interval being *slightly* larger than the allowed 60 sec, as `end` is created a fraction of a second later than `start`.

**Comment by bjcullinan** [comment]
Yup, that sounds like it, thank you for looking! :)
