### ISSUE TITLE
Final call for submissions! Cool examples for the new vis website!

### ISSUE THREAD

**Issue by AlexDM0** [almende/vis#545]
Hi Everyone,

I'm in the process of finalizing the new vis.js website and I'd like to ask everyone if they have a cool example of things they have made using vis.js. If you made a classified project, maybe you can make a dummy with example content. 

Anything is welcome, a link to your project, a working visualization, an image with small description etc.
I'm looking for nice pictures with a description and credits that (could) link to a working setup. If you'd prefer we can host your example on our website.

I look forward to hearing from you all!

Regards,

Alex

EDIT: once the new website is live, we are always in search of nice showcase projects, feel free to let us know if you'd like to be featured in the future! 

There was a issue about this before (#244). Those will also be incorporated in the new website. Thanks to everyone who posted submissions there!

**Comment by AVermeij** [comment]
Hi Alex,

Not sure whether I mentioned this to you before, but I wrote a blog article a while back which includes a vis.js network visualization:

http://www.kenedict.com/connecting-startups-and-investors-in-mobile-technology/

Relatively straightforward usage of the lib, but might serve as a practical example :-)

**Comment by AlexDM0** [comment]
Hi Andre,

I have added your entree to the showcase. Thanks for reminding me!

Regards,

Alex

**Comment by felixhayashi** [comment]
Hi @AlexDM0,

sorry, I didn't notice this post three days ago. If you think it suits for your great vis.js library as a showcase, please do not hesitate to link [Tiddlymap](bit.ly/tiddlymap) as a demo site of how vis is integrated in tiddlywiki.

The site is actually hosted on github (proxy: http://bit.ly/tiddlymap) and contains several examples how the wiki user can quickly create graphs with the (extended) vis.js editor (hidden in the right sidebar) and then immediately reference the created graph ("view") by using wiki-markup. The graph-content can either be added manually or assembled automatically by tiddlywiki filters (e.g. *all articles that contain the tag "task" and where created at date X*).

The great thing is that the vis graphs are neatly embedded in the overall wiki content and can support the text at any place. Also, since vis allows click events on nodes, articles can comfortably opened from any graph, which helps the user in quickly jumping between topics. Thus, a graph-wiki-hybrid is created which makes it incredibly easy to integrate, link and visualize ideas and topics.

Regards
Felix

**Comment by AlexDM0** [comment]
Hi Felix, 

I've added you to the showcase, thanks for letting us know!

Regards,

Alex

**Comment by felixhayashi** [comment]
Hi Alex,

many thanks.

-Felix

**Comment by theMiddleBlue** [comment]
Hi,

i've created a Real Time log visualization Dashboard based on vis.js network. 
You can find my project here https://github.com/theMiddleBlue/RealTimeVis.js

hope this can be useful :)
bye!

-theMiddle

**Comment by AlexDM0** [comment]
Hi,

It looks very nice! We're very busy at the moment but if you'd be able to make a pull req to ghpages with an image for your setup well accept it asap!

Cheers

**Comment by theMiddleBlue** [comment]
Hi Alex,

thank you! i've just send a pull req with a screenshot (a network that show
all facebook post likes)

bye!

-theMiddle


2015-12-03 22:48 GMT+01:00 Alex <notifications@github.com>:

> Hi,
>
> It looks very nice! We're very busy at the moment but if you'd be able to
> make a pull req to ghpages with an image for your setup well accept it asap!
>
> Cheers
>
> > On 03 Dec 2015, at 16:54, theMiddle <notifications@github.com> wrote:
> >
> > Hi,
> >
> > i've created a Real Time log visualization Dashboard based on vis.js
> network.
> > You can find my project here
> https://github.com/theMiddleBlue/RealTimeVis.js
> >
> > hope this can be useful :)
> > bye!
> >
> > -theMiddle
> >
> > —
> > Reply to this email directly or view it on GitHub.
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/almende/vis/issues/545#issuecomment-161794691>.
>



-- 
--
Andrea Menin
menin.andrea@gmail.com
skypeme @ und3rmenin

**Comment by AlexDM0** [comment]
Hi,

Im afraid I cannot merge gh-pages into master. You'd need to fork vis, change the gh-pages so it contains your addition, then do a pull request into the gh-pages branch of vis.

Regards
