### ISSUE TITLE
Getting edge data of a network graph

### ISSUE THREAD

**Issue by mindware** [almende/vis#551]
Hi there. 

I have a question and a problem.

The question: 
Why are edges given an internal visjs id in the form of a long string instead of a sequential numerical id?  

My problem: 
I have no O(1) way to access the meta-data associated with an edge (such as its title, value, etc),  simply by using its id corresponding to an index, but instead have to iterate through the entire data array to find a matching edge and access its meta data. 

The long version: 
I'm interested in retrieving the titles of edges that are selected on a network graph. I'm using network.on('select'... function in order to get information from edges that have been selected (available through get properties.edges array). I get a list of edges that have been selected, but with visjs assigned ids. 

It seems nodes can have a sequential id, but edges get their own visjs assigned ids (something similar to "abcqje-12kjreiq-123kjk"). When one checks the array of properties.edges, only the visjs id is present. 

 I'd like to know  what's the proper way to access selected edge's meta-data like title, values, etc programmatically.

In my case, nodes can be easily accessed by their id in the data array (an O(1)). Edges, however, with their odd id do not appear to be easily accessible and appear to require iteration. Is this by design? am I missing something?

**Comment by AlexDM0** [comment]
Hi,

To answer your question, ids are generated for edges as a convenience. It is perfectly fine to supply your own ids to edges.

I have a few question for you in order to fully understand the problem. 
- are you using the vis DataSet?
- how are you accessing the nodes O(1)? The default format is an array, not JSON. Do I understand that you're matching your ids to the index?
- could you make a jsbin showing us what you are doing?

There are examples on our website how to use a dataset to do this (neighbour highlighting for example). The similar principle is true for edges. 

Regards,

Alex

**Comment by mindware** [comment]
Thanks for the response. 

In regards to your question: 

* I'm not using DataSet.
* I get the node id via a listener. I'm doing something similar to the following:

```
network.on('select', function (properties) {
      // if nodes were clicked:
        if(properties.nodes.length > 0 ) {
            node_selected = true;
            id = parseInt(properties.nodes.toString());
            value = result["graph_nodes"][id]["label"];
```
The result array is the nodes array I originally used to create the data hash that I feed to create the graph.  

I tried repeatedly setting the id of an edge but it would always use the internally generated one, unlike the nodes. 

I'll look into posting the js. Any insight is much appreciated.

**Comment by AlexDM0** [comment]
http://jsbin.com/dagexisuxe/3/edit?html,output

I'm not sure what the problem is. You should NOT use the id as an array index. It's very prone to bugs and they're hard to find. If you want O(1), make a JSON copy of the data using the id as the key.

You can use the DataSet if you have dynamic data, and get the JSON copy from it like so: 

```
var edgesDataset = null;

  // create an array with edges
  var edges = [
    {id: 1, from: 1, to: 2},
    {id: 2, from: 1, to: 3},
    {id: 3, from: 2, to: 4},
    {id: 4, from: 2, to: 5}
  ];

  var edgesDataset = new vis.DataSet(edges);
  console.log(edgesDataset.get({returnType:'Object'}));
```

You can also use edgesDataset.get(3) to get a specific entree. (id:3 in this case).

This should be enough information for you to solve this. If there's anything else, let me know.

Regards,

Alex
