### ISSUE TITLE
Is there a way to size the node dynamically based on the number of connected nodes?

### ISSUE THREAD

**Issue by netigen** [almende/vis#553]
Is there a way to size the node dynamically based on the number of connected nodes?

Tried to find an examples on http://visjs.org/, but could not find a dynamic example. Can this only be done server side? I was hoping that there is a way to do so in the JS.

Thanks for your help.

**Comment by AlexDM0** [comment]
Hi,

You can use the DataSet to dynamically update your data. 

I have altered our size example here: http://jsbin.com/rovasiramu/2/edit?html,output

This illustrates two methods: using the value system or setting the radius. To use this example, first click on the resize by value, then click on the resize by radius. To repeat refresh the page. This is because the way I set this particular example up, you can use the ideas to make it work for you.

Regards,

Alex
