### ISSUE TITLE
Hover edges

### ISSUE THREAD

**Issue by Kacius** [almende/vis#602]
Hi,

There is a great function that allow to listen nodes when hover : 

network.on('hoverNode', function () {
  doSomething();
});
network.on('blurNode', function () {
  doSomething();
});

Is there any way to do the same thing with edges ? (Listen edges hover)

Thanks,

Kacius.

**Comment by AlexDM0** [comment]
Hi Kacius,

This is not currently possible but I'll add this as a feature request.

Regards,

Alex

**Comment by Kacius** [comment]
Thank you!

Kacius

**Comment by AlexDM0** [comment]
Hi Kacius, 

I have added your request to the list. 

http://visjs.org/featureRequests.html

Regards

**Comment by stanleyxu2005** [comment]
It seem to be on the todo list but the status is "closed" here. Do you mean "closed" "accepted" or "closed" "rejected"?

**Comment by AlexDM0** [comment]
Hi Stanley,

Since at a point more then half our issues were feature requests, we decided to move feature requests to the website and close the issue.

Here is more information on it:

http://visjs.org/blog.html#New\ website\ for\ vis\.js\!

Basically, it means we put it on as a feature request and we cannot give a timeframe on when this will be added. Anyone wanting to contribute can use this list to add something that is requested. We often look at this list to see what we shall add or which areas to expand upon. If they are marked in blue it means we're taking this one up ourselves (actively).

Regards,

Alex

**Comment by gdejong** [comment]
As of version 4.4.0 (2015-07-03) this functionality is available. See https://github.com/almende/vis/blob/master/examples/network/events/interactionEvents.html for an example. The feature request should be removed from the list on http://visjs.org/featureRequests.html
