### ISSUE TITLE
How does user initiate the graph edge connect?

### ISSUE THREAD

**Issue by valtih1978** [almende/vis#605]
Your [built-in editor](http://almende.github.io/vis/examples/network/21_data_manipulation.html) supports some connection of nodes. I would like to create my own instead. I would like to have the connectEdges button always on top or initiate the connection when node selected with Shift key or right mouse button, which is more agile than your bulky editor. How can I initiate the new edge draw?

I also do not understand why do you deny the edit (del key) while manipulatorBar is invisible, eventhough `options.dataManipulation.enabled` and `network.editMode` = true. I have heard that tying model with graphical controls is a bad practice.

**Comment by valtih1978** [comment]
Well, I think that I can hide standard controls with css styling yet use onclick functioins to enter the edge edit mode. Yet, since I [am going to use control+clicks](https://github.com/almende/vis/issues/605#issue-55793606) for that, it might still be easier to call these functions directly from inside the vis.js.

**Comment by josdejong** [comment]
@valtih1978 please be careful with your language. You sound quite offensive. Please comment in a more constructive way like you are looking for a *different* solution rather than a *superior* solution. Or share your ideas to improve the current solution in a *constructive* way.

**Comment by AlexDM0** [comment]
I deny the del key specificially when the manipulation bar is hidden because when it is hidden people are not in edit mode, regardless if you flip the boolean. Everything is neatly bound and unbound when you press the edit button and the hide button. The gui part is handled seperately from the vis functions.

At the moment we do not support the functionality to be bound to custom triggers. This will change in the future as we want to modularize the code more and more. You can look in the code to see which internal functions you need to call to get everything to work but I can't recommend it since the clean up functions might expect different circumstances. 

You can bind it to whatever you want. Luckily the control click is not used for anything else at the moment...

**Comment by valtih1978** [comment]
I have realized that I can enter edit mode by `network.manipulationDOM['addEdgeSpan'].onclick()` looking at your key code

```javascript
      this.manipulationDOM['addEdgeSpan'].onclick = this._createAddEdgeToolbar.bind(this);
```
The problem was that I could not call _createAddEdgeToolbar directly. This is what I meant by `bindig`. `Network._createAddEdgeToolbar` was failing. I was not sure that method is decalred for network and that _prefix assumed that it is not publically available, as opposed to click. Later, I have gained some script experience to learn that 

```javascript
network._createAddEdgeToolbar .call(network) // to enter the edge edit mode
```
does the trick and comprehended the meaning of ubiquitous bind everywhere in your lib. It tells what would be `this` inside the method, when I call it. Thank you for [resolving the issue after closing it](https://github.com/almende/vis/issues/712).
