### ISSUE TITLE
Support for timeline floating range

### ISSUE THREAD

**Issue by bbseven** [almende/vis#614]
Previous versions of the timeline had the concept of a floating range, where an end date didn't need to be specified for events that never ended. Is this feature available in visjs, and if not, and plans to add it?

Here is an example from the previous version:
http://almende.github.io/chap-links-library/js/timeline/examples/example30_floatingRange.html

Thanks for building this great timeline library!

**Comment by AlexDM0** [comment]
Hi BB,

This is not available out of the box, but you can quite easily implement this yourself by listening to the rangeChanged (or rangeChange, but that's more cpu intensive) event and manually setting the start or end range to a new value.

That is also what the old library seems to be doing :). Because we try to stimulate easy extensions of vis without adding more and more options, I don't think this feature will be added out of the box.

Regards,

Alex

**Comment by josdejong** [comment]
Would be nice to create a separate `FloatingRange` item type for this. 

There may be a few tricky things there: the Timeline assumes the width of an item does not change unless you zoom in/out, so in case of floating ranges the Timeline should be triggered with every redraw to redo the stacking and updating the size of items.

**Comment by bbseven** [comment]
Thanks. I was able to solve this a more elegant way specific to my application. I wouldn't add it unless a lot of people ask for it, especially since it can be solved fairly easily.

**Comment by josdejong** [comment]
Ok thanks for your feedback!
