### ISSUE TITLE
Very slow draw performance when rendering networks with 100+ images

### ISSUE THREAD

**Issue by andymc33** [almende/vis#633]
Whilst it's arguably nice to see the images "pop up" one by one on loading, redrawing the graph on each onLoad event is incredibly cpu intensive.

The following patch saved 30 secs of 100% cpu for me:

LINE 15664
    this.imageLoadCount = 0;
    this.images.setOnloadCallback(function (status) {
        network.imageLoadCount++;
        if (network.imageLoadCount == network.nodeIndices.length)
        network._redraw();
    });

**Comment by AlexDM0** [comment]
Hi,

We've never run into this because we've never used that many pictures. The problem with this approach is that is implies that all nodes are pictures. If only one of them is not, this will not redraw. 

I think the best way to do this is to just schedule a redraw instead of doing one. I'll see if I can take this and put it into vis.

Cheers!

**Comment by andymc33** [comment]
Ah good point - am not surprised - I'm using Phantom.js to stabilise server side which is the only reason I am getting some nice 300+ node image networks rendered quickly in the browser.

Your recent stabilizationIterationsDone change will be incredibly useful for me in deciding when to terminate phantom instances - thanks!

**Comment by AlexDM0** [comment]
Hi, 

I know what you mean :) I needed it to precalc 200 networks with 2000 nodes and 40000 edges (max) automatically for 15000 iterations, then freeze the physics and toggle a download :)

Cheers

**Comment by AlexDM0** [comment]
Hi, 

This has been resolved in v4, the requestRedraw does not stack up, there by solving this issue.

Regards,

Alex
