### ISSUE TITLE
Question: Network with popovers

### ISSUE THREAD

**Issue by austimkelly** [almende/vis#663]
Hi - I'm a noob to vis.js and not skilled with .js dev (I'm a native apps developer). I'm trying figure out how to show a popover control from the location of a clicked node. I got as far as showing a jquery dialog, but not able to really figure out the best way to show interactive html in response to user-interaction with nodes. Here's some sample I'm trying:

http://jsfiddle.net/austim/1bjeattn/2/

I also tried the route of putting in raw html into nodes that might have a class event but didn't have luck there either.

Can you recommend the best approach that might make this feasible?

Thank for the great vis framework!

**Comment by AlexDM0** [comment]
Hi Tim,

Apart from some JS inconsistencies, what's wrong with your current example? Could you clarify what it is you want? Do you want the popup to appear over the node? What data of the node do you want to show?

The network is drawn in canvas, that means it does not support html in nodes (without the svg workaround in our examples but I'd recommend you just don't do it). 

As for some JS tips: 

The selection is an array. Your check should be for selection.length > 0. 

You assume the nodeId you get from the event is the same as the INDEX of your data array. This is not necessarily true and prone to bugs. 

You don't need to pass the nodes var due to scoping. 

There is no point key in the properties object as you can see in the log. Look into the JSON data format to better understand what you get from the event. 

Use console.log for logging, that way you don't have to typecast everything to string. Open the developer console of your browser to see the logs and possible errors. 

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi Tim,

Is this still an issue?

Regards,

Alex
