### ISSUE TITLE
Multiple DataViews as groups in Graph2d

### ISSUE THREAD

**Issue by spatialillusions** [almende/vis#687]
Hi, 

Would it be possible to add different DataViews as groups in Graph2d, so that instead of having a group id in your DataSet, you could create a DataView for each group and then have them treated as separate groups automatically. 

Let me give you an example:
Say that you have a DataSet with your processor load over time, and you want to display it as green bars when you are below 90% and as red bars when over 90%.

Or would it be possible to add fields to a DataView, so that you could tag your different views with different group id, and then some way merge several DataViews into one virtual DataSet that would be the content of your Graph2d.

/Måns

**Comment by spatialillusions** [comment]
Hi, 

I looked into the code, and realised that it is the items that points to the groups and not groups that queries for items. I guess there is a good reason for why it is this way. But wouldn't it be really nice if every group was represented by a data view, and you could define the filter function in your group definition? 
This way you could add your data once, just a bunch of data without group definitions, and then for each group you added you would just add the DataView options to your group definition. Something like:
```javascript
groups.add({
    id: 1,
    content: 'High Load',
    dataView: {
        filter: function (item) {
            return (item.y > 90);
        }
    }
    // Optional: a field 'visible'
    // Optional: a field 'className'
    // Optional: options
  })
```

**Comment by spatialillusions** [comment]
I have been looking through the code for a workaround without having to do to much code rewriting, and I have a suggestion. How about being able to temporarily change the group id on items, and the possibility to have multiple filters on a DataView?

My idea is as follows:
- On data selection options add a property called id, in the same way we have an id on groups when we add them. When you add the id value on a data selection query the returned items will have group:options.id. (This can be done in a way that doesn't effect the original data.
- On DataView creation add the possibility to have an Array of options.

This would make it possible to create DataView that can create several graphs in a Graph2d. 

If I'm right I can make this possible without writing a lot of code, but before I start coding I would like to know if you would be interested in something like this, or if I would mess up your idea of how DataViews should work to much?

**Comment by AlexDM0** [comment]
Hi,

There are some inherent problems with the current setup of graph2d. There are usually multiple ways to solve a problem. Let's take a look at your example, higher than 90% red, otherwise green. 

You have two groups, red and green. Each datapoint needs to be added. When adding, just check the value and allocate the group. I assume you prefer to dynamically style the points? Usually I prefer to preprocess the data to suit my needs but then again that may not always be feasible. Do you have a case where this is not feasible?

> This way you could add your data once, just a bunch of data without group definitions, and then for each group you added you would just add the DataView options to your group definition.

There is nothing wrong with adding data once. But this data does not have to be loaded into the graph all at once. You can manually process this data which gives you a lot more control over what happens. 

I think the groups of a graph2d are what defines the graph. They are inherently different from a view of the data. They denote the relationship of points. I'll try to illustrate this below. 

Let me explain why I made it so that point are allocated in groups as opposed to groups querying points. In a graph, I felt a points alone are not relevant (point clouds aside). The relevance comes from a set of points. The relationship among each other, change over time. That is why points in a collection are grouped. They share a style. Hope that clarifies a bit.

I don't think the current design is perfect. After the initial setup with just lines, the barcharts came into being. These could use styling information per datapoint and I think that is a valid issue. Unfortunately the styling is locked into the groups (and static) at the moment.  I don't think expanding the group system is the way to go. What IS required is a reimagining of how groups should function. Groups are currently an old design from the initial line approach and do not perfectly suit the different modes. 

The point of what the dataView is supposed to be Id like to refer to @josdejong. He has built the dataset/view system and has a better perspective on this. 

I'd be very open to a reimagining of the graph2d. We're making great progress with the 4.0 release and there are a lot of great architecture changes. Maybe we could do the same for the graph2d. Groups are great for lines. For points or bars they are good for the legends. It really depends on the type of data you're showing. Colorcoding information or dynamically emphasizing values with color is not what the current setup is made for. Maybe a good solution would be to give groups an option to set styling information based on the point. Like an insertable callback function. 

If we solve it like that, would your solution with the dataViews still be needed?

Regards,

Alex

**Comment by spatialillusions** [comment]
Hi, 

There could be a lot of better ways to do this, so all input is welcome. The use case that I'm seeing is the following:
Every ten seconds or so, you send a request to your web server asking it for statistics for the last time period and it replies with something like. {datetime:YYYY-MM-DDThh:mm:ss.SSS, num_request:int, processor_load:float, average_responce_time:int} lets call this "reply".

I can add this to my DataSet with:
```javascript
reply["id"] = dataset.max("id").id + 1;
dataset.add(reply)
```
The other day I made a PR that makes it possible to rename properties in a DataView, so if I want to draw a line graph with my num_requests I can simply do:
```javascript
var view = new vis.DataView(data, {
  fields: {id:"id",datetime:"x",num_requests:"y"}
});
var graph = new vis.Graph2d(container, view);
```
And the graph2d will update when I just keep on pushing data into my DataSet, and if I get the correct id (that I will be able to get if I click on the bar) I will be able to get all information from my reply. Store data in one place, let the Views transform it for different kinds of visualisation.

My idea is that if I now also want to display a line graph of the processor_load, I would be able to do:
```javascript
var view = new vis.DataView(data, [{
    id:1,
    fields: {id:"id",datetime:"x",num_requests:"y"}
},
{
    id:2,
    fields: {id:"id",datetime:"x",processor_load:"y"}
}]);
var graph = new vis.Graph2d(container, view);
```
And this would now be two different groups in the graph and I could give them different properties and style them as I wanted. 

When I looked in the code, this approach seemed much, much simpler than trying to put the filter in the group definition. But like I said before, it be that it alters the view concept too much and maybe the data transformations that Jos has been thinking about would be a better solution. 

My estimate of what has to be done to make this work is the following:
- In DataSet.js around line 426 add something that triggers the filter function if an id has been set in the filter. This is so that we make sure that we copy the values of the item and not the item. Otherwise we will change the original group id when we set the group id.
-  In DataSet.js around line 439 add code to set item.group = options.id.
- In DataView.js around line 175 add code that if we have an array of options, call DataView.get(option,data) with each of the options as a single option, and the result from the previous call, so that we merge all data together  and then returns the result. 

I could be completely wrong, but I think that is all you will have to do... 

/Måns

**Comment by josdejong** [comment]
We could rethink the way you load multiple graphs in a Graph2d. Right now, you have to feed a single array containing x,y values, and to distinguish multiple groups, you have to add a `group` property. This may not fit that nicely with the way how you typically retrieve data:

- You can have different Arrays for different types of data, each representing a single line in the graph. 

  In order to use this in Graph2d, you will have to merge them into a single Array, and add a `group` property to distinguish them. Internally, Graph2d in turn will split this apart. Sounds like double work.

- You can have a table with multiple columns as source, each to be displayed as a different line in the graph. This is @spatialillusions case if I'm right: a line for processor load, a line for number of requests, etc.

  In order to use this in Graph2d, you will have to iterate over your data table, and generate a new data point with correct `group` for each column value in a new Array, which can be. Sounds like double work.

It may make sense to better meet these common use cases. Some ideas:

- The data for a single line (group) could be provided as a property of the groups, like:

  ```js
  var groups = new vis.DataSet([
    {
      id: 1,
      content: 'Group 1',
      options: {...},
      data: new vis.DataSet([ {x: ..., y: ...}, ... ])
    },
    {
      id: 2,
      ...
    }
  ]);
  ```

- Support table like data structures, be able to select the field with y values for different groups:

  ```js
  var items = vis.DataSet([
    {time: '2015-03-01T22:01:45.000Z', cpu: 0.5, requests: 2300, ... },
    {time: '2015-03-01T22:01:46.000Z', cpu: 0.41, requests: 1805, ... },
    ...
  ]);

  // specify which fields from the DataSet to use as x/y per group
  var groups = vis.DataSet([
    {id: 1, content: 'CPU usage', x: 'time', y: 'cpu'},
    {id: 2, content: 'Requests per second', x: 'time', y: 'request'},
    ...
  ]);
  ```

**Comment by mojoaxel** [comment]
@spatialillusions Is this still an issue? If not can you please close this. Thanks!
