### ISSUE TITLE
Navigating to specific node within a cluster

### ISSUE THREAD

**Issue by valtih1978** [almende/vis#696]
`focusOnNode` fails when I focus on a node within cluster. `SelectNodes` also fails when selection of clustered node is requested. I decided to select nodes by name because of low graph performance even in cluster mode (less than 2 000 nodes and 8 000 connections) and it is impossible to find the nodes by manual cluster expansion. I feel it is wrong that I add a node into a graph and receive that `graph does not contain that node` afterwards. How can I add it again?

**Comment by AlexDM0** [comment]
You can open the cluster to regain the node, there currently is not another way. Select and focus look in the visible nodes, so the node in the cluster is not taken into account.

In 4.0 however, the clustering system has had a complete overhaul. There will be manual control over the clusters and nodes will not be removed from the global stack. Whether or not focus will focus on the cluster containing the node I'm not sure yet, but functions will be available that allow you to identify the containing cluster.

There are many things wrong with the current clustering setup, which is why it has been overhauled. We expect 4.0 around april, though the branch is VERY unstable at the moment and the API and documentation is not available now.

**Comment by valtih1978** [comment]
Cool. If lookup and programmatic expanstion of clusters will be available then it will be easy to focus on the internal nodes :)

**Comment by valtih1978** [comment]
BTW, I have noticed that when I collapse single-edge connected graph, multiple edges appear between the clusters. This defeats clustering advantages, IMO, the CPU performance and clogs up the screen. Might be these are the bugs and will be fixed in 4.0 also.

**Comment by AlexDM0** [comment]
I'm going by all things marked for v4 and checking if they are in yet. This one has been added. I'll mark it as done and close it on release of v4.

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed.
