### ISSUE TITLE
Problems with images nodes

### ISSUE THREAD

**Issue by kenansalloum** [almende/vis#700]
the edges are not straight and always are show as half-circle !!
and physics options are not working

**Comment by AlexDM0** [comment]
Hi,

Try turning off the smoothCurves. 

Regards,

Alex

**Comment by kenansalloum** [comment]
thanks, how can i make Repulsion between the edges?

**Comment by AlexDM0** [comment]
Hi,

You can't I'm afraid. To solve this problem we introduced the smoothCurves. Those have an invisible node that guides the curve. That node has repulsion. 

It might be fun to lock an invisible node in the center of a straight curve, thereby giving it repulsion. I'll keep this in mind after the launch of v4. 

At the moment though, it's either smooth and thus (likely) curved or straight.  The nodes do repel each other so you may get some decent results if you play with the physics. Take a look at example 25 for that. 

Regards,

Alex

**Comment by kenansalloum** [comment]
![untitled](https://cloud.githubusercontent.com/assets/7274591/6579903/cabd1988-c755-11e4-881c-dd6eb9627fce.png)
help me plz.

**Comment by josdejong** [comment]
You can set `var options = {configurePhysics: true}` and fiddle around with the physics settings. See this example: http://visjs.org/examples/network/25_physics_configuration.html

**Comment by kenansalloum** [comment]
after generate options and copy it to code ,but anything doesn't change.
This is my code:

   var options = 
  {
    zoomable: false,
    smoothCurves: false,
    dragNodes: true,
    network: {barnesHut: {enabled: false}, repulsion: {nodeDistance: 300}}
};

**Comment by AlexDM0** [comment]
Could you make a JSBin with your nodes so we can help solve the problem? With default settings and smoothCurves off I think it will just work.

Regards,

Alex

**Comment by kenansalloum** [comment]
http://jsbin.com/pexuhesile/1/
thanks Alex

**Comment by AlexDM0** [comment]
Hi,

Could you please make sure the jsbin is functional next time? :)

You have an interesting case here. Basically, because the edges are so long (you can also set them in the physics options if they are all the same length), the net effect of the repulsion (at the strength you supply) to each other is very small. What happens then is that the central gravity pulls the nodes to the center, resulting in your case. The repulsion physics solver is not very well documented so the nodeDistance is not very clear. You set it the same size as the length of the edges but the real length you want is between the nodes connected to the edges in a circle so the distance is much greater. 

To solve this you can do a few things: 

Increase the nodeDistance to say 30000. I would recommend you use the BarnesHut solver and set the gravitationalConstant to about -10000.

You could also turn down the central gravity but I do not recommend that. Finally, as Jos and I mentioned, give the configurePhysics:true option a try. 

Just to clarify, this has nothing to do with the nodes being images, the physics is independent of the draw style. 

Regards,

Alex

**Comment by AlexDM0** [comment]
I think this issue is solved. If there's anything else, please let us know

Regards,

Alex
