### ISSUE TITLE
Edit Mode to Connect Nodes

### ISSUE THREAD

**Issue by rafaelthca** [almende/vis#712]
Is there a way to enable edit mode to connect nodes using my own function call instead the default 'Add Edge' button?

Sorry if it is a duplicate question.

Great job with this library.

**Comment by AlexDM0** [comment]
Hi Rafael,

At the moment no, but in 4.0 this will be possible. We plan 4.0 around april.

Regards,

Alex

**Comment by valtih1978** [comment]
I did that. Check it out [the demo](http://valtih1978.github.io/VisualDict/almende-vis.html) if it does what you want (use Ctrl when edge is selected). As bonus, you can also draw new edges when Ctrl is pressed. Basically, edge is tied to  `addEdgeSpan` and `backSpan` of 
network.manipulationDOM, which is created by automatically by vis.js when your app starts. These elements have `onclick` handler, bound to enter/leave the edit mode and depending on whether I want to enter or leave I called onclick of addEdgeSpan or backSpan element explicitly. I stimulated the mode change, clicking those hidden buttons programmatically. In fact 

```javascript
this.manipulationDOM['addEdgeSpan'].onclick = this._createAddEdgeToolbar.bind(this)
```

and 

```javascript
this.manipulationDOM['backSpan'].onclick = this._createManipulatorBar.bind(this);
```

I stimulated onclick [because I failed to call network._crateManipulatorBar/_createAddEdgeToolbar directly](https://github.com/almende/vis/issues/605). Now, I know that you can 

```javascript 
network._createManipulatorBar.call(network)
```
to exit the edit mode. _createManipulatorBar basically creates default edit mode wheras _createAddEdgeToolbar switches into edit edges submode. We exit the edge mode when  _createManipulatorBar is recovered.

I had also `dataManipulation: {enabled: true, initiallyVisible:false},` in the options and css `.network-manipulationLabel {display: none}` to make the almende control bar invisible. You cannot get rid of it completely -- the edit functions are tied to it. Quite oppositely, you need to create the edit bar in the network create options, if you want the graph edit functions enabled at all.

The only thing you can bypass is onclick. Instead of `network.manipulationDOM['addEdgeSpan'].onclick()` you can `network._createAddEdgeToolbar .call(network)` to enter the edge edit mode.

All this question looks duplicate.

**Comment by AlexDM0** [comment]
I'm going by all things marked for v4 and checking if they are in yet. This one has been added. I'll mark it as done and close it on release of v4.

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed.
