### ISSUE TITLE
dataAxis.customRange.left.min = 0, interpolation values below zero

### ISSUE THREAD

**Issue by AdamNowaczyk** [almende/vis#719]
Hi,

Another issue with dataAxis.customRange.left.min = 0. Interpolation 'pushes' some graph parts below zero, which I know is part of sideffect of interpolation between two zero points, but with min value of y-axis it looks like there are no values. Even if that would be visible, less than zero values are wrong for this type of graph (e.g. you cannot have less than zero throughput). 

Is there any way of solving this except disabling interpolation and going with linear?

--
Thanks,
Adam

**Comment by AlexDM0** [comment]
Hi Adam, 

could you make a jsBin to show this?

Regards,

Alex

**Comment by AdamNowaczyk** [comment]
Hi Alex,

Here's the jsBin to show this:
http://jsbin.com/cayoxujimo

I understand it is just the way interpolation works, but was wondering if it's possible to somehow 'force' values to be always >= dataAxis.customRange.left.min.

--
Thanks,
Adam

**Comment by AlexDM0** [comment]
Hi Adam,

I'm afraid it is not possible to partially interpolate. The interpolation takes 4 points into account. Because there are no actual datapoints being used for the interpolation but svg curves, I cannot abruptly force them into a different configuration locally.

You could resample your data and do it like that? If more datapoints are available it is more likely that the curve follows the path.

Regards,

Alex

**Comment by AdamNowaczyk** [comment]
Yeah, that's what I was thinking, that it's just SVG path and there isn't anything we can do about it. Most likely I'll have to go with no interpolation, but then the graph looks 'spiky'. The thing is that I allow zoom in/out and at some point I won't be able to deliver required 'density' of the points (data gathered every 30 seconds). 

Can you maybe help me out with second issue I have? It's #716.

--
Thanks,
Adam
