### ISSUE TITLE
Week numbers

### ISSUE THREAD

**Issue by almusawi** [almende/vis#734]
Hi,
Is it possible to add or show the week numbers on the timeline? and how if it is possible?

thanks

**Comment by josdejong** [comment]
Yes, you can customize the labels on the time axis. Have a look at the configuration option `format`:

http://visjs.org/docs/timeline.html#Configuration_Options

**Comment by MuneshThakur** [comment]
hi it's possible to make  fix left hand datatable with 3 Coloums and 10 Row data should not accept in alphabetic order  in timeline Example 15 mobile.html pls Resoponse me as soon as possible. if you can provide a demo , pls provide.

thank you

**Comment by almusawi** [comment]
Hi all, 
Thanks for the reply.

what I meant here to show the week numbers such as week15, week16, week17, etc. on the time like. I  can see the format of the weekday and months, but not the weeks.

**Comment by josdejong** [comment]
Yes indeed, you can adjust the labels such that they display the weeknumber rather than the weekday and month. For example with this option:

```js
  var options = {
    format: {
      majorLabels: {
        'hour': 'dddd D MMMM [week] w'
      }
    }
  }
```

Will display `'Tuesday 7 april week 15'` when zoomed in to the hour scale.

The formatting options are described here: http://momentjs.com/docs/#/displaying/format/ (it's referred from the vis.js docs).

If you mean like setting a scale such that the timeline dislays a grid line every 7 days, such a scale is not supported.
