### ISSUE TITLE
Another Point of view 

### ISSUE THREAD

**Issue by Min-gu** [almende/vis#746]
Hello

i've been using vis.js since  while,,

now i wanna edit the starting position of the network

it starts with top 50% and left 50%  maybe

i want to set left to something like 20%  but to keep the container div size as it is

Regards ,,

**Comment by AlexDM0** [comment]
Hi,

You cant. The container is a div that is fully filled. It also does not make any sense. If you'd like to change the size of the container, then use css to change the size of the container. There should be no reason you'd want to keep the size of the container the same because you can just put the container div inside of another div and position everything the way you want.

Regards,

Alex

**Comment by AlexDM0** [comment]
Sorry I may have misread your issue. If you just leave the network size at it's default 100%, you can size the containing div anything you'd like and position it wherever you'd like.

Is the problem here that you have altered the width and height of the network using the options? Could you make a JSbin to show the problem?

Regards,

Alex

**Comment by Min-gu** [comment]
thanks for reply ..
but i think i didn't explain my problem well 

what i want to change is not the div itself

just the network position inside the div

it's like i want the user to have the same space to move the network but the change the created network position

**Comment by AlexDM0** [comment]
Hi,

Seems I didn't understand you initially. Well in this case you can use the getScale and moveTo methods to position the camera anywhere you want. Take a look at the animation example for more details.

Regards,

Alex

**Comment by Min-gu** [comment]
i tried moveto but i couldn't do it

i want something like this ..

now when the page loads
the network shows like this
![untitled2](https://cloud.githubusercontent.com/assets/11696668/6882013/c7fbd104-d587-11e4-97d8-2cea983f4115.png)

i want it to show like 
![untitled](https://cloud.githubusercontent.com/assets/11696668/6882014/dab4416e-d587-11e4-96f3-19c4823f99f5.png)

of course i can size the div but i want the space to stay as it's

**Comment by kenansalloum** [comment]
Hi
 I'm having the same problem and i couldn't solve it

**Comment by AlexDM0** [comment]
Hi, 

Ok lets make this a small lesson :).

First I'll assume you have stabilization enabled (which it is by default). So what happens is that the physics engine solves the position for all nodes and edges. In vis version 3.x (latest version at the moment of writing this comment), this is done immediately after calling the constructor:

```
var network = new vis.Network(...)
```

So what we can do, is tell the network to move after the stabilization:
http://jsbin.com/juqolipune/4/edit?html,output

Lets do this with the stabilizationIterationsDone event. The reason for this is that future versions will start stabilization on a timeout. Because we now use 3.x, the network should not have data to stabilize before we bind the event because otherwise we'll bind the event AFTER the stabilization, rendering it useless. So:
http://jsbin.com/juqolipune/5/edit?html,output

Now it's not perfectly positioned. This is because the x and y values of 200 and -7 are guesses on my side. But we can do better! We will first get some information on the canvas. We will need the bounding box for all nodes, the positions of the corners of the canvas and the center position of the canvas.

The moveTo function moves the center point! This is important to remember. So finally we get:
http://jsbin.com/juqolipune/6/edit?html,output

If there's any questions let me know.

Regards,

Alex

**Comment by kenansalloum** [comment]
thanks a lot man, but how can i make position responsive "like percent"

**Comment by AlexDM0** [comment]
You can bind a listener to the window resize event and do exactly the same as I've done in the jsbin. 

Regards

**Comment by AlexDM0** [comment]
I think this issue is resolved.

**Comment by josdejong** [comment]
@AlexDM0 still, it would be nice if Networks gets an `autoResize` option like Timeline has

**Comment by AlexDM0** [comment]
True and it has it in 4.0, thereby fixing the issue about rendering in hidden divs.  Although the alignment is a different matter.
