### ISSUE TITLE
blur effect requires for neighbour nodes

### ISSUE THREAD

**Issue by mmcsivakumar** [almende/vis#760]
I need to display the blur effect for the neighbour nodes in the example "29_neighbourhood_highlight" instead of changing the background color of the node.

**Comment by AlexDM0** [comment]
Hi,

Dynamically blurring of drawn nodes or edges is not supported and not likely to be implemented due to severe performance impact. You could however fake this. Make an image or svg or a blurred node, assign the style to a group and dynamically update the nodes and allocate them in that group. 

Regards,

Alex

**Comment by mmcsivakumar** [comment]
Fine. 

Thanks You Very Much.
