### ISSUE TITLE
Suggestion - Edge

### ISSUE THREAD

**Issue by rafal-software** [almende/vis#767]
My suggestion is to create Edge data structure to get easy information (eg. for doubleclick) connected with node from - to. Now it is possible by putting some customized data format as an id of Edge eg. id: 1-2 it means from is 1 to is 2.
It is just my suggestion the vis project is very, very good job!!!

Kind regards.

**Comment by AlexDM0** [comment]
Hi,

I'm not sure what the enhancement is you propose. Are you referring to expanding the amount of information normally supplied in the click, select, etc events?

The reason we do not do this is because it is up to each user to determine what sort of information they want to see. That is why we supply you with the ID. You can use that to look up the data you want in your own datasets.

Regards,

Alex

**Comment by AlexDM0** [comment]
closed due to inactivity
