### ISSUE TITLE
Timeline: Option for hourly major steps when scale is minute

### ISSUE THREAD

**Issue by toxix** [almende/vis#801]
Requesting the future to set a major step each hour if the minor step is minute. This is inconsistent to all other scales, where it sets major steps on the next bigger scale/unit.

Just changed it quick and derty:
```
--- a/lib/timeline/TimeStep.js
+++ b/lib/timeline/TimeStep.js
@@ -483,7 +483,7 @@ TimeStep.prototype.isMajor = function() {
     case 'second':
       return (this.current.getSeconds() == 0);
     case 'minute':
-      return (this.current.getHours() == 0) && (this.current.getMinutes() == 0);
+      return (this.current.getMinutes() == 0);
     case 'hour':
       return (this.current.getHours() == 0);
     case 'weekday': // intentional fall through
```
maybe you want to expose the old/new behaviour with an option.

**Comment by josdejong** [comment]
This was done because (with the current implementation) the major label does not give extra information for different hours, on minute scale the major label is for example "Tuesday 28 April" and the minor scale "9:00", "9:15", "9:30", etc. It was just redundant to display "Tuesday 28 April" for every hour. 

Do you have a specific case where you have formatted the major label such that it differs for every hour at minute scale?
