### ISSUE TITLE
Is it feasible to get only timeline.js instead of the all the modules ( network,graphs etc ) all in a single file?

### ISSUE THREAD

**Issue by ghost** [almende/vis#808]
Are these modules (network,graphs,timeline) dependent on each other? If not then can we only get timeline.js ?

**Comment by josdejong** [comment]
Yes you can create your own custom builds of the library, see docs: https://github.com/almende/vis#build

**Comment by verybigelephants** [comment]
would it be perhaps possible to release separate modules as separate javascripts along with the one main file that you can get from the website? because you need to install 3 new libraries in order get only one module. it is very uncomfortable for regular people who don't work with npm and browserify

**Comment by josdejong** [comment]
Yes maybe we could provide additional files like `vis-timeline.js` and `vis-network.js` in the `./dist` folder.

**Comment by verybigelephants** [comment]
would be cool!

**Comment by mojoaxel** [comment]
This implemented since 4.16.0
