### ISSUE TITLE
Suppress multi-selection

### ISSUE THREAD

**Issue by xogeny** [almende/vis#811]
It would be useful for me to suppress multi-selection in both the timeline and network views.  It doesn't look like this is implemented.  But it seems like it would be relatively simple.  What I have in mind would be simply an additional setting `multiselect` that would default to `true` but if `false` would suppress selection of multiple items.

The question here is...am I missing something regarding existing functionality that would enable this.  If not, would you accept a pull request including such functionality (including updates to documentation)?

**Comment by AlexDM0** [comment]
Hi Michael,

This is not possible at the moment but we'll take it into account. We'd be happy to accept a pull request for this except that we're finalizing our 4.0 release, which is quite a big rewrite of at least the network and some of the other modules. I'll see if we can add this (as well as the shift or control hotkey for network) in the next release as it is pretty easy to implement. 

In general we're always very open to community contributions, it would just be a shame if it had to be redone due to our rewrite :)

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi Michael,

Small update, we have added this to the 4.0 branch.

Regards

**Comment by AlexDM0** [comment]
With the launch of v4, this issue can be closed. It is now blocked by default.
