### ISSUE TITLE
Network, Hierarchy view. Canvas scrollbar

### ISSUE THREAD

**Issue by moaliba** [almende/vis#813]
Hi,
I use hierarchy view with "direction" option. I use canvas to draw chart. when there are many nodes in tree, depend on screen size only some nodes are visible. Canvas does not have scroll bar to show all nodes. 
This is my options:

```js
var options = {
    height: '600px',
    smoothCurves:true,
    nodes:nodes,
    edges:edges,
    keyboard: true,
    zoomable:false,
    dragNetwork:false,
    dragNodes:true,
    stabilize:false,
    hover:true,
    dataManipulation: {
      enabled: false,
      initiallyVisible: false
    },
    hierarchicalLayout: {
      enabled:true,
      levelSeparation: 170,
      nodeSpacing: 110,
      direction: "UD",
      layout: "direction"
    },
    physics: {
      barnesHut: {
          enabled: false,
          gravitationalConstant: -2000,
          centralGravity: 0.1,
          springLength: 95,
          springConstant: 0.04,
          damping: 0.09
      },
      repulsion: {
          centralGravity: 0.0,
          springLength: 50,
          springConstant: 0.05,
          nodeDistance: 300,
          damping: 0.09
      },
      hierarchicalRepulsion: {
          centralGravity: 0.0,
          springLength: 130,
          springConstant: 0.01,
          nodeDistance: 150,
          damping: 0.1
      }
    },
    locale:"en"
  };
```
Thanks.

**Comment by AlexDM0** [comment]
Hi,

That's right, the canvas does not have a scroll bar since it is like an image with a fixed width and height regardless of what you show in it. 

I don't think we will be adding a fake scrollbar to the network. 

You could fake this by changing the size of the canvas based on the nodes (get node positions at zoom or dragend events, convert them into dom units and do a setSize with the new height. If you also give your container div a set height, that will give you a scrollbar. 

Regards,

Alex

**Comment by AlexDM0** [comment]
A small note on your options, only the hierarchicalrepulsion settings are used, regardless of the other physics settings you define. Stabilization is forced with hierarchical view and you have quite a bit more options defined that do not need to be there because of the default settings. 

I see you disable zoom and dragging of the canvas, in that case you can just set the size of your canvas once and have the scrollbar of the container. 

You now set the height to 600px. If this doesn't fit, make it bigger. 

Regards,

Alex
