### ISSUE TITLE
Timeline group event listener

### ISSUE THREAD

**Issue by mast0r** [almende/vis#814]
Is it possible to add some event listener to the group? For example `click`? 
I've assigned some CSS class to each group and now I want to attach `click` event listener with jQuery to it. No success... I suspect that this is suppressed somehow from the timeline :(

**Comment by josdejong** [comment]
Yes you should be able to use HTML in groups and items, including links and event handlers. It could be that attaching an `onclick` handler doesn't work (this is fixed in the `v4` branch). 

Besides that, you could listen for click events globally using `timeline.on('click', function (props) { ...})` and check whether `props.what == 'group-label'` in the callback.

**Comment by mast0r** [comment]
Thank you, I will try it!
