### ISSUE TITLE
Forcing maximum node width, auto multi-line a label

### ISSUE THREAD

**Issue by skinkie** [almende/vis#818]
When using a network with labels that are horizontally quite long, currently there doesn't seem to be a method to force the node's maximum width in such way the label gets spread over multiple lines. Adding newlines within the label makes it visually all much better.

**Comment by AlexDM0** [comment]
Hi Stefan,

It is very easy to write your own preprocessor for this. You can use a newline character '\n' for it.

Seeing as this would be about 3 lines of code, we will not add it to vis since everyone has different requirements. 

Regards,

Alex

**Comment by skinkie** [comment]
I just fail to see why extending maxWidth to work with labels next to images is such bad idea.

**Comment by AlexDM0** [comment]
Because the maxWidth parameter has a completely different purpose. It's for scaling certain node types by their value. I agree the naming should be done better and we have changed this  in 4.0 which will be released soon. 

We want to avoid too many options and especially ambiguous options. This would make using vis less intuitive and lead to unpredicted behaviour.

I'm not sure how images come into this discussion, as we've only talked about automatic line breaking of labels. The only reason I will not make this an option of vis is because it's very easy to do this yourself.

This makes vis more predictable, you give it a label without line breaks, you get a label without line breaks. If we have a default setting of say 30 characters and someone gets a line break without asking for one he will have to go through the docs and see how to disable it. If we disable it by default, I would argue most people will write the 3 lines of code to preprocess their labels in any way they want. 

If you have difficulty with preprocessing your labels manually, please let me know and I'll provide an example. 

Regards,

Alex

**Comment by skinkie** [comment]
I see you point, especially on predictability. What I envisioned is that the width of the node could be dynamically updated by the client, similar to moving a node. I am thinking more in the terms of "soft-hyphenation". I am currently exporting the contents directly from PostgreSQL, leaving me with SQL or postprocessing it in Javascript. Obviously I don't want a 30 char hard cut, but some heuristic based space replacement, but I should be quite capable of writing such thing :)

Thanks for your answers it is appreciated.

**Comment by AlexDM0** [comment]
Hi Stefan,

You're welcome :). When you say obviously you don't want a hard cut, that's exactly why we don't have it in vis ;) some people might, some people might want a ... Instead of a line break etc. 

Have fun using vis!
