### ISSUE TITLE
Edge length includes the height of the node

### ISSUE THREAD

**Issue by eipark** [almende/vis#833]
Edge labels display halfway along the length of the edge, but unfortunately, the edges seem to start at the middle of the node (in the case of a hierchical layout up down). 

Example:
![](https://s3.amazonaws.com/uploads.hipchat.com/10819/477180/oK1RMQVTPu0NbO4/Hublytics___HubSpot.jpg)

Ideally, the label would be along the calculated 'visible' length of the edge when it is static.

**Comment by AlexDM0** [comment]
Hi Ernie,

This is caused by the smooth curves. You can turn them off and everything will be much better. We could look into going from the edge of the node but it's quite computationally intensive to do so. 

The smooth curves are described by a formula with a nonlinear derivative. This means that even if we want position 0.5, it is not always the case in length. 

Anyway, for now just turn off the static smooth curves. 

Cheers

**Comment by eipark** [comment]
Ah that did the trick, thanks!
