### ISSUE TITLE
Need help with layout

### ISSUE THREAD

**Issue by say8425** [almende/vis#840]
If my nodes and nodes were same group, then I make have short length edges, or long length edges. <br> So I make clustering this behavior. And it works. But it's unclear. Nodes and nodes is clear, but group and group is not clear. Like this image.
![visjs_custom_clustering](https://cloud.githubusercontent.com/assets/3258867/7674032/a6b33a9c-fd59-11e4-809a-baeae605f76f.png)
But your example-27, world cup network, is so clear. And you said it can make with gephi or physics option. But I can not understand clearly. Could you explain more deeply? Thanks for reading.

**Comment by AlexDM0** [comment]
Hi,

I don't fully understand what you mean by clustering here or how you have done it. I'll assume your question is that you've played around with the length of the edges and it's a mess so how do you get a better result?

Take a look at example 28 where we use the physics model of vis. It's not like the result in example 27 but it's quite clear. Have you looked at the configurePhysics option? Take a look at example 25. 

In the upcoming version I have added a new physics model that is closer to what gephi used. Maybe that will help. 

A short explanation on physics: the nodes repel each other based on a gravitational model with a squared falloff. The nodes have a mass of 1, higher mass will give a higher repulsion but be careful when setting the mass! Alternatively you can change the gravitational constant to increase or decrease the repulsion over all. To counterbalance this, we have central gravity and the edges. 

The central gravity is a force on all nodes, regardless of mass that pulls them to the centre. 

The edges are modelled as springs. If you stretch them, they will pull back. The length is how long they want to be if they are not being pulled. The spring constant is how sturdy they are. In your specific case you probably want to increase the spring constant because your springs look a bit like rope so they are too weak for their length. 

Finally, smooth edges. We have dynamic and static smooth edges. You use dynamic (which is on by default.) what this means is that the edges are in fact modelled as a spring from the FROM node to an invisible node and a spring from the invisible node to the TO node. This means it is much more computationally expensive to use them if you have a lot of curves. Look at example 26 for what static smooth curves do. 

To conclude, look at example 25 to see what configure physics does. You need to disable dynamic smooth curves, increase springConstant and play with the settings. You'll never get it like example 27. With v4.0 you'll have the new model that's closer to it but you'll need gephi to reproduce it exactly. 

Regards,

Alex

**Comment by AlexDM0** [comment]
Maybe #867 and #902 can help you. I'll close this issue due to inactivity and information in those other two issues.
