### ISSUE TITLE
Grid Backgrounds does not attach .today class everywhere.

### ISSUE THREAD

**Issue by wouterhoogstra** [almende/vis#851]
The elements in the timeline do not get everywhere the .today class when it belongs to today. Especially on the higher zoom levels.

**Comment by AlexDM0** [comment]
Hi Wouter,

I take it you refer to the fact that when you zoom out and there is no separate indicator for day-level blocks that the coloring will not be shown? There is no exception for today.

This is by design actually. An alternative is to add your own background items. Those will always be visible, regardless of zoomlevel.

Regards,

Alex

**Comment by wouterhoogstra** [comment]
Hi Alex,

That seems to be the issue. I will solve it by adding my own background item. Thanks for the tip!

Regards,

Wouter
