### ISSUE TITLE
Export Network as SVG / v4 ?

### ISSUE THREAD

**Issue by nathalizator** [almende/vis#868]
Hello Alex,
I have read the Post about exporting the network, i heard it was possible to save as image but in this post you said that there will be a release that might give the possibility to export as svg ? ( cf https://github.com/almende/vis/issues/723 ) . Did i misunderstood? I try to search into the network documentation but didn't find anything such as exporting.

**Comment by AlexDM0** [comment]
Hi, 

Yes you do misunderstand. In that issue, Justin suggested he may be interested in building an SVG renderer for exporting. I told him that it would be wise to wait for the 4.0 release since a lot has changed. We do not plan to support SVG, but if someone makes it and does a pull request (or has a standalone tool for it, which would probably be better) we don't mind including it in our distribution.

As for exporting, you can use phantomJS or just rightclick the network and 'save as image'. 

Regards,

Alex

**Comment by nathalizator** [comment]
Thank you for your answer, sorry for the mistake.

**Comment by AlexDM0** [comment]
That's ok :) have fun using vis!
