### ISSUE TITLE
After setData(), can I make fix viewPosition?

### ISSUE THREAD

**Issue by say8425** [almende/vis#907]
After setData() with `mainNetwork.setData(slideDataSet);` then, viewPosition move to center.
I want to prevent this. So I code like this.

```java-script
var oldViewPosition = mainNetwork.getViewPosition();
mainNetwork.setData(slideDataSet);
mainNetwork.moveTo(oldViewPosition);
```

But it's not works. So I try put in `mainNetwork.on('startStabilizing')`. and `mainNetwork.on('stabilized')`.

```java-script
var oldViewPosition = mainNetwork.getViewPosition();
mainNetwork.setData(slideDataSet);

mainNetwork.on('startStabilizing', function () {
    mainNetwork.moveTo(oldViewPosition);
}
```

In this case, `moveTo()` worked. But after stabilized the view position back to the center of view. So I try put in `mainNetwork.on('stabilized')`. But it's not worked too.

How can I prevent view move to center of view, after setData()?

**Comment by AlexDM0** [comment]
Hi,

I think you're looking for the fit option in the stabilization object. 

http://visjs.org/docs/network/physics.html

As a guess as to why your method is not working, try putting it in the stabilizationIterationsDone event. 

If the fit option is true, it fits after stabilising. The startStabilizing event is fired before that so that won't work. Since you manually supply the amount of iterations, the stabilization process does not always result in a stabilized state. This means the stabilized event has not fired. 

Regards,

Alex

**Comment by AlexDM0** [comment]
Additionally, your moveto arguments are not valid. It should be like this:

```
var oldViewPosition = mainNetwork.getViewPosition();
mainNetwork.moveTo({position:oldViewPosition});
```
