### ISSUE TITLE
resize groups by dragging them?

### ISSUE THREAD

**Issue by Blugh** [almende/vis#929]
Hi guys

I am wondering if it would be possible to allow a user to resize the groups on the timeline by selecting the bottom edge and dargging it up or down. I will attempt this, but am looking for a bit of guidance as to what the recommended way and where to do this within the vis,js code would be.

**Comment by josdejong** [comment]
Can you explain about your use case? Why do you would need to adjust the height of groups?

**Comment by Blugh** [comment]
The users wish to do this in the scenario where they have many groups that overflow on the page. 

They would like to be able to drag a group to be smaller so that they can fit as many groups into the view as possible to get a more consolidated view of all their schedules.

**Comment by josdejong** [comment]
And should the items shrink accordingly or something, so they still fit?

**Comment by Blugh** [comment]
yes

**Comment by Blugh** [comment]
Hi @josdejong 

Any update on this? As I mentioned earlier, I am willing to attempt this, I just need a bit of guidance?

**Comment by josdejong** [comment]
I don't see how you could just "drag the groups smaller": the displayed items will not fit then. You could squeeze the margins and text size a bit but that doesn't help a lot. If you really want to make the group smaller you will have to display less information.

Just an idea: how about making every group collapsible (clickable triangle left from the group label), where when expanded the group shows all items with all information. And when collapsed it shows items in a very minimal form: just a colored bar or circle with a height of say 6px, and instead of showing the text contents inside the items, it's only shown as a popup when hovering the item. 
You can put HTML in group labels to get this collapsible functionality working, and you could create a new item type to display items in a very small form factor.

**Comment by Blugh** [comment]
Hi @josdejong 

Apologies for the very late reply. Your idea will work well, I will give that a go. Thank you.

**Comment by josdejong** [comment]
Ok that's good to hear, thanks
