### ISSUE TITLE
Network svg image don't respect original image size / v4

### ISSUE THREAD

**Issue by nathalizator** [almende/vis#936]
Hi ,
I upgrade to the new v4 network, sadly it seems that the size on my svg image are not similar to their original size.   Some of my icons have the right size and others see their  size enlarged ( not distorted as in the old v4). Here is an example . The black background node on the left should have the good size ( like on the right side which is old version of vis.js )

**Comment by AlexDM0** [comment]
Hi,

I don't really have any idea what you're doing. I'm not sure how to answer this. A lot of the options have been renamed or refactored. Radius has been replaced by size for instance. 

Without more information I really cannot help you. 

Regards

**Comment by nathalizator** [comment]
its okay i have use the "size" inside my object and now it is working. But let me try to explain one more time what is the problem ( which is not a problem anymore if i use "size" ).
I have two different size of svg image : 50x50 and 100x100 for example. I set those size in illustrator. When i upload those image in my network, the 50x50 are enlarged and the 100x100 are ok. 
With the old version, the network used to keep the original size of the svg image that i set in illustrator. But not it looks like the smaller icon scale to the bigger.

**Comment by nathalizator** [comment]
I think it's a bug because the svg image used to keep the original size of the image with the old version. It is annoying when you have different size of svg image.

**Comment by AlexDM0** [comment]
Hi,

I see, images indeed are scaled to the size option. This is not a big but intended. This is because the only way to use SVG icons as well as images at a certain size was to resize each and every one of them. To fix this the size parameter works on nearly all nodes except the ones getting size from the label. 

There was another issue that raises the question to set options of node type specific properties and we'll think about a clean solution for this. If we have a nice way to provide options for the node shape specific parameters, a scaleToSize could be added for the images types?

Regards,

Alex

**Comment by AlexDM0** [comment]
Hi,

I've added this in the release that will be done today.

It's called {nodes:{shapeProperties:{useImageSize:6}} and only applies to image and circularImage shapes.

Regards

**Comment by AlexDM0** [comment]
This has just been released in v4.6.0
