### ISSUE TITLE
Bar-chart 3D slow performance

### ISSUE THREAD

**Issue by nikodll** [almende/vis#988]
Hi,

While running the bar-chart example, with a larger number of data points (128x128 bars), the bar-chart performs very, very slow (around 0.5fps). Is it normal? Is there a way to increase its performance? As a workaround I set the style to "line", in this case performance boosts back to 60 (or so) fps, but obviously it doesn't look as good any more.

Thank you in advance for any suggestions.
Nikita.

**Comment by josdejong** [comment]
Is your question about the Graph2d or Graph3d?

**Comment by nikodll** [comment]
About the Graph3d. The FPS performance I was referring to is about when I try to rotate the scene.

**Comment by nikodll** [comment]
The original example I used is called "Graph 3D tooltips" and can be found here: http://almende.github.io/chap-links-library/js/graph3d/examples/example15_tooltips.html
I don't think graphic card is what limits here the performance (I tried on various, including very fast ones), and I see 1 entire CPU core is busy with 100% load, so it must be the JS that is busy with something. Profiling in Chrome shows function Graph3d._redrawDataBar occupies the most of the CPU time.

**Comment by josdejong** [comment]
The Graph3d emulates a 3d system on 2d HTML Canvas. What you're rendering (in the order of 10000 data points) is the limit of what's doable that way. 

We would need to use WebGL instead of 2D-Canvas to allow drawing more data, but this is not (yet) standard supported in all browsers. We may rework Graph3d to a WebGL based version some day, would be cool.

Please note that you're referring to an example of the predecessor of the vis.js library, here is the corresponding example in vis.js: http://visjs.org/examples/graph3d/11_tooltips.html

**Comment by nikodll** [comment]
Thank you for the quick response! I see your point about WebGL, and I wasn't even aware it's a pure 2d canvas. In this case it performs amazingly well :)

In general, I think vis.js is an awesome library. Having it rendering 3D in WebGL would be yet a huuuge extra feature!

**Comment by josdejong** [comment]
Thanks

> In this case it performs amazingly well :)

Yeah I think so too :). All credit for the development teams implementing HTML Canvas in today's browsers...
